// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { FGuid } from "../objects/CoreUObject/Guid";
import { CustomVersionGuid } from "./registry";
import * as FAnimationCustomVersion from "./custom-versions-enums/FAnimationCustomVersion";
import * as FClothingAssetCustomVersion from "./custom-versions-enums/FClothingAssetCustomVersion";
import * as FClothConfigNvCustomVersion from "./custom-versions-enums/FClothConfigNvCustomVersion";
import * as FReleaseObjectVersion from "./custom-versions-enums/FReleaseObjectVersion";
import * as FBlueprintsObjectVersion from "./custom-versions-enums/FBlueprintsObjectVersion";
import * as FBuildObjectVersion from "./custom-versions-enums/FBuildObjectVersion";
import * as FCoreObjectVersion from "./custom-versions-enums/FCoreObjectVersion";
import * as FEditorObjectVersion from "./custom-versions-enums/FEditorObjectVersion";
import * as FFrameworkObjectVersion from "./custom-versions-enums/FFrameworkObjectVersion";
import * as FMobileObjectVersion from "./custom-versions-enums/FMobileObjectVersion";
import * as FNetworkingObjectVersion from "./custom-versions-enums/FNetworkingObjectVersion";
import * as FOnlineObjectVersion from "./custom-versions-enums/FOnlineObjectVersion";
import * as FPhysicsObjectVersion from "./custom-versions-enums/FPhysicsObjectVersion";
import * as FPlatformObjectVersion from "./custom-versions-enums/FPlatformObjectVersion";
import * as FRenderingObjectVersion from "./custom-versions-enums/FRenderingObjectVersion";
import * as FSequencerObjectVersion from "./custom-versions-enums/FSequencerObjectVersion";
import * as FVRObjectVersion from "./custom-versions-enums/FVRObjectVersion";
import * as FLoadTimesObjectVersion from "./custom-versions-enums/FLoadTimesObjectVersion";
import * as FGeometryObjectVersion from "./custom-versions-enums/FGeometryObjectVersion";
import * as FAnimPhysObjectVersion from "./custom-versions-enums/FAnimPhysObjectVersion";
import * as FAnimObjectVersion from "./custom-versions-enums/FAnimObjectVersion";
import * as FReflectionCaptureObjectVersion from "./custom-versions-enums/FReflectionCaptureObjectVersion";
import * as FAutomationObjectVersion from "./custom-versions-enums/FAutomationObjectVersion";
import * as FFortniteMainBranchObjectVersion from "./custom-versions-enums/FFortniteMainBranchObjectVersion";
import * as FFortniteValkyrieBranchObjectVersion from "./custom-versions-enums/FFortniteValkyrieBranchObjectVersion";
import * as FFortniteSeasonBranchObjectVersion from "./custom-versions-enums/FFortniteSeasonBranchObjectVersion";
import * as FFortniteReleaseBranchCustomObjectVersion from "./custom-versions-enums/FFortniteReleaseBranchCustomObjectVersion";
import * as FEnterpriseObjectVersion from "./custom-versions-enums/FEnterpriseObjectVersion";
import * as FNiagaraObjectVersion from "./custom-versions-enums/FNiagaraObjectVersion";
import * as FDestructionObjectVersion from "./custom-versions-enums/FDestructionObjectVersion";
import * as FExternalPhysicsCustomObjectVersion from "./custom-versions-enums/FExternalPhysicsCustomObjectVersion";
import * as FExternalPhysicsMaterialCustomObjectVersion from "./custom-versions-enums/FExternalPhysicsMaterialCustomObjectVersion";
import * as FCineCameraObjectVersion from "./custom-versions-enums/FCineCameraObjectVersion";
import * as FVirtualProductionObjectVersion from "./custom-versions-enums/FVirtualProductionObjectVersion";
import * as FUE5MainStreamObjectVersion from "./custom-versions-enums/FUE5MainStreamObjectVersion";
import * as FUE5ReleaseStreamObjectVersion from "./custom-versions-enums/FUE5ReleaseStreamObjectVersion";
import * as FUE5PrivateFrostyStreamObjectVersion from "./custom-versions-enums/FUE5PrivateFrostyStreamObjectVersion";
import * as FUE5CookerObjectVersion from "./custom-versions-enums/FUE5CookerObjectVersion";
import * as FMediaFrameworkObjectVersion from "./custom-versions-enums/FMediaFrameworkObjectVersion";
import * as FUE5LWCRenderingStreamObjectVersion from "./custom-versions-enums/FUE5LWCRenderingStreamObjectVersion";
import * as FAssetRegistryVersion from "./custom-versions-enums/FAssetRegistryVersion";
import * as FSkeletalMeshCustomVersion from "./custom-versions-enums/FSkeletalMeshCustomVersion";
import * as FRecomputeTangentCustomVersion from "./custom-versions-enums/FRecomputeTangentCustomVersion";
import * as FOverlappingVerticesCustomVersion from "./custom-versions-enums/FOverlappingVerticesCustomVersion";
import * as FSoundSubmixCustomVersion from "./custom-versions-enums/FSoundSubmixCustomVersion";
import * as FWorldSettingCustomVersion from "./custom-versions-enums/FWorldSettingCustomVersion";
import * as FShapeComponentCustomVersion from "./custom-versions-enums/FShapeComponentCustomVersion";
import * as FParticleSystemCustomVersion from "./custom-versions-enums/FParticleSystemCustomVersion";
import * as EVisualLoggerVersion from "./custom-versions-enums/EVisualLoggerVersion";
import * as FFoliageCustomVersion from "./custom-versions-enums/FFoliageCustomVersion";
import * as FProceduralFoliageCustomVersion from "./custom-versions-enums/FProceduralFoliageCustomVersion";
import * as FInterchangeCustomVersion from "./custom-versions-enums/FInterchangeCustomVersion";
import * as FLandscapeCustomVersion from "./custom-versions-enums/FLandscapeCustomVersion";
import * as FLiveLinkCustomVersion from "./custom-versions-enums/FLiveLinkCustomVersion";
import * as FMovieSceneEvaluationCustomVersion from "./custom-versions-enums/FMovieSceneEvaluationCustomVersion";
import * as FPoseDriverCustomVersion from "./custom-versions-enums/FPoseDriverCustomVersion";
import * as FTempCustomVersion from "./custom-versions-enums/FTempCustomVersion";

export const GRegisterAnimationCustomVersion = new CustomVersionGuid<FAnimationCustomVersion.FAnimationCustomVersion>({
  friendlyName: "AnimGraphVer",
  guid: FGuid.fromComponents(0x2eb5fdbd, 0x01ac4d10, 0x8136f38f, 0x3393a5da),
  details: FAnimationCustomVersion.FAnimationCustomVersionDetails,
});

export const GRegisterClothingAssetCustomVersion =
  new CustomVersionGuid<FClothingAssetCustomVersion.FClothingAssetCustomVersion>({
    friendlyName: "ClothingAssetVer",
    guid: FGuid.fromComponents(0xfb680af2, 0x59ef4ba3, 0xbaa819b5, 0x73c8443d),
    details: FClothingAssetCustomVersion.FClothingAssetCustomVersionDetails,
  });

export const GRegisterClothConfigNvCustomVersion =
  new CustomVersionGuid<FClothConfigNvCustomVersion.FClothConfigNvCustomVersion>({
    friendlyName: "ClothConfigNvVer",
    guid: FGuid.fromComponents(0x9950b70e, 0xb41a4e17, 0xbbccfa0d, 0x57817fd6),
    details: FClothConfigNvCustomVersion.FClothConfigNvCustomVersionDetails,
  });

export const GRegisterReleaseObjectVersion = new CustomVersionGuid<FReleaseObjectVersion.FReleaseObjectVersion>({
  friendlyName: "Release",
  guid: FGuid.fromComponents(0x9c54d522, 0xa8264fbe, 0x94210746, 0x61b482d0),
  details: FReleaseObjectVersion.FReleaseObjectVersionDetails,
});

export const GRegisterBlueprintsObjectVersion =
  new CustomVersionGuid<FBlueprintsObjectVersion.FBlueprintsObjectVersion>({
    friendlyName: "Dev-Blueprints",
    guid: FGuid.fromComponents(0xb0d832e4, 0x1f894f0d, 0xaccf7eb7, 0x36fd4aa2),
    details: FBlueprintsObjectVersion.FBlueprintsObjectVersionDetails,
  });

export const GRegisterBuildObjectVersion = new CustomVersionGuid<FBuildObjectVersion.FBuildObjectVersion>({
  friendlyName: "Dev-Build",
  guid: FGuid.fromComponents(0xe1c64328, 0xa22c4d53, 0xa36c8e86, 0x6417bd8c),
  details: FBuildObjectVersion.FBuildObjectVersionDetails,
});

export const GRegisterCoreObjectVersion = new CustomVersionGuid<FCoreObjectVersion.FCoreObjectVersion>({
  friendlyName: "Dev-Core",
  guid: FGuid.fromComponents(0x375ec13c, 0x06e448fb, 0xb50084f0, 0x262a717e),
  details: FCoreObjectVersion.FCoreObjectVersionDetails,
});

export const GRegisterEditorObjectVersion = new CustomVersionGuid<FEditorObjectVersion.FEditorObjectVersion>({
  friendlyName: "Dev-Editor",
  guid: FGuid.fromComponents(0xe4b068ed, 0xf49442e9, 0xa231da0b, 0x2e46bb41),
  details: FEditorObjectVersion.FEditorObjectVersionDetails,
});

export const GRegisterFrameworkObjectVersion = new CustomVersionGuid<FFrameworkObjectVersion.FFrameworkObjectVersion>({
  friendlyName: "Dev-Framework",
  guid: FGuid.fromComponents(0xcffc743f, 0x43b04480, 0x939114df, 0x171d2073),
  details: FFrameworkObjectVersion.FFrameworkObjectVersionDetails,
});

export const GRegisterMobileObjectVersion = new CustomVersionGuid<FMobileObjectVersion.FMobileObjectVersion>({
  friendlyName: "Dev-Mobile",
  guid: FGuid.fromComponents(0xb02b49b5, 0xbb2044e9, 0xa30432b7, 0x52e40360),
  details: FMobileObjectVersion.FMobileObjectVersionDetails,
});

export const GRegisterNetworkingObjectVersion =
  new CustomVersionGuid<FNetworkingObjectVersion.FNetworkingObjectVersion>({
    friendlyName: "Dev-Networking",
    guid: FGuid.fromComponents(0xa4e4105c, 0x59a149b5, 0xa7c540c4, 0x547edfee),
    details: FNetworkingObjectVersion.FNetworkingObjectVersionDetails,
  });

export const GRegisterOnlineObjectVersion = new CustomVersionGuid<FOnlineObjectVersion.FOnlineObjectVersion>({
  friendlyName: "Dev-Online",
  guid: FGuid.fromComponents(0x39c831c9, 0x5ae647dc, 0x9a449c17, 0x3e1c8e7c),
  details: FOnlineObjectVersion.FOnlineObjectVersionDetails,
});

export const GRegisterPhysicsObjectVersion = new CustomVersionGuid<FPhysicsObjectVersion.FPhysicsObjectVersion>({
  friendlyName: "Dev-Physics",
  guid: FGuid.fromComponents(0x78f01b33, 0xebea4f98, 0xb9b484ea, 0xccb95aa2),
  details: FPhysicsObjectVersion.FPhysicsObjectVersionDetails,
});

export const GRegisterPlatformObjectVersion = new CustomVersionGuid<FPlatformObjectVersion.FPlatformObjectVersion>({
  friendlyName: "Dev-Platform",
  guid: FGuid.fromComponents(0x6631380f, 0x2d4d43e0, 0x8009cf27, 0x6956a95a),
  details: FPlatformObjectVersion.FPlatformObjectVersionDetails,
});

export const GRegisterRenderingObjectVersion = new CustomVersionGuid<FRenderingObjectVersion.FRenderingObjectVersion>({
  friendlyName: "Dev-Rendering",
  guid: FGuid.fromComponents(0x12f88b9f, 0x88754afc, 0xa67cd90c, 0x383abd29),
  details: FRenderingObjectVersion.FRenderingObjectVersionDetails,
});

export const GRegisterSequencerObjectVersion = new CustomVersionGuid<FSequencerObjectVersion.FSequencerObjectVersion>({
  friendlyName: "Dev-Sequencer",
  guid: FGuid.fromComponents(0x7b5ae74c, 0xd2704c10, 0xa9585798, 0x0b212a5a),
  details: FSequencerObjectVersion.FSequencerObjectVersionDetails,
});

export const GRegisterVRObjectVersion = new CustomVersionGuid<FVRObjectVersion.FVRObjectVersion>({
  friendlyName: "Dev-VR",
  guid: FGuid.fromComponents(0xd7296918, 0x1dd64bdd, 0x9de264a8, 0x3cc13884),
  details: FVRObjectVersion.FVRObjectVersionDetails,
});

export const GRegisterLoadTimesObjectVersion = new CustomVersionGuid<FLoadTimesObjectVersion.FLoadTimesObjectVersion>({
  friendlyName: "Dev-LoadTimes",
  guid: FGuid.fromComponents(0xc2a15278, 0xbfe74afe, 0x6c1790ff, 0x531df755),
  details: FLoadTimesObjectVersion.FLoadTimesObjectVersionDetails,
});

export const GRegisterGeometryObjectVersion = new CustomVersionGuid<FGeometryObjectVersion.FGeometryObjectVersion>({
  friendlyName: "Private-Geometry",
  guid: FGuid.fromComponents(0x6eaca3d4, 0x40ec4cc1, 0xb7868bed, 0x9428fc5),
  details: FGeometryObjectVersion.FGeometryObjectVersionDetails,
});

export const GRegisterAnimPhysObjectVersion = new CustomVersionGuid<FAnimPhysObjectVersion.FAnimPhysObjectVersion>({
  friendlyName: "Dev-AnimPhys",
  guid: FGuid.fromComponents(0x29e575dd, 0xe0a34627, 0x9d10d276, 0x232cdcea),
  details: FAnimPhysObjectVersion.FAnimPhysObjectVersionDetails,
});

export const GRegisterAnimObjectVersion = new CustomVersionGuid<FAnimObjectVersion.FAnimObjectVersion>({
  friendlyName: "Dev-Anim",
  guid: FGuid.fromComponents(0xaf43a65d, 0x7fd34947, 0x98733e8e, 0xd9c1bb05),
  details: FAnimObjectVersion.FAnimObjectVersionDetails,
});

export const GRegisterReflectionCaptureObjectVersion =
  new CustomVersionGuid<FReflectionCaptureObjectVersion.FReflectionCaptureObjectVersion>({
    friendlyName: "Dev-ReflectionCapture",
    guid: FGuid.fromComponents(0x6b266cec, 0x1ec74b8f, 0xa30be4d9, 0x0942fc07),
    details: FReflectionCaptureObjectVersion.FReflectionCaptureObjectVersionDetails,
  });

export const GRegisterAutomationObjectVersion =
  new CustomVersionGuid<FAutomationObjectVersion.FAutomationObjectVersion>({
    friendlyName: "Dev-Automation",
    guid: FGuid.fromComponents(0x0df73d61, 0xa23f47ea, 0xb72789e9, 0x0c41499a),
    details: FAutomationObjectVersion.FAutomationObjectVersionDetails,
  });

export const GRegisterFortniteMainBranchObjectVersion =
  new CustomVersionGuid<FFortniteMainBranchObjectVersion.FFortniteMainBranchObjectVersion>({
    friendlyName: "FortniteMain",
    guid: FGuid.fromComponents(0x601d1886, 0xac644f84, 0xaa16d3de, 0x0deac7d6),
    details: FFortniteMainBranchObjectVersion.FFortniteMainBranchObjectVersionDetails,
  });

export const GRegisterFortniteValkyrieBranchObjectVersion =
  new CustomVersionGuid<FFortniteValkyrieBranchObjectVersion.FFortniteValkyrieBranchObjectVersion>({
    friendlyName: "FortniteValkyrie",
    guid: FGuid.fromComponents(0x8dbc2c5b, 0x54a743e0, 0xa768fcbb, 0x7da29060),
    details: FFortniteValkyrieBranchObjectVersion.FFortniteValkyrieBranchObjectVersionDetails,
  });

export const GRegisterFortniteSeasonBranchObjectVersion =
  new CustomVersionGuid<FFortniteSeasonBranchObjectVersion.FFortniteSeasonBranchObjectVersion>({
    friendlyName: "FortniteSeason",
    guid: FGuid.fromComponents(0x5b4c06b7, 0x24634af8, 0x805bbf70, 0xcdf5d0dd),
    details: FFortniteSeasonBranchObjectVersion.FFortniteSeasonBranchObjectVersionDetails,
  });

export const GRegisterFortniteReleaseBranchCustomObjectVersion =
  new CustomVersionGuid<FFortniteReleaseBranchCustomObjectVersion.FFortniteReleaseBranchCustomObjectVersion>({
    friendlyName: "FortniteRelease",
    guid: FGuid.fromComponents(0xe7086368, 0x6b234c58, 0x84391b70, 0x16265e91),
    details: FFortniteReleaseBranchCustomObjectVersion.FFortniteReleaseBranchCustomObjectVersionDetails,
  });

export const GRegisterEnterpriseObjectVersion =
  new CustomVersionGuid<FEnterpriseObjectVersion.FEnterpriseObjectVersion>({
    friendlyName: "Dev-Enterprise",
    guid: FGuid.fromComponents(0x9dffbcd6, 0x494f0158, 0xe2211282, 0x3c92a888),
    details: FEnterpriseObjectVersion.FEnterpriseObjectVersionDetails,
  });

export const GRegisterNiagaraObjectVersion = new CustomVersionGuid<FNiagaraObjectVersion.FNiagaraObjectVersion>({
  friendlyName: "Dev-Niagara",
  guid: FGuid.fromComponents(0xf2aed0ac, 0x9afe416f, 0x8664aa7f, 0xfa26d6fc),
  details: FNiagaraObjectVersion.FNiagaraObjectVersionDetails,
});

export const GRegisterDestructionObjectVersion =
  new CustomVersionGuid<FDestructionObjectVersion.FDestructionObjectVersion>({
    friendlyName: "Dev-Destruction",
    guid: FGuid.fromComponents(0x174f1f0b, 0xb4c645a5, 0xb13f2ee8, 0xd0fb917d),
    details: FDestructionObjectVersion.FDestructionObjectVersionDetails,
  });

export const GRegisterExternalPhysicsCustomVersion =
  new CustomVersionGuid<FExternalPhysicsCustomObjectVersion.FExternalPhysicsCustomObjectVersion>({
    friendlyName: "Dev-Physics-Ext",
    guid: FGuid.fromComponents(0x35f94a83, 0xe258406c, 0xa31809f5, 0x9610247c),
    details: FExternalPhysicsCustomObjectVersion.FExternalPhysicsCustomObjectVersionDetails,
  });

export const GRegisterExternalPhysicsMaterialCustomVersion =
  new CustomVersionGuid<FExternalPhysicsMaterialCustomObjectVersion.FExternalPhysicsMaterialCustomObjectVersion>({
    friendlyName: "Dev-PhysicsMaterial-Chaos",
    guid: FGuid.fromComponents(0xb68fc16e, 0x8b1b42e2, 0xb453215c, 0x058844fe),
    details: FExternalPhysicsMaterialCustomObjectVersion.FExternalPhysicsMaterialCustomObjectVersionDetails,
  });

export const GRegisterCineCameraObjectVersion =
  new CustomVersionGuid<FCineCameraObjectVersion.FCineCameraObjectVersion>({
    friendlyName: "Dev-CineCamera",
    guid: FGuid.fromComponents(0xb2e18506, 0x4273cfc2, 0xa54ef4bb, 0x758bba07),
    details: FCineCameraObjectVersion.FCineCameraObjectVersionDetails,
  });

export const GRegisterVirtualProductionObjectVersion =
  new CustomVersionGuid<FVirtualProductionObjectVersion.FVirtualProductionObjectVersion>({
    friendlyName: "Dev-VirtualProduction",
    guid: FGuid.fromComponents(0x64f58936, 0xfd1b42ba, 0xba967289, 0xd5d0fa4e),
    details: FVirtualProductionObjectVersion.FVirtualProductionObjectVersionDetails,
  });

export const GRegisterUE5MainStreamObjectVersion =
  new CustomVersionGuid<FUE5MainStreamObjectVersion.FUE5MainStreamObjectVersion>({
    friendlyName: "UE5-Main",
    guid: FGuid.fromComponents(0x697dd581, 0xe64f41ab, 0xaa4a51ec, 0xbeb7b628),
    details: FUE5MainStreamObjectVersion.FUE5MainStreamObjectVersionDetails,
  });

export const GRegisterUE5ReleaseStreamObjectVersion =
  new CustomVersionGuid<FUE5ReleaseStreamObjectVersion.FUE5ReleaseStreamObjectVersion>({
    friendlyName: "UE5-Release",
    guid: FGuid.fromComponents(0xd89b5e42, 0x24bd4d46, 0x8412aca8, 0xdf641779),
    details: FUE5ReleaseStreamObjectVersion.FUE5ReleaseStreamObjectVersionDetails,
  });

export const GRegisterUE5PrivateFrostyStreamObjectVersion =
  new CustomVersionGuid<FUE5PrivateFrostyStreamObjectVersion.FUE5PrivateFrostyStreamObjectVersion>({
    friendlyName: "UE5-PrivateFrosty",
    guid: FGuid.fromComponents(0x59da5d52, 0x12324948, 0xb8785978, 0x70b8e98b),
    details: FUE5PrivateFrostyStreamObjectVersion.FUE5PrivateFrostyStreamObjectVersionDetails,
  });

export const GRegisterCookerObjectVersion = new CustomVersionGuid<FUE5CookerObjectVersion.FUE5CookerObjectVersion>({
  friendlyName: "UE5-Dev-Cooker",
  guid: FGuid.fromComponents(0x26075a32, 0x730f4708, 0x88e98c32, 0xf1599d05),
  details: FUE5CookerObjectVersion.FUE5CookerObjectVersionDetails,
});

export const GRegisterMediaFrameworkObjectVersion =
  new CustomVersionGuid<FMediaFrameworkObjectVersion.FMediaFrameworkObjectVersion>({
    friendlyName: "Dev-MediaFramework",
    guid: FGuid.fromComponents(0x6f0ed827, 0xa6094895, 0x9c91998d, 0x90180ea4),
    details: FMediaFrameworkObjectVersion.FMediaFrameworkObjectVersionDetails,
  });

export const GRegisterLWCRenderingStreamObjectVersion =
  new CustomVersionGuid<FUE5LWCRenderingStreamObjectVersion.FUE5LWCRenderingStreamObjectVersion>({
    friendlyName: "UE5-Dev-LWCRendering",
    guid: FGuid.fromComponents(0x30d58be3, 0x95ea4282, 0xa6e3b159, 0xd8ebb06a),
    details: FUE5LWCRenderingStreamObjectVersion.FUE5LWCRenderingStreamObjectVersionDetails,
  });

export const GRegisterAssetRegistryVersion = new CustomVersionGuid<FAssetRegistryVersion.FAssetRegistryVersion>({
  friendlyName: "AssetRegistry",
  guid: FGuid.fromComponents(0x717f9ee7, 0xe9b0493a, 0x88b39132, 0x1b388107),
  details: FAssetRegistryVersion.FAssetRegistryVersionDetails,
});

export const GRegisterSkeletalMeshCustomVersion =
  new CustomVersionGuid<FSkeletalMeshCustomVersion.FSkeletalMeshCustomVersion>({
    friendlyName: "SkeletalMeshVer",
    guid: FGuid.fromComponents(0xd78a4a00, 0xe8584697, 0xbaa819b5, 0x487d46b4),
    details: FSkeletalMeshCustomVersion.FSkeletalMeshCustomVersionDetails,
  });

export const GRegisterRecomputeTangentCustomVersion =
  new CustomVersionGuid<FRecomputeTangentCustomVersion.FRecomputeTangentCustomVersion>({
    friendlyName: "RecomputeTangentCustomVer",
    guid: FGuid.fromComponents(0x5579f886, 0x933a4c1f, 0x83ba087b, 0x6361b92f),
    details: FRecomputeTangentCustomVersion.FRecomputeTangentCustomVersionDetails,
  });

export const GRegisterOverlappingVerticesCustomVersion =
  new CustomVersionGuid<FOverlappingVerticesCustomVersion.FOverlappingVerticesCustomVersion>({
    friendlyName: "OverlappingVerticeDetectionVer",
    guid: FGuid.fromComponents(0x612fbe52, 0xda53400b, 0x910d4f91, 0x9fb1857c),
    details: FOverlappingVerticesCustomVersion.FOverlappingVerticesCustomVersionDetails,
  });

export const GSoundSubmixCustomVersion = new CustomVersionGuid<FSoundSubmixCustomVersion.FSoundSubmixCustomVersion>({
  friendlyName: "SoundSubmixVer",
  guid: FGuid.fromComponents(0x79d25301, 0x47af41f8, 0xadcf10e7, 0x97415c16),
  details: FSoundSubmixCustomVersion.FSoundSubmixCustomVersionDetails,
});

export const GRegisterWorldSettingCustomVersion =
  new CustomVersionGuid<FWorldSettingCustomVersion.FWorldSettingCustomVersion>({
    friendlyName: "WorldSettingVer",
    guid: FGuid.fromComponents(0x1ed048f4, 0x2f2e4c68, 0x89d053a4, 0xf18f102d),
    details: FWorldSettingCustomVersion.FWorldSettingCustomVersionDetails,
  });

export const GRegisterShapeComponentCustomVersion =
  new CustomVersionGuid<FShapeComponentCustomVersion.FShapeComponentCustomVersion>({
    friendlyName: "ShapeComponentVer",
    guid: FGuid.fromComponents(0xb6e31b1c, 0xd29f11ec, 0x857e9f85, 0x6f9970e2),
    details: FShapeComponentCustomVersion.FShapeComponentCustomVersionDetails,
  });

export const GRegisterParticleSystemCustomVersion =
  new CustomVersionGuid<FParticleSystemCustomVersion.FParticleSystemCustomVersion>({
    friendlyName: "ParticleSystemVer",
    guid: FGuid.fromComponents(0x4a56eb40, 0x10f511dc, 0x92d3347e, 0xb2c96ae7),
    details: FParticleSystemCustomVersion.FParticleSystemCustomVersionDetails,
  });

export const GVisualLoggerVersion = new CustomVersionGuid<EVisualLoggerVersion.EVisualLoggerVersion>({
  friendlyName: "VisualLogger",
  guid: FGuid.fromComponents(0xa4237a36, 0xcaea41c9, 0x8fa218f8, 0x58681bf3),
  details: EVisualLoggerVersion.EVisualLoggerVersionDetails,
});

export const GRegisterFoliageCustomVersion = new CustomVersionGuid<FFoliageCustomVersion.FFoliageCustomVersion>({
  friendlyName: "FoliageVer",
  guid: FGuid.fromComponents(0x430c4d19, 0x71544970, 0x87699b69, 0xdf90b0e5),
  details: FFoliageCustomVersion.FFoliageCustomVersionDetails,
});

export const GRegisterProceduralFoliageCustomVersion =
  new CustomVersionGuid<FProceduralFoliageCustomVersion.FProceduralFoliageCustomVersion>({
    friendlyName: "ProceduralFoliageVer",
    guid: FGuid.fromComponents(0xaafe32bd, 0x53954c14, 0xb66a5e25, 0x1032d1dd),
    details: FProceduralFoliageCustomVersion.FProceduralFoliageCustomVersionDetails,
  });

export const GRegisterInterchangeCustomVersion =
  new CustomVersionGuid<FInterchangeCustomVersion.FInterchangeCustomVersion>({
    friendlyName: "InterchangeAssetImportDataVer",
    guid: FGuid.fromString("{92738C43-2988-4D9C-9A3D-9BBE6EFF9FC0}"),
    details: FInterchangeCustomVersion.FInterchangeCustomVersionDetails,
  });

export const GRegisterLandscapeCustomVersion = new CustomVersionGuid<FLandscapeCustomVersion.FLandscapeCustomVersion>({
  friendlyName: "Landscape",
  guid: FGuid.fromComponents(0x23afe18e, 0x4ce14e58, 0x8d61c252, 0xb953beb7),
  details: FLandscapeCustomVersion.FLandscapeCustomVersionDetails,
});

export const GRegisterLiveLinkInterfaceCustomVersion =
  new CustomVersionGuid<FLiveLinkCustomVersion.FLiveLinkCustomVersion>({
    friendlyName: "LiveLinkVer",
    guid: FGuid.fromComponents(0xab965196, 0x45d808fc, 0xb7d7228d, 0x78ad569e),
    details: FLiveLinkCustomVersion.FLiveLinkCustomVersionDetails,
  });

export const GRegisterMovieSceneEvaluationCustomVersion =
  new CustomVersionGuid<FMovieSceneEvaluationCustomVersion.FMovieSceneEvaluationCustomVersion>({
    friendlyName: "MovieSceneEvaluation",
    guid: FGuid.fromComponents(0xa462b7ea, 0xf4994e3a, 0x99c1ec1f, 0x8224e1b2),
    details: FMovieSceneEvaluationCustomVersion.FMovieSceneEvaluationCustomVersionDetails,
  });

export const GRegisterPoseDriverCustomVersion =
  new CustomVersionGuid<FPoseDriverCustomVersion.FPoseDriverCustomVersion>({
    friendlyName: "PoseDriverVer",
    guid: FGuid.fromComponents(0xafe08691, 0x3a0d4952, 0xb673673b, 0x7cf22d1e),
    details: FPoseDriverCustomVersion.FPoseDriverCustomVersionDetails,
  });

export const GRegisterLiveLinkMovieSectionCustomVersion = new CustomVersionGuid<FTempCustomVersion.FTempCustomVersion>({
  friendlyName: "LiveLinkCustomVersion",
  guid: FGuid.fromComponents(0xcb8ab0cd, 0xe78c4bde, 0xa8621393, 0x14e9ef62),
  details: FTempCustomVersion.FTempCustomVersionDetails,
});
