// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { FFortniteMainBranchObjectVersionGuid } from "./custom-versions-enums/FFortniteMainBranchObjectVersion";

export const allCustomVersions = [FFortniteMainBranchObjectVersionGuid];
