// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { FAnimObjectVersionGuid } from "./custom-versions-enums/FAnimObjectVersion";
import { FAnimPhysObjectVersionGuid } from "./custom-versions-enums/FAnimPhysObjectVersion";
import { FEditorObjectVersionGuid } from "./custom-versions-enums/FEditorObjectVersion";
import { FEnterpriseObjectVersionGuid } from "./custom-versions-enums/FEnterpriseObjectVersion";
import { FFortniteMainBranchObjectVersionGuid } from "./custom-versions-enums/FFortniteMainBranchObjectVersion";
import { FFrameworkObjectVersionGuid } from "./custom-versions-enums/FFrameworkObjectVersion";
import { FUE5MainStreamObjectVersionGuid } from "./custom-versions-enums/FUE5MainStreamObjectVersion";
import type { CustomVersionGuid } from "./CustomVersionGuid";

export const allCustomVersions: ReadonlyArray<CustomVersionGuid> = [
  FAnimObjectVersionGuid,
  FAnimPhysObjectVersionGuid,
  FEditorObjectVersionGuid,
  FEnterpriseObjectVersionGuid,
  FFortniteMainBranchObjectVersionGuid,
  FFrameworkObjectVersionGuid,
  FUE5MainStreamObjectVersionGuid,
];
