// This file is auto-generated, do not edit directly.

import type { EStaticMeshPaintSupport } from "./EStaticMeshPaintSupport";
import type { FAssetEditorOrbitCameraPosition } from "./AssetEditorOrbitCameraPosition";
import type { FBoxSphereBounds } from "../CoreUObject/BoxSphereBounds";
import type { FMaterialRemapIndex } from "./MaterialRemapIndex";
import type { FMeshNaniteSettings } from "./MeshNaniteSettings";
import type { FMeshRayTracingProxySettings } from "./MeshRayTracingProxySettings";
import type { FMeshSectionInfoMap } from "./MeshSectionInfoMap";
import type { FPerPlatformInt } from "../CoreUObject/PerPlatformInt";
import type { FPerQualityLevelInt } from "./PerQualityLevelInt";
import type { FStaticMaterial } from "./StaticMaterial";
import type { FStaticMeshSourceModel } from "./StaticMeshSourceModel";
import type { FVector } from "../CoreUObject/Vector";
import type { UAssetImportData } from "./AssetImportData";
import type { UAssetUserData } from "./AssetUserData";
import type { UMaterialInterface } from "./MaterialInterface";
import type { UObject } from "../CoreUObject/Object";
import type { UStaticMeshSocket } from "./StaticMeshSocket";
import type { UStreamableRenderAsset } from "./StreamableRenderAsset";
import type { UThumbnailInfo } from "./ThumbnailInfo";

export interface UStaticMesh extends UStreamableRenderAsset {
  SourceModels: Array<FStaticMeshSourceModel>;
  HiResSourceModel: FStaticMeshSourceModel;
  SectionInfoMap: FMeshSectionInfoMap;
  OriginalSectionInfoMap: FMeshSectionInfoMap;
  LODGroup: string;
  NumStreamedLODs: FPerPlatformInt;
  ImportVersion: number;
  MaterialRemapIndexPerImportVersion: Array<FMaterialRemapIndex>;
  LightmapUVVersion: number;
  bAutoComputeLODScreenSize: boolean;
  Materials: Array<UMaterialInterface>;
  NaniteSettings: FMeshNaniteSettings;
  MinQualityLevelLOD: FPerQualityLevelInt;
  MinLOD: FPerPlatformInt;
  ElementToIgnoreForTexFactor: number;
  StaticMaterials: Array<FStaticMaterial>;
  LightmapUVDensity: number;
  LightMapResolution: number;
  LightMapCoordinateIndex: number;
  StaticMeshPaintSupport: EStaticMeshPaintSupport;
  MeshPaintTextureCoordinateIndex: number;
  MeshPaintTextureResolution: number;
  DistanceFieldSelfShadowBias: number;
  LODForCollision: number;
  bGenerateMeshDistanceField: boolean;
  bStripComplexCollisionForConsole: boolean;
  bHasNavigationData: boolean;
  bSupportUniformlyDistributedSampling: boolean;
  bSupportPhysicalMaterialMasks: boolean;
  bUseLegacyTangentScaling: boolean;
  RayTracingProxySettings: FMeshRayTracingProxySettings;
  bSupportRayTracing: boolean;
  bDoFastBuild: boolean;
  bIsBuiltAtRuntime: boolean;
  bAllowCPUAccess: boolean;
  bSupportGpuUniformlyDistributedSampling: boolean;
  AssetImportData: UAssetImportData;
  SourceFilePath: string;
  SourceFileTimestamp: string;
  ThumbnailInfo: UThumbnailInfo;
  EditorCameraPosition: FAssetEditorOrbitCameraPosition;
  bCustomizedCollision: boolean;
  Sockets: Array<UStaticMeshSocket>;
  PositiveBoundsExtension: FVector;
  NegativeBoundsExtension: FVector;
  ExtendedBounds: FBoxSphereBounds;
  AssetUserData: Array<UAssetUserData>;
  EditableMesh: UObject;
  ComplexCollisionMesh: UStaticMesh;
}
