// This file is auto-generated, do not edit directly.

import type { FAssetEditorOrbitCameraPosition } from "./AssetEditorOrbitCameraPosition";
import type { FBoxSphereBounds } from "../CoreUObject/BoxSphereBounds";
import type { FMaterialRemapIndex } from "./MaterialRemapIndex";
import type { FMeshNaniteSettings } from "./MeshNaniteSettings";
import type { FMeshRayTracingProxySettings } from "./MeshRayTracingProxySettings";
import type { FMeshSectionInfoMap } from "./MeshSectionInfoMap";
import type { FPerPlatformInt } from "../CoreUObject/PerPlatformInt";
import type { FPerQualityLevelInt } from "./PerQualityLevelInt";
import type { FStaticMaterial } from "./StaticMaterial";
import type { FStaticMeshSourceModel } from "./StaticMeshSourceModel";
import type { FVector } from "../CoreUObject/Vector";
import type { UStreamableRenderAsset } from "./StreamableRenderAsset";

export interface UStaticMesh extends UStreamableRenderAsset {
  SourceModels: Array<FStaticMeshSourceModel>;
  HiResSourceModel: FStaticMeshSourceModel;
  SectionInfoMap: FMeshSectionInfoMap;
  OriginalSectionInfoMap: FMeshSectionInfoMap;
  LODGroup: string;
  NumStreamedLODs: FPerPlatformInt;
  ImportVersion: number;
  MaterialRemapIndexPerImportVersion: Array<FMaterialRemapIndex>;
  LightmapUVVersion: number;
  bAutoComputeLODScreenSize: boolean;
  Materials: Array<Object>;
  NaniteSettings: FMeshNaniteSettings;
  MinQualityLevelLOD: FPerQualityLevelInt;
  MinLOD: FPerPlatformInt;
  ElementToIgnoreForTexFactor: number;
  StaticMaterials: Array<FStaticMaterial>;
  AssemblyReferenceCache: Array<Object>;
  LightmapUVDensity: number;
  LightMapResolution: number;
  LightMapCoordinateIndex: number;
  StaticMeshPaintSupport: Invalid__EnumProperty;
  MeshPaintTextureCoordinateIndex: number;
  MeshPaintTextureResolution: number;
  DistanceFieldSelfShadowBias: number;
  BodySetup: Object;
  LODForCollision: number;
  bGenerateMeshDistanceField: boolean;
  bStripComplexCollisionForConsole: boolean;
  bHasNavigationData: boolean;
  bSupportUniformlyDistributedSampling: boolean;
  bSupportPhysicalMaterialMasks: boolean;
  bUseLegacyTangentScaling: boolean;
  RayTracingProxySettings: FMeshRayTracingProxySettings;
  bSupportRayTracing: boolean;
  bDoFastBuild: boolean;
  bIsBuiltAtRuntime: boolean;
  bAllowCPUAccess: boolean;
  bSupportGpuUniformlyDistributedSampling: boolean;
  AssetImportData: Object;
  SourceFilePath: string;
  SourceFileTimestamp: string;
  ThumbnailInfo: Object;
  EditorCameraPosition: FAssetEditorOrbitCameraPosition;
  bCustomizedCollision: boolean;
  Sockets: Array<Object>;
  PositiveBoundsExtension: FVector;
  NegativeBoundsExtension: FVector;
  ExtendedBounds: FBoxSphereBounds;
  AssetUserData: Array<Object>;
  EditableMesh: Object;
  ComplexCollisionMesh: Object;
  NavCollision: Object;
}
