// This file is auto-generated, do not edit directly.

import { EStaticMeshPaintSupport } from "./EStaticMeshPaintSupport";
import { FAssetEditorOrbitCameraPosition } from "./AssetEditorOrbitCameraPosition";
import { FBoxSphereBounds } from "../CoreUObject/BoxSphereBounds";
import type { FMaterialRemapIndex } from "./MaterialRemapIndex";
import { FMeshNaniteSettings } from "./MeshNaniteSettings";
import { FMeshRayTracingProxySettings } from "./MeshRayTracingProxySettings";
import { FMeshSectionInfoMap } from "./MeshSectionInfoMap";
import { FPerPlatformInt } from "../CoreUObject/PerPlatformInt";
import { FPerQualityLevelInt } from "./PerQualityLevelInt";
import type { FStaticMaterial } from "./StaticMaterial";
import { FStaticMeshSourceModel } from "./StaticMeshSourceModel";
import { FVector } from "../CoreUObject/Vector";
import type { UAssetImportData } from "./AssetImportData";
import type { UAssetUserData } from "./AssetUserData";
import type { UMaterialInterface } from "./MaterialInterface";
import type { UObject } from "../CoreUObject/Object";
import type { UStaticMeshSocket } from "./StaticMeshSocket";
import { UStreamableRenderAsset } from "./StreamableRenderAsset";
import type { UThumbnailInfo } from "./ThumbnailInfo";

export class UStaticMesh extends UStreamableRenderAsset {
  SourceModels: Array<FStaticMeshSourceModel> = [];
  HiResSourceModel: FStaticMeshSourceModel = new FStaticMeshSourceModel();
  SectionInfoMap: FMeshSectionInfoMap = new FMeshSectionInfoMap();
  OriginalSectionInfoMap: FMeshSectionInfoMap = new FMeshSectionInfoMap();
  LODGroup: string = "";
  NumStreamedLODs: FPerPlatformInt = new FPerPlatformInt();
  ImportVersion: number = 0;
  MaterialRemapIndexPerImportVersion: Array<FMaterialRemapIndex> = [];
  LightmapUVVersion: number = 0;
  bAutoComputeLODScreenSize: boolean = false;
  Materials: Array<UMaterialInterface | null> = [];
  NaniteSettings: FMeshNaniteSettings = new FMeshNaniteSettings();
  MinQualityLevelLOD: FPerQualityLevelInt = new FPerQualityLevelInt();
  MinLOD: FPerPlatformInt = new FPerPlatformInt();
  ElementToIgnoreForTexFactor: number = 0;
  StaticMaterials: Array<FStaticMaterial> = [];
  LightmapUVDensity: number = 0;
  LightMapResolution: number = 0;
  LightMapCoordinateIndex: number = 0;
  StaticMeshPaintSupport: EStaticMeshPaintSupport = EStaticMeshPaintSupport.Default;
  MeshPaintTextureCoordinateIndex: number = 0;
  MeshPaintTextureResolution: number = 0;
  DistanceFieldSelfShadowBias: number = 0;
  LODForCollision: number = 0;
  bGenerateMeshDistanceField: boolean = false;
  bStripComplexCollisionForConsole: boolean = false;
  bHasNavigationData: boolean = false;
  bSupportUniformlyDistributedSampling: boolean = false;
  bSupportPhysicalMaterialMasks: boolean = false;
  bUseLegacyTangentScaling: boolean = false;
  RayTracingProxySettings: FMeshRayTracingProxySettings = new FMeshRayTracingProxySettings();
  bSupportRayTracing: boolean = false;
  bDoFastBuild: boolean = false;
  bIsBuiltAtRuntime: boolean = false;
  bAllowCPUAccess: boolean = false;
  bSupportGpuUniformlyDistributedSampling: boolean = false;
  AssetImportData: UAssetImportData | null = null;
  SourceFilePath: string = "";
  SourceFileTimestamp: string = "";
  ThumbnailInfo: UThumbnailInfo | null = null;
  EditorCameraPosition: FAssetEditorOrbitCameraPosition = new FAssetEditorOrbitCameraPosition();
  bCustomizedCollision: boolean = false;
  Sockets: Array<UStaticMeshSocket | null> = [];
  PositiveBoundsExtension: FVector = new FVector();
  NegativeBoundsExtension: FVector = new FVector();
  ExtendedBounds: FBoxSphereBounds = new FBoxSphereBounds();
  AssetUserData: Array<UAssetUserData | null> = [];
  EditableMesh: UObject | null = null;
  ComplexCollisionMesh: UStaticMesh | null = null;
}
