// This file is auto-generated, do not edit directly.

import { ECompositeTextureMode } from "./ECompositeTextureMode";
import { ETextureAvailability } from "./ETextureAvailability";
import { ETextureCompressionQuality } from "./ETextureCompressionQuality";
import { ETextureDownscaleOptions } from "./ETextureDownscaleOptions";
import { ETextureLossyCompressionAmount } from "./ETextureLossyCompressionAmount";
import { ETextureMipLoadOptions } from "./ETextureMipLoadOptions";
import { ETexturePowerOfTwoSetting } from "./ETexturePowerOfTwoSetting";
import { EVTProducerPriority } from "../RenderCore/EVTProducerPriority";
import { FColor } from "../CoreUObject/Color";
import { FGuid } from "../CoreUObject/Guid";
import { FPerPlatformFloat } from "../CoreUObject/PerPlatformFloat";
import type { FTextureFormatSettings } from "./TextureFormatSettings";
import { FTextureSource } from "./TextureSource";
import { FTextureSourceColorSettings } from "./TextureSourceColorSettings";
import { FVector4 } from "../CoreUObject/Vector4";
import { TextureCompressionSettings } from "./TextureCompressionSettings";
import { TextureCookPlatformTilingSettings } from "./TextureCookPlatformTilingSettings";
import { TextureFilter } from "./TextureFilter";
import { TextureGroup } from "./TextureGroup";
import { TextureMipGenSettings } from "./TextureMipGenSettings";
import type { UAssetImportData } from "./AssetImportData";
import type { UAssetUserData } from "./AssetUserData";
import { UStreamableRenderAsset } from "./StreamableRenderAsset";

export class UTexture extends UStreamableRenderAsset {
  Source: FTextureSource = new FTextureSource();
  LightingGuid: FGuid = new FGuid();
  SourceFilePath: string = "";
  AssetImportData: UAssetImportData | null = null;
  AdjustBrightness: number = 0;
  AdjustBrightnessCurve: number = 0;
  AdjustVibrance: number = 0;
  AdjustSaturation: number = 0;
  AdjustRGBCurve: number = 0;
  AdjustHue: number = 0;
  AdjustMinAlpha: number = 0;
  AdjustMaxAlpha: number = 0;
  CompressionNoAlpha: boolean = false;
  CompressionForceAlpha: boolean = false;
  CompressionNone: boolean = false;
  LossyCompressionAmount: ETextureLossyCompressionAmount = ETextureLossyCompressionAmount.TLCA_Default;
  OodleTextureSdkVersion: string = "";
  MaxTextureSize: number = 0;
  CompressionQuality: ETextureCompressionQuality = ETextureCompressionQuality.TCQ_Default;
  CompressionCacheId: FGuid = new FGuid();
  bDitherMipMapAlpha: boolean = false;
  bDoScaleMipsForAlphaCoverage: boolean = false;
  AlphaCoverageThresholds: FVector4 = new FVector4();
  bUseNewMipFilter: boolean = false;
  bPreserveBorder: boolean = false;
  bFlipGreenChannel: boolean = false;
  PowerOfTwoMode: ETexturePowerOfTwoSetting = ETexturePowerOfTwoSetting.None;
  PaddingColor: FColor = new FColor();
  bPadWithBorderColor: boolean = false;
  ResizeDuringBuildX: number = 0;
  ResizeDuringBuildY: number = 0;
  bChromaKeyTexture: boolean = false;
  ChromaKeyThreshold: number = 0;
  ChromaKeyColor: FColor = new FColor();
  MipGenSettings: TextureMipGenSettings = TextureMipGenSettings.TMGS_FromTextureGroup;
  CompositeTexture: UTexture | null = null;
  CompositeTextureMode: ECompositeTextureMode = ECompositeTextureMode.CTM_Disabled;
  CompositePower: number = 0;
  LayerFormatSettings: Array<FTextureFormatSettings> = [];
  LODBias: number = 0;
  CompressionSettings: TextureCompressionSettings = TextureCompressionSettings.TC_Default;
  Filter: TextureFilter = TextureFilter.TF_Nearest;
  MipLoadOptions: ETextureMipLoadOptions = ETextureMipLoadOptions.Default;
  VirtualTextureStreamingPriority: EVTProducerPriority = EVTProducerPriority.Lowest;
  VirtualTexturePrefetchMips: number = 0;
  CookPlatformTilingSettings: TextureCookPlatformTilingSettings =
    TextureCookPlatformTilingSettings.TCPTS_FromTextureGroup;
  bOodlePreserveExtremes: boolean = false;
  LODGroup: TextureGroup = TextureGroup.TEXTUREGROUP_World;
  Downscale: FPerPlatformFloat = new FPerPlatformFloat();
  DownscaleOptions: ETextureDownscaleOptions = ETextureDownscaleOptions.Default;
  Availability: ETextureAvailability = ETextureAvailability.GPU;
  SRGB: boolean = false;
  bNormalizeNormals: boolean = false;
  bUseLegacyGamma: boolean = false;
  SourceColorSettings: FTextureSourceColorSettings = new FTextureSourceColorSettings();
  bNoTiling: boolean = false;
  VirtualTextureStreaming: boolean = false;
  bUseVirtualTextureStreamingPriority: boolean = false;
  CompressionYCoCg: boolean = false;
  AssetUserData: Array<UAssetUserData | null> = [];
}
