import { RegisterClass } from "../../../types/class-registry";
import type { FName } from "../../../types/Name";
import { NAME_None } from "../../../types/Name";
import type { UObject } from "../../CoreUObject/objects/Object";
import { FBoxSphereBounds } from "../../CoreUObject/structs/BoxSphereBounds";
import { FPerPlatformInt } from "../../CoreUObject/structs/PerPlatformProperties";
import { FVector3 } from "../../CoreUObject/structs/Vector3";
import { EStaticMeshPaintSupport } from "../enums/EStaticMeshPaintSupport";
import { FAssetEditorOrbitCameraPosition } from "../structs/AssetEditorOrbitCameraPosition";
import type { FMaterialRemapIndex } from "../structs/MaterialRemapIndex";
import { FMeshNaniteSettings } from "../structs/MeshNaniteSettings";
import { FMeshRayTracingProxySettings } from "../structs/MeshRayTracingProxySettings";
import { FMeshSectionInfoMap } from "../structs/MeshSectionInfoMap";
import { FPerQualityLevelInt } from "../structs/PerQualityLevelInt";
import type { FStaticMaterial } from "../structs/StaticMaterial";
import { FStaticMeshSourceModel } from "../structs/StaticMeshSourceModel";

import type { UAssetImportData } from "./AssetImportData";
import type { UAssetUserData } from "./AssetUserData";
import type { UMaterialInterface } from "./MaterialInterface";
import type { UStaticMeshSocket } from "./StaticMeshSocket";
import { UStreamableRenderAsset } from "./StreamableRenderAsset";
import type { UThumbnailInfo } from "./ThumbnailInfo";

@RegisterClass("/Script/Engine.StaticMesh")
export class UStaticMesh extends UStreamableRenderAsset {
  SourceModels: Array<FStaticMeshSourceModel> = [];
  HiResSourceModel: FStaticMeshSourceModel = new FStaticMeshSourceModel();
  SectionInfoMap: FMeshSectionInfoMap = new FMeshSectionInfoMap();
  OriginalSectionInfoMap: FMeshSectionInfoMap = new FMeshSectionInfoMap();
  LODGroup: FName = NAME_None;
  NumStreamedLODs: FPerPlatformInt = new FPerPlatformInt();
  ImportVersion: number = 0;
  MaterialRemapIndexPerImportVersion: Array<FMaterialRemapIndex> = [];
  LightmapUVVersion: number = 0;
  bAutoComputeLODScreenSize: boolean = false;
  Materials: Array<UMaterialInterface | null> = [];
  NaniteSettings: FMeshNaniteSettings = new FMeshNaniteSettings();
  MinQualityLevelLOD: FPerQualityLevelInt = new FPerQualityLevelInt();
  MinLOD: FPerPlatformInt = new FPerPlatformInt();
  ElementToIgnoreForTexFactor: number = 0;
  StaticMaterials: Array<FStaticMaterial> = [];
  LightmapUVDensity: number = 0;
  LightMapResolution: number = 0;
  LightMapCoordinateIndex: number = 0;
  StaticMeshPaintSupport: EStaticMeshPaintSupport = EStaticMeshPaintSupport.Default;
  MeshPaintTextureCoordinateIndex: number = 0;
  MeshPaintTextureResolution: number = 0;
  DistanceFieldSelfShadowBias: number = 0;
  LODForCollision: number = 0;
  bGenerateMeshDistanceField: boolean = false;
  bStripComplexCollisionForConsole: boolean = false;
  bHasNavigationData: boolean = false;
  bSupportUniformlyDistributedSampling: boolean = false;
  bSupportPhysicalMaterialMasks: boolean = false;
  bUseLegacyTangentScaling: boolean = false;
  RayTracingProxySettings: FMeshRayTracingProxySettings = new FMeshRayTracingProxySettings();
  bSupportRayTracing: boolean = false;
  bDoFastBuild: boolean = false;
  bIsBuiltAtRuntime: boolean = false;
  bAllowCPUAccess: boolean = false;
  bSupportGpuUniformlyDistributedSampling: boolean = false;
  AssetImportData: UAssetImportData | null = null;
  SourceFilePath: string = "";
  SourceFileTimestamp: string = "";
  ThumbnailInfo: UThumbnailInfo | null = null;
  EditorCameraPosition: FAssetEditorOrbitCameraPosition = new FAssetEditorOrbitCameraPosition();
  bCustomizedCollision: boolean = false;
  Sockets: Array<UStaticMeshSocket | null> = [];
  PositiveBoundsExtension: FVector3 = new FVector3();
  NegativeBoundsExtension: FVector3 = new FVector3();
  ExtendedBounds: FBoxSphereBounds = new FBoxSphereBounds();
  AssetUserData: Array<UAssetUserData | null> = [];
  EditableMesh: UObject | null = null;
  ComplexCollisionMesh: UStaticMesh | null = null;
}
