import type { FName } from "../../../types/Name";
import { NAME_None } from "../../../types/Name";
import { FColor } from "../../CoreUObject/structs/Color";
import type { FGuid } from "../../CoreUObject/structs/Guid";
import { GUID_None } from "../../CoreUObject/structs/Guid";
import { FPerPlatformFloat } from "../../CoreUObject/structs/PerPlatformProperties";
import { FVector4 } from "../../CoreUObject/structs/Vector4";
import { EVTProducerPriority } from "../../RenderCore/enums/EVTProducerPriority";
import { ECompositeTextureMode } from "../enums/ECompositeTextureMode";
import { ETextureAvailability } from "../enums/ETextureAvailability";
import { ETextureCompressionQuality } from "../enums/ETextureCompressionQuality";
import { ETextureDownscaleOptions } from "../enums/ETextureDownscaleOptions";
import { ETextureLossyCompressionAmount } from "../enums/ETextureLossyCompressionAmount";
import { ETextureMipLoadOptions } from "../enums/ETextureMipLoadOptions";
import { ETexturePowerOfTwoSetting } from "../enums/ETexturePowerOfTwoSetting";
import { TextureCompressionSettings } from "../enums/TextureCompressionSettings";
import { TextureCookPlatformTilingSettings } from "../enums/TextureCookPlatformTilingSettings";
import { TextureFilter } from "../enums/TextureFilter";
import { TextureGroup } from "../enums/TextureGroup";
import { TextureMipGenSettings } from "../enums/TextureMipGenSettings";
import type { FTextureFormatSettings } from "../structs/TextureFormatSettings";
import { FTextureSource } from "../structs/TextureSource";
import { FTextureSourceColorSettings } from "../structs/TextureSourceColorSettings";

import { RegisterClass } from "../../../types/class-registry";
import type { UAssetImportData } from "./AssetImportData";
import type { UAssetUserData } from "./AssetUserData";
import { UStreamableRenderAsset } from "./StreamableRenderAsset";

@RegisterClass("/Script/Engine.Texture")
export class UTexture extends UStreamableRenderAsset {
  Source: FTextureSource = new FTextureSource();
  LightingGuid: FGuid = GUID_None;
  SourceFilePath: string = "";
  AssetImportData: UAssetImportData | null = null;
  AdjustBrightness: number = 0;
  AdjustBrightnessCurve: number = 0;
  AdjustVibrance: number = 0;
  AdjustSaturation: number = 0;
  AdjustRGBCurve: number = 0;
  AdjustHue: number = 0;
  AdjustMinAlpha: number = 0;
  AdjustMaxAlpha: number = 0;
  CompressionNoAlpha: boolean = false;
  CompressionForceAlpha: boolean = false;
  CompressionNone: boolean = false;
  LossyCompressionAmount: ETextureLossyCompressionAmount = ETextureLossyCompressionAmount.TLCA_Default;
  OodleTextureSdkVersion: FName = NAME_None;
  MaxTextureSize: number = 0;
  CompressionQuality: ETextureCompressionQuality = ETextureCompressionQuality.TCQ_Default;
  CompressionCacheId: FGuid = GUID_None;
  bDitherMipMapAlpha: boolean = false;
  bDoScaleMipsForAlphaCoverage: boolean = false;
  AlphaCoverageThresholds: FVector4 = new FVector4();
  bUseNewMipFilter: boolean = false;
  bPreserveBorder: boolean = false;
  bFlipGreenChannel: boolean = false;
  PowerOfTwoMode: ETexturePowerOfTwoSetting = ETexturePowerOfTwoSetting.None;
  PaddingColor: FColor = new FColor();
  bPadWithBorderColor: boolean = false;
  ResizeDuringBuildX: number = 0;
  ResizeDuringBuildY: number = 0;
  bChromaKeyTexture: boolean = false;
  ChromaKeyThreshold: number = 0;
  ChromaKeyColor: FColor = new FColor();
  MipGenSettings: TextureMipGenSettings = TextureMipGenSettings.TMGS_FromTextureGroup;
  CompositeTexture: UTexture | null = null;
  CompositeTextureMode: ECompositeTextureMode = ECompositeTextureMode.CTM_Disabled;
  CompositePower: number = 0;
  LayerFormatSettings: Array<FTextureFormatSettings> = [];
  LODBias: number = 0;
  CompressionSettings: TextureCompressionSettings = TextureCompressionSettings.TC_Default;
  Filter: TextureFilter = TextureFilter.TF_Nearest;
  MipLoadOptions: ETextureMipLoadOptions = ETextureMipLoadOptions.Default;
  VirtualTextureStreamingPriority: EVTProducerPriority = EVTProducerPriority.Lowest;
  VirtualTexturePrefetchMips: number = 0;
  CookPlatformTilingSettings: TextureCookPlatformTilingSettings =
    TextureCookPlatformTilingSettings.TCPTS_FromTextureGroup;
  bOodlePreserveExtremes: boolean = false;
  LODGroup: TextureGroup = TextureGroup.TEXTUREGROUP_World;
  Downscale: FPerPlatformFloat = new FPerPlatformFloat();
  DownscaleOptions: ETextureDownscaleOptions = ETextureDownscaleOptions.Default;
  Availability: ETextureAvailability = ETextureAvailability.GPU;
  SRGB: boolean = false;
  bNormalizeNormals: boolean = false;
  bUseLegacyGamma: boolean = false;
  SourceColorSettings: FTextureSourceColorSettings = new FTextureSourceColorSettings();
  bNoTiling: boolean = false;
  VirtualTextureStreaming: boolean = false;
  bUseVirtualTextureStreamingPriority: boolean = false;
  CompressionYCoCg: boolean = false;
  AssetUserData: Array<UAssetUserData | null> = [];
}
