// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum ECommonUIObjectVersion {
  // region Introduced with UE 5.3.0
  Initial = 0,
  /// Updated the UCommonUILoadGuard to expose its content in a ULoadGuardSlot
  CreatedLoadGuardSlot = 1,
  // endregion
}

export const ECommonUIObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "Initial",
    value: 0,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "CreatedLoadGuardSlot",
    comment: "Updated the UCommonUILoadGuard to expose its content in a ULoadGuardSlot",
    value: 1,
    firstAppearance: "5.3.0",
  }),
];

export const ECommonUIObjectVersionGuid = new CustomVersionGuid<ECommonUIObjectVersion>({
  friendlyName: "CommonUI",
  guid: FGuid.fromComponents(0x4288211b, 0x454816c6, 0x1a7667b2, 0x507a2a00),
  details: ECommonUIObjectVersionDetails,
});
