// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FAnimObjectVersion {
  // region Introduced with UE 4.21.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Reworked how anim blueprint root nodes are recovered
  LinkTimeAnimBlueprintRootDiscovery = 1,
  /// Cached marker sync names on skeleton for editor
  StoreMarkerNamesOnSkeleton = 2,
  // endregion

  // region Introduced with UE 4.25.0
  /// Serialized register array state for RigVM
  SerializeRigVMRegisterArrayState = 3,
  /// Increase number of bones per chunk from uint8 to uint16
  IncreaseBoneIndexLimitPerChunk = 4,
  UnlimitedBoneInfluences = 5,
  /// Anim sequences have colors for their curves
  AnimSequenceCurveColors = 6,
  /// Notifies and sync markers now have Guids
  NotifyAndSyncMarkerGuids = 7,
  // endregion

  // region Introduced with UE 4.26.0
  /// Serialized register dynamic state for RigVM
  SerializeRigVMRegisterDynamicState = 8,
  /// Groom cards serialization
  SerializeGroomCards = 9,
  /// Serialized rigvm entry names
  SerializeRigVMEntries = 10,
  /// Serialized rigvm entry names
  SerializeHairBindingAsset = 11,
  /// Serialized rigvm entry names
  SerializeHairClusterCullingData = 12,
  /// Groom cards and meshes serialization
  SerializeGroomCardsAndMeshes = 13,
  /// Stripping LOD data from groom
  GroomLODStripping = 14,
  /// Stripping LOD data from groom
  GroomBindingSerialization = 15,
  // endregion
}

export const FAnimObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "LinkTimeAnimBlueprintRootDiscovery",
    comment: "Reworked how anim blueprint root nodes are recovered",
    value: 1,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "StoreMarkerNamesOnSkeleton",
    comment: "Cached marker sync names on skeleton for editor",
    value: 2,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "SerializeRigVMRegisterArrayState",
    comment: "Serialized register array state for RigVM",
    value: 3,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "IncreaseBoneIndexLimitPerChunk",
    comment: "Increase number of bones per chunk from uint8 to uint16",
    value: 4,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "UnlimitedBoneInfluences",
    value: 5,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AnimSequenceCurveColors",
    comment: "Anim sequences have colors for their curves",
    value: 6,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "NotifyAndSyncMarkerGuids",
    comment: "Notifies and sync markers now have Guids",
    value: 7,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializeRigVMRegisterDynamicState",
    comment: "Serialized register dynamic state for RigVM",
    value: 8,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SerializeGroomCards",
    comment: "Groom cards serialization",
    value: 9,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SerializeRigVMEntries",
    comment: "Serialized rigvm entry names",
    value: 10,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SerializeHairBindingAsset",
    comment: "Serialized rigvm entry names",
    value: 11,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SerializeHairClusterCullingData",
    comment: "Serialized rigvm entry names",
    value: 12,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SerializeGroomCardsAndMeshes",
    comment: "Groom cards and meshes serialization",
    value: 13,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "GroomLODStripping",
    comment: "Stripping LOD data from groom",
    value: 14,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "GroomBindingSerialization",
    comment: "Stripping LOD data from groom",
    value: 15,
    firstAppearance: "4.26.0",
  }),
];

export const FAnimObjectVersionGuid = new CustomVersionGuid<FAnimObjectVersion>({
  friendlyName: "Dev-Anim",
  guid: FGuid.fromComponents(0xaf43a65d, 0x7fd34947, 0x98733e8e, 0xd9c1bb05),
  details: FAnimObjectVersionDetails,
});
