// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FAnimNextStateTreeCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Added unique name to inner state tree
  InnerStateTreeUniqueName = 1,
  // endregion
}

export const FAnimNextStateTreeCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "InnerStateTreeUniqueName",
    comment: "Added unique name to inner state tree",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FAnimNextStateTreeCustomVersionGuid = new CustomVersionGuid<FAnimNextStateTreeCustomVersion>({
  friendlyName: "AnimNextStateTree",
  guid: FGuid.fromComponents(0x45641511, 0x102f42bb, 0xa6ef181d, 0x6c442cac),
  details: FAnimNextStateTreeCustomVersionDetails,
});
