// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FAnimNextTraceCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made in the plugin
  FirstVersion = 0,
  // endregion
}

export const FAnimNextTraceCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "FirstVersion",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.6.0",
  }),
];

export const FAnimNextTraceCustomVersionGuid = new CustomVersionGuid<FAnimNextTraceCustomVersion>({
  friendlyName: "FAnimNextTraceCustomVersion",
  guid: FGuid.fromComponents(0x83e9be13, 0xb1c845dc, 0x86c4d3e5, 0xe66cbe91),
  details: FAnimNextTraceCustomVersionDetails,
});
