// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FAssetRegistryVersion {
  // region Introduced with UE 4.26.0
  PreVersioning = 0,
  /// From before file versioning was implemented
  HardSoftDependencies = 1,
  /// The first version of the runtime asset registry to include file versioning.
  AddAssetRegistryState = 2,
  /// Added FAssetRegistryState and support for piecemeal serialization
  ChangedAssetData = 3,
  /// AssetData serialization format changed, versions before this are not readable
  RemovedMD5Hash = 4,
  /// Removed MD5 hash from package data
  AddedHardManage = 5,
  /// Added hard/soft manage references
  AddedCookedMD5Hash = 6,
  /// Added MD5 hash of cooked package to package data
  AddedDependencyFlags = 7,
  // endregion

  // region Introduced with UE 4.27.0
  /// Added UE::AssetRegistry::EDependencyProperty to each dependency
  FixedTags = 8,
  // endregion

  // region Introduced with UE 5.0.0
  /// * All configs can mix fixed and loose tag maps
  WorkspaceDomain = 9,
  /// Added Version information to AssetPackageData
  PackageImportedClasses = 10,
  /// Added ImportedClasses to AssetPackageData
  PackageFileSummaryVersionChange = 11,
  /// A new version number of UE5 was added to FPackageFileSummary
  ObjectResourceOptionalVersionChange = 12,
  // endregion

  // region Introduced with UE 5.1.0
  /// Change to linker export/import resource serialization
  AddedChunkHashes = 13,
  /// Added FIoHash for each FIoChunkId in the package to the AssetPackageData.
  ClassPaths = 14,
  /// Classes are serialized as path names rather than short object names, e.g. /Script/Engine.StaticMesh
  RemoveAssetPathFNames = 15,
  /// Asset bundles are serialized as FTopLevelAssetPath instead of FSoftObjectPath, deprecated FAssetData::ObjectPath
  AddedHeader = 16,
  // endregion

  // region Introduced with UE 5.2.0
  /// Added header with bFilterEditorOnlyData flag
  AssetPackageDataHasExtension = 17,
  // endregion
}

export const FAssetRegistryVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "HardSoftDependencies",
    comment: "From before file versioning was implemented",
    value: 1,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "AddAssetRegistryState",
    comment:
      "The first version of the runtime asset registry to include file versioning.",
    value: 2,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "ChangedAssetData",
    comment:
      "Added FAssetRegistryState and support for piecemeal serialization",
    value: 3,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "RemovedMD5Hash",
    comment:
      "AssetData serialization format changed, versions before this are not readable",
    value: 4,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "AddedHardManage",
    comment: "Removed MD5 hash from package data",
    value: 5,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "AddedCookedMD5Hash",
    comment: "Added hard/soft manage references",
    value: 6,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "AddedDependencyFlags",
    comment: "Added MD5 hash of cooked package to package data",
    value: 7,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixedTags",
    comment: "Added UE::AssetRegistry::EDependencyProperty to each dependency",
    value: 8,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "WorkspaceDomain",
    comment: "* All configs can mix fixed and loose tag maps ",
    value: 9,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "PackageImportedClasses",
    comment: "Added Version information to AssetPackageData",
    value: 10,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "PackageFileSummaryVersionChange",
    comment: "Added ImportedClasses to AssetPackageData",
    value: 11,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "ObjectResourceOptionalVersionChange",
    comment: "A new version number of UE5 was added to FPackageFileSummary",
    value: 12,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "AddedChunkHashes",
    comment: "Change to linker export/import resource serialization",
    value: 13,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ClassPaths",
    comment:
      "Added FIoHash for each FIoChunkId in the package to the AssetPackageData.",
    value: 14,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "RemoveAssetPathFNames",
    comment:
      "Classes are serialized as path names rather than short object names, e.g. /Script/Engine.StaticMesh",
    value: 15,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "AddedHeader",
    comment:
      "Asset bundles are serialized as FTopLevelAssetPath instead of FSoftObjectPath, deprecated FAssetData::ObjectPath	",
    value: 16,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "AssetPackageDataHasExtension",
    comment: "Added header with bFilterEditorOnlyData flag ",
    value: 17,
    firstAppearance: "5.2.0",
  }),
];
