// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FAvaExtrudeModifierVersion {
  // region Introduced with UE 5.6.0
  PreVersioning = 0,
  ExtrudeMode = 1,
  // endregion
}

export const FAvaExtrudeModifierVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ExtrudeMode",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FAvaExtrudeModifierVersionGuid = new CustomVersionGuid<FAvaExtrudeModifierVersion>({
  friendlyName: "AvaExtrudeModifierVersion",
  guid: FGuid.fromComponents(0x9271d8a5, 0xbf414602, 0xa20fc0a4, 0x9d829563),
  details: FAvaExtrudeModifierVersionDetails,
});
