// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FBlueprintsObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  OverridenEventReferenceFixup = 1,
  CleanBlueprintFunctionFlags = 2,
  ArrayGetByRefUpgrade = 3,
  // endregion

  // region Introduced with UE 4.13.0
  EdGraphPinOptimized = 4,
  AllowDeletionConformed = 5,
  // endregion

  // region Introduced with UE 4.14.0
  AdvancedContainerSupport = 6,
  SCSHasComponentTemplateClass = 7,
  // endregion

  // region Introduced with UE 4.15.0
  ComponentTemplateClassSupport = 8,
  // endregion

  // region Introduced with UE 4.16.0
  ArrayGetFuncsReplacedByCustomNode = 9,
  // endregion

  // region Introduced with UE 4.17.0
  DisallowObjectConfigVars = 10,
  // endregion
}

export const FBlueprintsObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "OverridenEventReferenceFixup",
    value: 1,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "CleanBlueprintFunctionFlags",
    value: 2,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "ArrayGetByRefUpgrade",
    value: 3,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "EdGraphPinOptimized",
    value: 4,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "AllowDeletionConformed",
    value: 5,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "AdvancedContainerSupport",
    value: 6,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "SCSHasComponentTemplateClass",
    value: 7,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "ComponentTemplateClassSupport",
    value: 8,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "ArrayGetFuncsReplacedByCustomNode",
    value: 9,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "DisallowObjectConfigVars",
    value: 10,
    firstAppearance: "4.17.0",
  }),
];
