// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FBuildObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FBuildObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
];

export const FBuildObjectVersionGuid = new CustomVersionGuid<FBuildObjectVersion>({
  friendlyName: "Dev-Build",
  guid: FGuid.fromComponents(0xe1c64328, 0xa22c4d53, 0xa36c8e86, 0x6417bd8c),
  details: FBuildObjectVersionDetails,
});
