// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FCEEffectorActorVersion {
  // region Introduced with UE 5.6.0
  PreVersioning = 0,
  ComponentMigration = 1,
  // endregion
}

export const FCEEffectorActorVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ComponentMigration",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FCEEffectorActorVersionGuid = new CustomVersionGuid<FCEEffectorActorVersion>({
  friendlyName: "CEEffectorActorVersion",
  guid: FGuid.fromComponents(0x9271d8a6, 0xbf4146b2, 0xa20fc0a4, 0x9d8295b3),
  details: FCEEffectorActorVersionDetails,
});
