// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FChaosClothConfigCustomVersion {
  // region Introduced with UE 5.4.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Update drag default to better preserve legacy behavior
  UpdateDragDefault = 1,
  /// Added damping and collision thickness per cloth
  AddDampingThicknessMigration = 2,
  /// Added gravity and self collision thickness per cloth
  AddGravitySelfCollisionMigration = 3,
  /// Remove internal config parameters from UI
  RemoveInternalConfigParameters = 4,
  /// Add a parameter to fix the backstop behavior without breaking PhysX assets backward compatibility
  AddLegacyBackstopParameter = 5,
  // endregion
}

export const FChaosClothConfigCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "UpdateDragDefault",
    comment: "Update drag default to better preserve legacy behavior",
    value: 1,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddDampingThicknessMigration",
    comment: "Added damping and collision thickness per cloth",
    value: 2,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddGravitySelfCollisionMigration",
    comment: "Added gravity and self collision thickness per cloth",
    value: 3,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "RemoveInternalConfigParameters",
    comment: "Remove internal config parameters from UI",
    value: 4,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddLegacyBackstopParameter",
    comment: "Add a parameter to fix the backstop behavior without breaking PhysX assets backward compatibility",
    value: 5,
    firstAppearance: "5.4.0",
  }),
];
