// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FChaosClothSharedConfigCustomVersion {
  // region Introduced with UE 5.4.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added gravity override/gravity scale properties
  AddGravityOverride = 1,
  // endregion
}

export const FChaosClothSharedConfigCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddGravityOverride",
    comment: "Added gravity override/gravity scale properties",
    value: 1,
    firstAppearance: "5.4.0",
  }),
];
