// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FCineCameraObjectVersion {
  // region Introduced with UE 4.24.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Changed default filmback to digital film
  ChangeDefaultFilmbackToDigitalFilm = 1,
  // endregion
}

export const FCineCameraObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "ChangeDefaultFilmbackToDigitalFilm",
    comment: "Changed default filmback to digital film",
    value: 1,
    firstAppearance: "4.24.0",
  }),
];
