// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FClothConfigNvCustomVersion {
  // region Introduced with UE 4.25.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Deprecate legacy structure and enum that couldn't be redirected
  DeprecateLegacyStructureAndEnum = 1,
  // endregion
}

export const FClothConfigNvCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "DeprecateLegacyStructureAndEnum",
    comment: "Deprecate legacy structure and enum that couldn't be redirected",
    value: 1,
    firstAppearance: "4.25.0",
  }),
];

export const FClothConfigNvCustomVersionGuid = new CustomVersionGuid<FClothConfigNvCustomVersion>({
  friendlyName: "ClothConfigNvVer",
  guid: FGuid.fromComponents(0x9950b70e, 0xb41a4e17, 0xbbccfa0d, 0x57817fd6),
  details: FClothConfigNvCustomVersionDetails,
});
