// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FClothingAssetCustomVersion {
  // region Introduced with UE 4.25.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added storage of vertex colors with sim data, for editor usage
  AddVertexColorsToPhysicalMesh = 1,
  /// Changed memory layouts by moving some properties to base classes
  MovePropertiesToCommonBaseClasses = 2,
  // endregion
}

export const FClothingAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddVertexColorsToPhysicalMesh",
    comment: "Added storage of vertex colors with sim data, for editor usage",
    value: 1,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "MovePropertiesToCommonBaseClasses",
    comment: "Changed memory layouts by moving some properties to base classes",
    value: 2,
    firstAppearance: "4.25.0",
  }),
];

export const FClothingAssetCustomVersionGuid = new CustomVersionGuid<FClothingAssetCustomVersion>({
  friendlyName: "ClothingAssetVer",
  guid: FGuid.fromComponents(0xfb680af2, 0x59ef4ba3, 0xbaa819b5, 0x73c8443d),
  details: FClothingAssetCustomVersionDetails,
});
