// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FClothingAssetCustomVersion {
  // region Introduced with UE 4.25.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added storage of vertex colors with sim data, for editor usage
  AddVertexColorsToPhysicalMesh = 1,
  /// Changed memory layouts by moving some properties to base classes
  MovePropertiesToCommonBaseClasses = 2,
  // endregion
}

export const FClothingAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddVertexColorsToPhysicalMesh",
    comment: "Added storage of vertex colors with sim data, for editor usage",
    value: 1,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "MovePropertiesToCommonBaseClasses",
    comment: "Changed memory layouts by moving some properties to base classes",
    value: 2,
    firstAppearance: "4.25.0",
  }),
];
