// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FComputeFrameworkObjectVersion {
  // region Introduced with UE 5.1.0
  InitialVersion = 0,
  // endregion
}

export const FComputeFrameworkObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "InitialVersion",
    value: 0,
    firstAppearance: "5.1.0",
  }),
];

export const FComputeFrameworkObjectVersionGuid = new CustomVersionGuid<FComputeFrameworkObjectVersion>({
  friendlyName: "Dev-ComputeFramework",
  guid: FGuid.fromComponents(0x6304a3e7, 0x00594f59, 0x8cfc21bd, 0x7721fd4e),
  details: FComputeFrameworkObjectVersionDetails,
});
