// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FCoreObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  MaterialInputNativeSerialize = 1,
  // endregion

  // region Introduced with UE 4.15.0
  EnumProperties = 2,
  // endregion

  // region Introduced with UE 4.22.0
  SkeletalMaterialEditorDataStripping = 3,
  // endregion

  // region Introduced with UE 4.25.0
  FProperties = 4,
  // endregion
}

export const FCoreObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "MaterialInputNativeSerialize",
    value: 1,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "EnumProperties",
    value: 2,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "SkeletalMaterialEditorDataStripping",
    value: 3,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "FProperties",
    value: 4,
    firstAppearance: "4.25.0",
  }),
];
