// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FCustomizableObjectCustomVersion {
  // region Introduced with UE 5.5.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  FixBlueprintPinsUseRealNumbers = 1,
  NodeExposePinOnNameChangedDelegateAdded = 2,
  GroupProjectorPinTypeAdded = 3,
  AutomaticNodeMaterial = 4,
  AutomaticNodeMaterialPerformance = 5,
  LayoutClassAdded = 6,
  AutomaticNodeMaterialPerformanceBug = 7,
  PinsNamesImageToTexture = 8,
  BugPinsSwitch = 9,
  PostLoadToCustomVersion = 10,
  /// Wrapped old backwards compatible code that was located at PostLoads inside this custom version.
  AutomaticNodeMaterialUXImprovements = 11,
  ExtendMaterialOnlyMutableModeParameters = 12,
  ExtendMaterialOnlyMutableModeParametersBug = 13,
  ExtendMaterialRemoveImages = 14,
  EditMaterialOnlyMutableModeParameters = 15,
  /// Force refresh to avoid having Images which are not in Mutable mode.
  GroupProjectorIntToScalarIndex = 16,
  FixBlueprintPinsUseRealNumbersAgain = 17,
  NodeMaterialAddTablePin = 18,
  MorphMaterialAddFactorPin = 19,
  NodeSkeletalMeshCorruptedPinRef = 20,
  CustomizableObjectInstanceDescriptor = 21,
  DescriptorBuildParameterDecorations = 22,
  DescriptorMultilayerProjectors = 23,
  DeformSkeletonOptionsAdded = 24,
  GroupProjectorImagePin = 25,
  GroupProjectorImagePinRemoved = 26,
  StateTextureCompressionStrategyEnum = 27,
  AddedTableNodesTextureMode = 28,
  ConvertAnimationSlotToFName = 29,
  RemovedParameterDecorations = 30,
  AutomaticNodeSkeletalMesh = 31,
  AutomaticNodeSkeletalMeshPinDataOuter = 32,
  AutomaticNodeSkeletalMeshPinDataUProperty = 33,
  EditMaterialMaskPinDesync = 34,
  /// MTBL-979
  IgnoreDisabledSections = 35,
  SkeletalMeshNodeDefaultPinWithoutPinData = 36,
  AddedTableMaterialSwitch = 37,
  FixPinsNamesImageToTexture2 = 38,
  MeshReshapeVertexColorUsageSelection = 39,
  DeduplicateNodeVariant = 40,
  TextureCompressionEnum = 41,
  NodeTextureParameterDefaultToReferenceValue = 42,
  NodeVariationSerializationIssue = 43,
  /// The parent class and child classes had a member with the same name. Unreal was serialized the member from the child class but deserialized it to the parent class.
  RegenerateNodeObjectsIds = 44,
  NodeMaterialPinDataImageDetails = 45,
  CustomizableObjectStateHasSeparateNeverStreamFlag = 46,
  CustomizableObjectNodeHasSeparateNeverStreamFlag = 47,
  AddedColumnIdDataToTableNodePins = 48,
  AddedAnyTextureTypeToPassThroughTextures = 49,
  ProjectorNodesDefaultValueFix = 50,
  StateUIMetadata = 51,
  AddedRenameOptionToParameterNodes = 52,
  CompilationOptions = 53,
  NodeTablePinViewer = 54,
  NewComponentOptions = 55,
  NodeMaterialTypedImagePins = 56,
  FixedMultilayerMaterialIds = 57,
  UseUVRects = 58,
  /// Instead of pointing at layout blocks in the edited parent, define custom absolute UV layout rects.
  AddModifierPin = 59,
  /// Move the modifiers output pin from Material to Modifier
  CorrectlySerializeTableToParamNames = 60,
  MovedCompatibilityFromPostBackwardsCompatibleFixup = 61,
  FixModifierPin = 62,
  ConvertEditAndExtendToModifiers = 63,
  NodeComponentMesh = 64,
  /// Moved LOD pins from NodeObject to NodeComponentMesh.
  MergeNodeComponents = 65,
  UnifyRequiredTags = 66,
  MaterialPinsRename = 67,
  /// Moved from "Material" to "Mesh Section"
  MoveLayoutToNodeSkeletalMesh = 68,
  /// Move the layouts from the NodeLayout to the NodeSkeletalMesh
  RemoveNodeLayout = 69,
  ComponentsArray = 70,
  FixMaterialPinsRename = 71,
  ModifierClipWithMeshCleanup = 72,
  RealTimeMorphTargetOverrideDataStructureRework = 73,
  FixAutomaticBlocksStrategyLegacyNodes = 74,
  SnapToBoneComponentIndexToName = 75,
  // endregion

  // region Introduced with UE 5.6.0
  SetDisplayNamePropertyAsPinNameOfTableNodes = 76,
  // endregion

  // region Introduced with UE 5.5.4
  FixedNoPinsInRerouteNodes = 77,
  // endregion

  // region Introduced with UE 5.6.0
  TableNoneOptionsMovedToUnrealCode = 78,
  UpdatedNodesPinName = 79,
  UpdatedNodesPinName2 = 80,
  UpdatedNodesPinName3 = 81,
  TextureVariationsToVariations = 82,
  MovedLODSettingsToMeshComponentNode = 83,
  AddedTableNodeCompilationFilters = 84,
  ChangedComponentsInheritance = 85,
  ChangedSwitchNodesInputPinsFriendlyNames = 86,
  TableNodeCompilationFilterArray = 87,
  EnableMutableMacros = 88,
  EnableMutableMacrosNewVersion = 89,
  // endregion
}

export const FCustomizableObjectCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixBlueprintPinsUseRealNumbers",
    value: 1,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeExposePinOnNameChangedDelegateAdded",
    value: 2,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "GroupProjectorPinTypeAdded",
    value: 3,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeMaterial",
    value: 4,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeMaterialPerformance",
    value: 5,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LayoutClassAdded",
    value: 6,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeMaterialPerformanceBug",
    value: 7,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PinsNamesImageToTexture",
    value: 8,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "BugPinsSwitch",
    value: 9,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PostLoadToCustomVersion",
    value: 10,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeMaterialUXImprovements",
    comment: "Wrapped old backwards compatible code that was located at PostLoads inside this custom version.",
    value: 11,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ExtendMaterialOnlyMutableModeParameters",
    value: 12,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ExtendMaterialOnlyMutableModeParametersBug",
    value: 13,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ExtendMaterialRemoveImages",
    value: 14,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "EditMaterialOnlyMutableModeParameters",
    value: 15,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "GroupProjectorIntToScalarIndex",
    comment: "Force refresh to avoid having Images which are not in Mutable mode.",
    value: 16,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixBlueprintPinsUseRealNumbersAgain",
    value: 17,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeMaterialAddTablePin",
    value: 18,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MorphMaterialAddFactorPin",
    value: 19,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeSkeletalMeshCorruptedPinRef",
    value: 20,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "CustomizableObjectInstanceDescriptor",
    value: 21,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DescriptorBuildParameterDecorations",
    value: 22,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DescriptorMultilayerProjectors",
    value: 23,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DeformSkeletonOptionsAdded",
    value: 24,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "GroupProjectorImagePin",
    value: 25,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "GroupProjectorImagePinRemoved",
    value: 26,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "StateTextureCompressionStrategyEnum",
    value: 27,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddedTableNodesTextureMode",
    value: 28,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ConvertAnimationSlotToFName",
    value: 29,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "RemovedParameterDecorations",
    value: 30,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeSkeletalMesh",
    value: 31,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeSkeletalMeshPinDataOuter",
    value: 32,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AutomaticNodeSkeletalMeshPinDataUProperty",
    value: 33,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "EditMaterialMaskPinDesync",
    value: 34,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "IgnoreDisabledSections",
    comment: "MTBL-979",
    value: 35,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SkeletalMeshNodeDefaultPinWithoutPinData",
    value: 36,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddedTableMaterialSwitch",
    value: 37,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixPinsNamesImageToTexture2",
    value: 38,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MeshReshapeVertexColorUsageSelection",
    value: 39,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DeduplicateNodeVariant",
    value: 40,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "TextureCompressionEnum",
    value: 41,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeTextureParameterDefaultToReferenceValue",
    value: 42,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeVariationSerializationIssue",
    value: 43,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "RegenerateNodeObjectsIds",
    comment:
      "The parent class and child classes had a member with the same name. Unreal was serialized the member from the child class but deserialized it to the parent class.",
    value: 44,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeMaterialPinDataImageDetails",
    value: 45,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "CustomizableObjectStateHasSeparateNeverStreamFlag",
    value: 46,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "CustomizableObjectNodeHasSeparateNeverStreamFlag",
    value: 47,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddedColumnIdDataToTableNodePins",
    value: 48,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddedAnyTextureTypeToPassThroughTextures",
    value: 49,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ProjectorNodesDefaultValueFix",
    value: 50,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "StateUIMetadata",
    value: 51,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddedRenameOptionToParameterNodes",
    value: 52,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "CompilationOptions",
    value: 53,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeTablePinViewer",
    value: 54,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NewComponentOptions",
    value: 55,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeMaterialTypedImagePins",
    value: 56,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixedMultilayerMaterialIds",
    value: 57,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "UseUVRects",
    value: 58,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddModifierPin",
    comment: "Instead of pointing at layout blocks in the edited parent, define custom absolute UV layout rects.",
    value: 59,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "CorrectlySerializeTableToParamNames",
    comment: "Move the modifiers output pin from Material to Modifier",
    value: 60,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MovedCompatibilityFromPostBackwardsCompatibleFixup",
    value: 61,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixModifierPin",
    value: 62,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ConvertEditAndExtendToModifiers",
    value: 63,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "NodeComponentMesh",
    value: 64,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MergeNodeComponents",
    comment: "Moved LOD pins from NodeObject to NodeComponentMesh.",
    value: 65,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "UnifyRequiredTags",
    value: 66,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MaterialPinsRename",
    value: 67,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MoveLayoutToNodeSkeletalMesh",
    comment: 'Moved from "Material" to "Mesh Section"',
    value: 68,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "RemoveNodeLayout",
    comment: "Move the layouts from the NodeLayout to the NodeSkeletalMesh",
    value: 69,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ComponentsArray",
    value: 70,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixMaterialPinsRename",
    value: 71,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ModifierClipWithMeshCleanup",
    value: 72,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "RealTimeMorphTargetOverrideDataStructureRework",
    value: 73,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixAutomaticBlocksStrategyLegacyNodes",
    value: 74,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SnapToBoneComponentIndexToName",
    value: 75,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SetDisplayNamePropertyAsPinNameOfTableNodes",
    value: 76,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "FixedNoPinsInRerouteNodes",
    value: 77,
    firstAppearance: "5.5.4",
  }),
  new VersionDetails({
    name: "TableNoneOptionsMovedToUnrealCode",
    value: 78,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UpdatedNodesPinName",
    value: 79,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UpdatedNodesPinName2",
    value: 80,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UpdatedNodesPinName3",
    value: 81,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "TextureVariationsToVariations",
    value: 82,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "MovedLODSettingsToMeshComponentNode",
    value: 83,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddedTableNodeCompilationFilters",
    value: 84,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ChangedComponentsInheritance",
    value: 85,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ChangedSwitchNodesInputPinsFriendlyNames",
    value: 86,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "TableNodeCompilationFilterArray",
    value: 87,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "EnableMutableMacros",
    value: 88,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "EnableMutableMacrosNewVersion",
    value: 89,
    firstAppearance: "5.6.0",
  }),
];

export const FCustomizableObjectCustomVersionGuid = new CustomVersionGuid<FCustomizableObjectCustomVersion>({
  friendlyName: "CustomizableObjectVer",
  guid: FGuid.fromComponents(0xc1270312, 0xab730b1e, 0x0b1ec745, 0x71c70f73),
  details: FCustomizableObjectCustomVersionDetails,
});
