// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDestructionObjectVersion {
  // region Introduced with UE 4.22.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added timestamped caches for geometry component to handle transform sampling instead of per-frame
  AddedTimestampedGeometryComponentCache = 1,
  /// Added functionality to strip unnecessary data from geometry collection caches
  AddedCacheDataReduction = 2,
  // endregion

  // region Introduced with UE 4.23.0
  /// Geometry collection data is now in the DDC
  GeometryCollectionInDDC = 3,
  /// Geometry collection data is now in both the DDC and the asset
  GeometryCollectionInDDCAndAsset = 4,
  /// New way to serialize unique ptr and serializable ptr
  ChaosArchiveAdded = 5,
  /// Serialization support for UFieldSystems
  FieldsAdded = 6,
  /// density default units changed from kg/cm3 to kg/m3
  DensityUnitsChanged = 7,
  /// bulk serialize arrays
  BulkSerializeArrays = 8,
  /// bulk serialize arrays
  GroupAndAttributeNameRemapping = 9,
  // endregion

  // region Introduced with UE 4.25.0
  /// bulk serialize arrays
  ImplicitObjectDoCollideAttribute = 10,
  // endregion
}

export const FDestructionObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "AddedTimestampedGeometryComponentCache",
    comment: "Added timestamped caches for geometry component to handle transform sampling instead of per-frame",
    value: 1,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "AddedCacheDataReduction",
    comment: "Added functionality to strip unnecessary data from geometry collection caches",
    value: 2,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "GeometryCollectionInDDC",
    comment: "Geometry collection data is now in the DDC",
    value: 3,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "GeometryCollectionInDDCAndAsset",
    comment: "Geometry collection data is now in both the DDC and the asset",
    value: 4,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "ChaosArchiveAdded",
    comment: "New way to serialize unique ptr and serializable ptr",
    value: 5,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "FieldsAdded",
    comment: "Serialization support for UFieldSystems",
    value: 6,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "DensityUnitsChanged",
    comment: "density default units changed from kg/cm3 to kg/m3",
    value: 7,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "BulkSerializeArrays",
    comment: "bulk serialize arrays",
    value: 8,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "GroupAndAttributeNameRemapping",
    comment: "bulk serialize arrays",
    value: 9,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "ImplicitObjectDoCollideAttribute",
    comment: "bulk serialize arrays",
    value: 10,
    firstAppearance: "4.25.0",
  }),
];

export const FDestructionObjectVersionGuid = new CustomVersionGuid<FDestructionObjectVersion>({
  friendlyName: "Dev-Destruction",
  guid: FGuid.fromComponents(0x174f1f0b, 0xb4c645a5, 0xb13f2ee8, 0xd0fb917d),
  details: FDestructionObjectVersionDetails,
});
