// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDisplayClusterCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  ComponentParentChange_4_27 = 1,
  // endregion
}

export const FDisplayClusterCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ComponentParentChange_4_27",
    value: 1,
    firstAppearance: "4.27.0",
  }),
];

export const FDisplayClusterCustomVersionGuid = new CustomVersionGuid<FDisplayClusterCustomVersion>({
  friendlyName: "nDisplayVer",
  guid: FGuid.fromComponents(0x06c4f6dc, 0xf518b974, 0x87b0c096, 0xe3855b05),
  details: FDisplayClusterCustomVersionDetails,
});
