// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDMXPixelMappingMainStreamObjectVersion {
  // region Introduced with UE 5.6.0
  /// Roughly corresponds to 4.26
  BeforeCustomVersionWasAdded = 0,
  /// Update DMXPixelMappingMatrixComponent to no longer use a custom MatrixFixturePatchRef, but the default EntityFixturePatchRef one.
  ChangePixelMappingMatrixComponentToFixturePatchReference = 1,
  /// Update DMXPixelMappingBaseComponent to store the parent as a weak ptr
  UseWeakPtrForPixelMappingComponentParent = 2,
  /// Update DMXPixelMappingRendererComponent to lock those components that use a texture in designer to trigger the edit condition of the size property
  LockRendererComponentsThatUseTextureInDesigner = 3,
  /// Update DMXPixelMappingFixtureGroupItemComponent and DMXPixelMappingMatrixCellComponent to use DMXPixelMappingColorSpace
  UseDMXPixelMappingColorSpace = 4,
  /// The renderer component now holds the layout rect, so its children can be layout out relative to the current texture size
  RendererComponentHoldsLayoutRect = 5,
  /// 5.5: Color spaces now apply a gamma correction
  DMXOutputAppliesGammaCorrection = 6,
  /// 5.6: Each pixel mapping holds its own reset DMX mode
  PerPixelMappingResetDMXMode = 7,
  // endregion
}

export const FDMXPixelMappingMainStreamObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 4.26",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ChangePixelMappingMatrixComponentToFixturePatchReference",
    comment:
      "Update DMXPixelMappingMatrixComponent to no longer use a custom MatrixFixturePatchRef, but the default EntityFixturePatchRef one.",
    value: 1,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UseWeakPtrForPixelMappingComponentParent",
    comment: "Update DMXPixelMappingBaseComponent to store the parent as a weak ptr",
    value: 2,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "LockRendererComponentsThatUseTextureInDesigner",
    comment:
      "Update DMXPixelMappingRendererComponent to lock those components that use a texture in designer to trigger the edit condition of the size property",
    value: 3,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UseDMXPixelMappingColorSpace",
    comment:
      "Update DMXPixelMappingFixtureGroupItemComponent and DMXPixelMappingMatrixCellComponent to use DMXPixelMappingColorSpace",
    value: 4,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "RendererComponentHoldsLayoutRect",
    comment:
      "The renderer component now holds the layout rect, so its children can be layout out relative to the current texture size",
    value: 5,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "DMXOutputAppliesGammaCorrection",
    comment: "5.5: Color spaces now apply a gamma correction",
    value: 6,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PerPixelMappingResetDMXMode",
    comment: "5.6: Each pixel mapping holds its own reset DMX mode",
    value: 7,
    firstAppearance: "5.6.0",
  }),
];

export const FDMXPixelMappingMainStreamObjectVersionGuid =
  new CustomVersionGuid<FDMXPixelMappingMainStreamObjectVersion>({
    friendlyName: "DMXMainStreamObjectVer",
    guid: FGuid.fromComponents(0x75a7b683, 0x4f4c7e28, 0xdde54885, 0x85323940),
    details: FDMXPixelMappingMainStreamObjectVersionDetails,
  });
