// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDMXRuntimeMainStreamObjectVersion {
  // region Introduced with UE 5.1.0
  /// Roughly corresponds to 4.26
  BeforeCustomVersionWasAdded = 0,
  /// Update to DMX Library Section using normalized values by default
  DefaultToNormalizedValuesInDMXLibrarySection = 1,
  /// Update to DMX Library Section using normalized values by default
  ReplaceWeakWithStrongFixturePatchReferncesInLibrarySection = 2,
  /// Update DMX Entity Fixture Type to allow the Matrix to be enabled/disabled per Mode
  DMXFixtureTypeAllowMatrixInEachFixtureMode = 3,
  /// DMX Controllers are removed from the pugin
  DMXControllersAreRemoved = 4,
  /// Update Fixture Patch to use an MVR UUID
  DMXFixturePatchHasMVRUUID = 5,
  /// Remove auto assign features from fixture patch (instead it's auto assigned via FDMXEditorUtils where required)
  DMXFixturePatchNoLongerImplementsAutoAssign = 6,
  // endregion

  // region Introduced with UE 5.5.0
  /// Change the DMXImportGDTF asset reference in Fixture Type to a soft object ptr, to avoid loading the data (since UE 5.5)
  DMXImportGDTFIsASoftObjectPtr = 7,
  /// Update Fixture Patch to hold the MVR Fixture ID (since UE 5.5)
  DMXFixturePatchHasFixtureID = 8,
  /// Rename GDTF import assets with invalid names
  DMXFixGDTFImportAssetsWithInvalidNames = 9,
  /// Upgrade Fixture Functions to make use of pysical properties where required (e.g. Pan, Tilt, Zoom)
  DMXUpgradeFixtureFunctionsToUsePhysicalProperties = 10,
  /// Upgrade Fixture Patches to have a Default Transform
  DMXFixturePatchesHaveDefaultTransform = 11,
  /// 5.5 Upgrade MVR Scene Actor to spawn Actors per Fixture Type of per GDTF
  DMXMVRSceneActorSpawnsActorsPerFixtureType = 12,
  // endregion
}

export const FDMXRuntimeMainStreamObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 4.26",
    value: 0,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DefaultToNormalizedValuesInDMXLibrarySection",
    comment: "Update to DMX Library Section using normalized values by default",
    value: 1,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ReplaceWeakWithStrongFixturePatchReferncesInLibrarySection",
    comment: "Update to DMX Library Section using normalized values by default",
    value: 2,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DMXFixtureTypeAllowMatrixInEachFixtureMode",
    comment: "Update DMX Entity Fixture Type to allow the Matrix to be enabled/disabled per Mode",
    value: 3,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DMXControllersAreRemoved",
    comment: "DMX Controllers are removed from the pugin",
    value: 4,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DMXFixturePatchHasMVRUUID",
    comment: "Update Fixture Patch to use an MVR UUID",
    value: 5,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DMXFixturePatchNoLongerImplementsAutoAssign",
    comment:
      "Remove auto assign features from fixture patch (instead it's auto assigned via FDMXEditorUtils where required)",
    value: 6,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "DMXImportGDTFIsASoftObjectPtr",
    comment:
      "Change the DMXImportGDTF asset reference in Fixture Type to a soft object ptr, to avoid loading the data (since UE 5.5)",
    value: 7,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXFixturePatchHasFixtureID",
    comment: "Update Fixture Patch to hold the MVR Fixture ID (since UE 5.5)",
    value: 8,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXFixGDTFImportAssetsWithInvalidNames",
    comment: "Rename GDTF import assets with invalid names",
    value: 9,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXUpgradeFixtureFunctionsToUsePhysicalProperties",
    comment: "Upgrade Fixture Functions to make use of pysical properties where required (e.g. Pan, Tilt, Zoom)",
    value: 10,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXFixturePatchesHaveDefaultTransform",
    comment: "Upgrade Fixture Patches to have a Default Transform",
    value: 11,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXMVRSceneActorSpawnsActorsPerFixtureType",
    comment: "5.5 Upgrade MVR Scene Actor to spawn Actors per Fixture Type of per GDTF",
    value: 12,
    firstAppearance: "5.5.0",
  }),
];

export const FDMXRuntimeMainStreamObjectVersionGuid = new CustomVersionGuid<FDMXRuntimeMainStreamObjectVersion>({
  friendlyName: "DMXRuntimeMainStreamObjectVersion",
  guid: FGuid.fromComponents(0x75a7b683, 0x4f4c7e28, 0xdde54885, 0x85323939),
  details: FDMXRuntimeMainStreamObjectVersionDetails,
});
