// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDMXControlConsoleMainStreamObjectVersion {
  // region Introduced with UE 5.5.0
  /// Roughly corresponds to 5.5
  BeforeCustomVersionWasAdded = 0,
  /// 5.5 Upgrade Control Console Fader Group to use a Fixture Patch Ref instead of a Soft Object Ptr
  DMXControlConsoleFaderGroupUsesFixturePatchRef = 1,
  // endregion
}

export const FDMXControlConsoleMainStreamObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 5.5",
    value: 0,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DMXControlConsoleFaderGroupUsesFixturePatchRef",
    comment: "5.5 Upgrade Control Console Fader Group to use a Fixture Patch Ref instead of a Soft Object Ptr",
    value: 1,
    firstAppearance: "5.5.0",
  }),
];

export const FDMXControlConsoleMainStreamObjectVersionGuid =
  new CustomVersionGuid<FDMXControlConsoleMainStreamObjectVersion>({
    friendlyName: "DMXControlConsoleMainStreamObjectVersion",
    guid: FGuid.fromComponents(0x6c3be9c2, 0x4d818685, 0x4d93abae, 0x9af3c0ba),
    details: FDMXControlConsoleMainStreamObjectVersionDetails,
  });
