// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDNAAssetCustomVersion {
  // region Introduced with UE 4.26.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FDNAAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.26.0",
  }),
];

export const FDNAAssetCustomVersionGuid = new CustomVersionGuid<FDNAAssetCustomVersion>({
  friendlyName: "DNAAssetVer",
  guid: FGuid.fromComponents(0x9de7bd98, 0x67d445b2, 0x8c0e9d73, 0xfde1e367),
  details: FDNAAssetCustomVersionDetails,
});
