// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FDNAAssetCustomVersion {
  // region Introduced with UE 4.26.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FDNAAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.26.0",
  }),
];
