// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FDynamicMaterialModelEditorOnlyDataVersion {
  // region Introduced with UE 5.6.0
  PreVersioning = 0,
  GlobalValueRename = 1,
  // endregion
}

export const FDynamicMaterialModelEditorOnlyDataVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "GlobalValueRename",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FDynamicMaterialModelEditorOnlyDataVersionGuid =
  new CustomVersionGuid<FDynamicMaterialModelEditorOnlyDataVersion>({
    friendlyName: "DynamicMaterialModelEditorOnlyData",
    guid: FGuid.fromComponents(0xfcf57afc, 0x50764285, 0xb9a9e660, 0xffa02d34),
    details: FDynamicMaterialModelEditorOnlyDataVersionDetails,
  });
