// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FEditorObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Localizable text gathered and stored in packages is now flagged with a localizable text gathering process version
  GatheredTextProcessVersionFlagging = 1,
  // endregion

  // region Introduced with UE 4.13.0
  /// Fixed several issues with the gathered text cache stored in package headers
  GatheredTextPackageCacheFixesV1 = 2,
  /// Added support for "root" meta-data (meta-data not associated with a particular object in a package)
  RootMetaDataSupport = 3,
  /// Fixed issues with how Blueprint bytecode was cached
  GatheredTextPackageCacheFixesV2 = 4,
  /// Updated FFormatArgumentData to allow variant data to be marshaled from a BP into C++
  TextFormatArgumentDataIsVariant = 5,
  /// Changes to SplineComponent
  SplineComponentCurvesInStruct = 6,
  // endregion

  // region Introduced with UE 4.14.0
  /// Updated ComboBox to support toggling the menu open, better controller support
  ComboBoxControllerSupportUpdate = 7,
  /// Refactor mesh editor materials
  RefactorMeshEditorMaterials = 8,
  // endregion

  // region Introduced with UE 4.15.0
  /// Added UFontFace assets
  AddedFontFaceAssets = 9,
  /// Add UPROPERTY for TMap of Mesh section, so the serialize will be done normally (and export to text will work correctly)
  UPropertryForMeshSection = 10,
  /// Update the schema of all widget blueprints to use the WidgetGraphSchema
  WidgetGraphSchema = 11,
  /// Added a specialized content slot to the background blur widget
  AddedBackgroundBlurContentSlot = 12,
  /// Updated UserDefinedEnums to have stable keyed display names
  StableUserDefinedEnumDisplayNames = 13,
  /// Added "Inline" option to UFontFace assets
  AddedInlineFontFaceAssets = 14,
  // endregion

  // region Introduced with UE 4.16.0
  /// Fix a serialization issue with static mesh FMeshSectionInfoMap FProperty
  UPropertryForMeshSectionSerialize = 15,
  /// Adding a version bump for the new fast widget construction in case of problems.
  FastWidgetTemplates = 16,
  /// Update material thumbnails to be more intelligent on default primitive shape for certain material types
  MaterialThumbnailRenderingChanges = 17,
  // endregion

  // region Introduced with UE 4.17.0
  /// Introducing a new clipping system for Slate/UMG
  NewSlateClippingSystem = 18,
  /// MovieScene Meta Data added as native Serialization
  MovieSceneMetaDataSerialization = 19,
  /// Text gathered from properties now adds two variants: a version without the package localization ID (for use at runtime), and a version with it (which is editor-only)
  GatheredTextEditorOnlyPackageLocId = 20,
  // endregion

  // region Introduced with UE 4.19.0
  /// Added AlwaysSign to FNumberFormattingOptions
  AddedAlwaysSignNumberFormattingOption = 21,
  /// Added additional objects that must be serialized as part of this new material feature
  AddedMaterialSharedInputs = 22,
  /// Added morph target section indices
  AddedMorphTargetSectionIndices = 23,
  // endregion

  // region Introduced with UE 4.20.0
  /// Serialize the instanced static mesh render data, to avoid building it at runtime
  SerializeInstancedStaticMeshRenderData = 24,
  // endregion

  // region Introduced with UE 4.21.0
  /// Change to MeshDescription serialization (moved to release)
  MeshDescriptionNewSerialization_MovedToRelease = 25,
  /// New format for mesh description attributes
  MeshDescriptionNewAttributeFormat = 26,
  // endregion

  // region Introduced with UE 4.22.0
  /// Switch root component of SceneCapture actors from MeshComponent to SceneComponent
  ChangeSceneCaptureRootComponent = 27,
  /// StaticMesh serializes MeshDescription instead of RawMesh
  StaticMeshDeprecatedRawMesh = 28,
  /// MeshDescriptionBulkData contains a Guid used as a DDC key
  MeshDescriptionBulkDataGuid = 29,
  /// Change to MeshDescription serialization (removed FMeshPolygon::HoleContours)
  MeshDescriptionRemovedHoles = 30,
  // endregion

  // region Introduced with UE 4.23.0
  /// Change to the WidgetCompoent WindowVisibilty default value
  ChangedWidgetComponentWindowVisibilityDefault = 31,
  /// Avoid keying culture invariant display strings during serialization to avoid non-deterministic cooking issues
  CultureInvariantTextSerializationKeyStability = 32,
  /// Change to UScrollBar and UScrollBox thickness property (removed implicit padding of 2, so thickness value must be incremented by 4).
  ScrollBarThicknessChange = 33,
  /// Deprecated LandscapeHoleMaterial
  RemoveLandscapeHoleMaterial = 34,
  // endregion

  // region Introduced with UE 4.24.0
  /// MeshDescription defined by triangles instead of arbitrary polygons
  MeshDescriptionTriangles = 35,
  /// Add weighted area and angle when computing the normals
  ComputeWeightedNormals = 36,
  /// SkeletalMesh now can be rebuild in editor, no more need to re-import
  SkeletalMeshBuildRefactor = 37,
  // endregion

  // region Introduced with UE 4.25.0
  /// Move all SkeletalMesh source data into a private uasset in the same package has the skeletalmesh
  SkeletalMeshMoveEditorSourceDataToPrivateAsset = 38,
  // endregion

  // region Introduced with UE 4.26.0
  /// Parse text only if the number is inside the limits of its type
  NumberParsingOptionsNumberLimitsAndClamping = 39,
  /// Make sure we can have more then 255 material in the skeletal mesh source data
  SkeletalMeshSourceDataSupport16bitOfMaterialNumber = 40,
  // endregion

  // region Introduced with UE 4.12.0
  /// Fixed several issues with the gathered text cache stored in package headers
  GatheredTextPackageCacheFixes = 2,
  // endregion
}

export const FEditorObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "GatheredTextProcessVersionFlagging",
    comment: "Localizable text gathered and stored in packages is now flagged with a localizable text gathering process version",
    value: 1,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "GatheredTextPackageCacheFixesV1",
    comment: "Fixed several issues with the gathered text cache stored in package headers",
    value: 2,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "RootMetaDataSupport",
    comment: "Added support for \"root\" meta-data (meta-data not associated with a particular object in a package)",
    value: 3,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "GatheredTextPackageCacheFixesV2",
    comment: "Fixed issues with how Blueprint bytecode was cached",
    value: 4,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "TextFormatArgumentDataIsVariant",
    comment: "Updated FFormatArgumentData to allow variant data to be marshaled from a BP into C++",
    value: 5,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "SplineComponentCurvesInStruct",
    comment: "Changes to SplineComponent",
    value: 6,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "ComboBoxControllerSupportUpdate",
    comment: "Updated ComboBox to support toggling the menu open, better controller support",
    value: 7,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "RefactorMeshEditorMaterials",
    comment: "Refactor mesh editor materials",
    value: 8,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "AddedFontFaceAssets",
    comment: "Added UFontFace assets",
    value: 9,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "UPropertryForMeshSection",
    comment: "Add UPROPERTY for TMap of Mesh section, so the serialize will be done normally (and export to text will work correctly)",
    value: 10,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "WidgetGraphSchema",
    comment: "Update the schema of all widget blueprints to use the WidgetGraphSchema",
    value: 11,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "AddedBackgroundBlurContentSlot",
    comment: "Added a specialized content slot to the background blur widget",
    value: 12,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "StableUserDefinedEnumDisplayNames",
    comment: "Updated UserDefinedEnums to have stable keyed display names",
    value: 13,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "AddedInlineFontFaceAssets",
    comment: "Added \"Inline\" option to UFontFace assets",
    value: 14,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "UPropertryForMeshSectionSerialize",
    comment: "Fix a serialization issue with static mesh FMeshSectionInfoMap FProperty",
    value: 15,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "FastWidgetTemplates",
    comment: "Adding a version bump for the new fast widget construction in case of problems.",
    value: 16,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "MaterialThumbnailRenderingChanges",
    comment: "Update material thumbnails to be more intelligent on default primitive shape for certain material types",
    value: 17,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "NewSlateClippingSystem",
    comment: "Introducing a new clipping system for Slate/UMG",
    value: 18,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "MovieSceneMetaDataSerialization",
    comment: "MovieScene Meta Data added as native Serialization",
    value: 19,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "GatheredTextEditorOnlyPackageLocId",
    comment: "Text gathered from properties now adds two variants: a version without the package localization ID (for use at runtime), and a version with it (which is editor-only)",
    value: 20,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "AddedAlwaysSignNumberFormattingOption",
    comment: "Added AlwaysSign to FNumberFormattingOptions",
    value: 21,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "AddedMaterialSharedInputs",
    comment: "Added additional objects that must be serialized as part of this new material feature",
    value: 22,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "AddedMorphTargetSectionIndices",
    comment: "Added morph target section indices",
    value: 23,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "SerializeInstancedStaticMeshRenderData",
    comment: "Serialize the instanced static mesh render data, to avoid building it at runtime",
    value: 24,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionNewSerialization_MovedToRelease",
    comment: "Change to MeshDescription serialization (moved to release)",
    value: 25,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionNewAttributeFormat",
    comment: "New format for mesh description attributes",
    value: 26,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "ChangeSceneCaptureRootComponent",
    comment: "Switch root component of SceneCapture actors from MeshComponent to SceneComponent",
    value: 27,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "StaticMeshDeprecatedRawMesh",
    comment: "StaticMesh serializes MeshDescription instead of RawMesh",
    value: 28,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionBulkDataGuid",
    comment: "MeshDescriptionBulkData contains a Guid used as a DDC key",
    value: 29,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionRemovedHoles",
    comment: "Change to MeshDescription serialization (removed FMeshPolygon::HoleContours)",
    value: 30,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "ChangedWidgetComponentWindowVisibilityDefault",
    comment: "Change to the WidgetCompoent WindowVisibilty default value",
    value: 31,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "CultureInvariantTextSerializationKeyStability",
    comment: "Avoid keying culture invariant display strings during serialization to avoid non-deterministic cooking issues",
    value: 32,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "ScrollBarThicknessChange",
    comment: "Change to UScrollBar and UScrollBox thickness property (removed implicit padding of 2, so thickness value must be incremented by 4).",
    value: 33,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "RemoveLandscapeHoleMaterial",
    comment: "Deprecated LandscapeHoleMaterial",
    value: 34,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionTriangles",
    comment: "MeshDescription defined by triangles instead of arbitrary polygons",
    value: 35,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "ComputeWeightedNormals",
    comment: "Add weighted area and angle when computing the normals",
    value: 36,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SkeletalMeshBuildRefactor",
    comment: "SkeletalMesh now can be rebuild in editor, no more need to re-import",
    value: 37,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SkeletalMeshMoveEditorSourceDataToPrivateAsset",
    comment: "Move all SkeletalMesh source data into a private uasset in the same package has the skeletalmesh",
    value: 38,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "NumberParsingOptionsNumberLimitsAndClamping",
    comment: "Parse text only if the number is inside the limits of its type",
    value: 39,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SkeletalMeshSourceDataSupport16bitOfMaterialNumber",
    comment: "Make sure we can have more then 255 material in the skeletal mesh source data",
    value: 40,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "GatheredTextPackageCacheFixes",
    comment: "Fixed several issues with the gathered text cache stored in package headers",
    value: 2,
    firstAppearance: "4.12.0",
    lastAppearance: "4.12.5",
  }),
];

export const FEditorObjectVersionGuid = new CustomVersionGuid<FEditorObjectVersion>({
  name: "FEditorObjectVersion",
  guid: FGuid.fromComponents(0xe4b068ed, 0xf49442e9, 0xa231da0b, 0x2e46bb41),
  details: FEditorObjectVersionDetails,
});
