// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FEnterpriseObjectVersion {
  // region Introduced with UE 4.20.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Conditional serialization of bulk (UDatasmithScene) and extra (UDatasmithStaticMeshCADImportData) data
  FixSerializationOfBulkAndExtraData = 1,
  // endregion

  // region Introduced with UE 4.21.0
  /// Extensibility updates for bookmarks
  BookmarkExtensibilityUpgrade = 2,
  /// Update FMediaFrameworkCaptureCameraViewportCameraOutputInfo with LazyObjectPtr
  MediaFrameworkUserDataLazyObject = 3,
  /// Live Live timecode synchronization updates
  LiveLinkTimeSynchronization = 4,
  // endregion

  // region Introduced with UE 4.22.0
  /// Deprecate MediaMode and MediaPort for from MediaConfiguration
  AjaMediaConfiguration = 5,
  // endregion

  // region Introduced with UE 4.23.0
  /// Addition of pointer to UDatasmithDataPrepRecipe
  HasUDataprepRecipe = 6,
  // endregion

  // region Introduced with UE 4.24.0
  /// Addition of UDatatprepAssetInterface and UDatatprepAssetInstance
  HasUDatatprepAssetInterface = 7,
  /// MeshDescriptionBulkData contains a bGuidIsHash so we can benefit from DDC caching.
  MeshDescriptionBulkDataGuidIsHash = 8,
  // endregion

  // region Introduced with UE 4.25.0
  /// Splitting controller associated with a livelink component for each LiveLinkRole class hierarchy
  LiveLinkControllerSplitPerRole = 9,
  /// Change CoreTechParametricSurface serialization to be more efficient
  CoreTechParametricSurfaceOptim = 10,
  // endregion

  // region Introduced with UE 5.6.0
  /// Replacement of UDatasmithParametricSurfaceData by UParametricSurfaceData
  AddedParametricSurfaceData = 11,
  // endregion

  // region Introduced with UE 4.22.0
  /// Addition of pointer to UDatasmithDataPrepRecipe
  HasUDatasmithDataPrepRecipe = 6,
  // endregion
}

export const FEnterpriseObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "FixSerializationOfBulkAndExtraData",
    comment: "Conditional serialization of bulk (UDatasmithScene) and extra (UDatasmithStaticMeshCADImportData) data ",
    value: 1,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "BookmarkExtensibilityUpgrade",
    comment: "Extensibility updates for bookmarks",
    value: 2,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "MediaFrameworkUserDataLazyObject",
    comment: "Update FMediaFrameworkCaptureCameraViewportCameraOutputInfo with LazyObjectPtr",
    value: 3,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "LiveLinkTimeSynchronization",
    comment: "Live Live timecode synchronization updates",
    value: 4,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "AjaMediaConfiguration",
    comment: "Deprecate MediaMode and MediaPort for from MediaConfiguration",
    value: 5,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "HasUDataprepRecipe",
    comment: "Addition of pointer to UDatasmithDataPrepRecipe ",
    value: 6,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "HasUDatatprepAssetInterface",
    comment: "Addition of UDatatprepAssetInterface and UDatatprepAssetInstance",
    value: 7,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionBulkDataGuidIsHash",
    comment: "MeshDescriptionBulkData contains a bGuidIsHash so we can benefit from DDC caching.",
    value: 8,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "LiveLinkControllerSplitPerRole",
    comment: "Splitting controller associated with a livelink component for each LiveLinkRole class hierarchy",
    value: 9,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "CoreTechParametricSurfaceOptim",
    comment: "Change CoreTechParametricSurface serialization to be more efficient",
    value: 10,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddedParametricSurfaceData",
    comment: "Replacement of UDatasmithParametricSurfaceData by UParametricSurfaceData",
    value: 11,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "HasUDatasmithDataPrepRecipe",
    comment: "Addition of pointer to UDatasmithDataPrepRecipe ",
    value: 6,
    firstAppearance: "4.22.0",
    lastAppearance: "4.22.3",
  }),
];

export const FEnterpriseObjectVersionGuid = new CustomVersionGuid<FEnterpriseObjectVersion>({
  friendlyName: "Dev-Enterprise",
  guid: FGuid.fromComponents(0x9dffbcd6, 0x494f0158, 0xe2211282, 0x3c92a888),
  details: FEnterpriseObjectVersionDetails,
});
