// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FExternalPhysicsCustomObjectVersion {
  // region Introduced with UE 4.24.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Format change, Removed Convex Hulls From Triangle Mesh Implicit Object
  RemovedConvexHullsFromTriangleMeshImplicitObject = 1,
  /// Add serialization for particle bounds
  SerializeParticleBounds = 2,
  /// Add BV serialization for evolution
  SerializeEvolutionBV = 3,
  /// Allow evolution to swap acceleration structures
  SerializeEvolutionGenericAcceleration = 4,
  /// Global elements have bounds so we can skip them
  GlobalElementsHaveBounds = 5,
  /// SpatialIdx serialized
  SpatialIdxSerialized = 6,
  /// Save out heightfield data
  HeightfieldData = 7,
  /// Save out multiple acceleration structures
  SerializeMultiStructures = 8,
  // endregion

  // region Introduced with UE 4.25.0
  /// Add kinematic targets to TKinematicGeometryParticles
  KinematicTargets = 9,
  /// Allow trimeshes to serialize their acceleration structure
  TrimeshSerializesBV = 10,
  /// Serialize broadphase type
  SerializeBroadphaseType = 11,
  /// Allow scaled geometry to be a concrete type
  ScaledGeometryIsConcrete = 12,
  /// Trimeshes serialize AABBTree
  TrimeshSerializesAABBTree = 13,
  /// Adds Serialization of HashResult, and separates delete/update TAccelerationStructureHandle in FPendingSpatialData
  SerializeHashResult = 14,
  /// Only serialize internal acceleration structure queue and acceleration structure. No external/Async queues.
  FlushEvolutionInternalAccelerationQueue = 15,
  /// Serialize world space bounds of TPerShapeData
  SerializeShapeWorldSpaceBounds = 16,
  /// Add an SOA which contains particles with full dynamic data but which are in the kinematic object state.
  AddDynamicKinematicSOA = 17,
  /// Added material manager to Chaos
  AddedMaterialManager = 18,
  /// Added material indices to trimesh collision data
  AddTrimeshMaterialIndices = 19,
  /// Add center of mass and volume cached calculations to TConvex
  AddConvexCenterOfMassAndVolume = 20,
  /// Add mass transform data to kinematic particle
  KinematicCentersOfMass = 21,
  /// Added ability to remove shapes from collision resolution (will not construct constraints when one or more shapes removed)
  AddShapeCollisionDisable = 22,
  /// Heightfield cell bounds are implicit
  HeightfieldImplicitBounds = 23,
  /// Add damping to rigid particles
  AddDampingToRigids = 24,
  /// Replace TBox with TAABB in many places
  TBoxReplacedWithTAABB = 25,
  /// Serialize bSimulate on PerShapeData
  SerializePerShapeDataSimulateFlag = 26,
  /// Serialize whether or not an AABBTree is immutable
  ImmutableAABBTree = 27,
  /// Trimeshes can now use small indices
  TrimeshCanUseSmallIndices = 28,
  /// Union objects can avoid allocating a full hierarchy
  UnionObjectsCanAvoidHierarchy = 29,
  /// Capsules no longer have a union inside them or stored aabbs
  CapsulesNoUnionOrAABBs = 30,
  /// Convexes use concrete planes
  ConvexUsesTPlaneConcrete = 31,
  /// Heightfield uses uint16 heights directly
  HeightfieldUsesHeightsDirectly = 32,
  /// TriangleMesh has map from internal face indices to external.
  TriangleMeshHasFaceIndexMap = 33,
  /// Acceleration structures use unique payload idx
  UniquePayloadIdx = 34,
  /// Added serialization for the collision type in the shape
  SerializeCollisionTraceType = 35,
  /// Force rebuild of indices in BodySetup
  ForceRebuildBodySetupIndices = 36,
  /// Added serialization for the physics material sleep counter threshold
  PhysicsMaterialSleepCounterThreshold = 37,
  // endregion

  // region Introduced with UE 4.26.0
  /// Added ability to remove shapes from sim and/or query separately
  AddShapeSimAndQueryCollisionEnabled = 38,
  /// Remove extra representations of per shape sim and query enabled flags
  RemoveShapeSimAndQueryDuplicateRepresentations = 39,
  /// Removed unused full bounds from AABBTree
  RemovedAABBTreeFullBounds = 40,
  // endregion

  // region Introduced with UE 4.27.0
  /// Added one-way interaction flag
  AddOneWayInteraction = 41,
  // endregion
}

export const FExternalPhysicsCustomObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "RemovedConvexHullsFromTriangleMeshImplicitObject",
    comment: "Format change, Removed Convex Hulls From Triangle Mesh Implicit Object",
    value: 1,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SerializeParticleBounds",
    comment: "Add serialization for particle bounds",
    value: 2,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SerializeEvolutionBV",
    comment: "Add BV serialization for evolution",
    value: 3,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SerializeEvolutionGenericAcceleration",
    comment: "Allow evolution to swap acceleration structures",
    value: 4,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "GlobalElementsHaveBounds",
    comment: "Global elements have bounds so we can skip them",
    value: 5,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SpatialIdxSerialized",
    comment: "SpatialIdx serialized",
    value: 6,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "HeightfieldData",
    comment: "Save out heightfield data",
    value: 7,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "SerializeMultiStructures",
    comment: "Save out multiple acceleration structures",
    value: 8,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "KinematicTargets",
    comment: "Add kinematic targets to TKinematicGeometryParticles",
    value: 9,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "TrimeshSerializesBV",
    comment: "Allow trimeshes to serialize their acceleration structure",
    value: 10,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializeBroadphaseType",
    comment: "Serialize broadphase type",
    value: 11,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "ScaledGeometryIsConcrete",
    comment: "Allow scaled geometry to be a concrete type",
    value: 12,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "TrimeshSerializesAABBTree",
    comment: "Trimeshes serialize AABBTree",
    value: 13,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializeHashResult",
    comment:
      "Adds Serialization of HashResult, and separates delete/update TAccelerationStructureHandle in FPendingSpatialData",
    value: 14,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "FlushEvolutionInternalAccelerationQueue",
    comment:
      "Only serialize internal acceleration structure queue and acceleration structure. No external/Async queues.",
    value: 15,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializeShapeWorldSpaceBounds",
    comment: "Serialize world space bounds of TPerShapeData",
    value: 16,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddDynamicKinematicSOA",
    comment: "Add an SOA which contains particles with full dynamic data but which are in the kinematic object state.",
    value: 17,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddedMaterialManager",
    comment: "Added material manager to Chaos",
    value: 18,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddTrimeshMaterialIndices",
    comment: "Added material indices to trimesh collision data",
    value: 19,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddConvexCenterOfMassAndVolume",
    comment: "Add center of mass and volume cached calculations to TConvex",
    value: 20,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "KinematicCentersOfMass",
    comment: "Add mass transform data to kinematic particle",
    value: 21,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddShapeCollisionDisable",
    comment:
      "Added ability to remove shapes from collision resolution (will not construct constraints when one or more shapes removed)",
    value: 22,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "HeightfieldImplicitBounds",
    comment: "Heightfield cell bounds are implicit",
    value: 23,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddDampingToRigids",
    comment: "Add damping to rigid particles",
    value: 24,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "TBoxReplacedWithTAABB",
    comment: "Replace TBox with TAABB in many places",
    value: 25,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializePerShapeDataSimulateFlag",
    comment: "Serialize bSimulate on PerShapeData",
    value: 26,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "ImmutableAABBTree",
    comment: "Serialize whether or not an AABBTree is immutable",
    value: 27,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "TrimeshCanUseSmallIndices",
    comment: "Trimeshes can now use small indices",
    value: 28,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "UnionObjectsCanAvoidHierarchy",
    comment: "Union objects can avoid allocating a full hierarchy",
    value: 29,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "CapsulesNoUnionOrAABBs",
    comment: "Capsules no longer have a union inside them or stored aabbs",
    value: 30,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "ConvexUsesTPlaneConcrete",
    comment: "Convexes use concrete planes",
    value: 31,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "HeightfieldUsesHeightsDirectly",
    comment: "Heightfield uses uint16 heights directly",
    value: 32,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "TriangleMeshHasFaceIndexMap",
    comment: "TriangleMesh has map from internal face indices to external.",
    value: 33,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "UniquePayloadIdx",
    comment: "Acceleration structures use unique payload idx",
    value: 34,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SerializeCollisionTraceType",
    comment: "Added serialization for the collision type in the shape",
    value: 35,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "ForceRebuildBodySetupIndices",
    comment: "Force rebuild of indices in BodySetup",
    value: 36,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "PhysicsMaterialSleepCounterThreshold",
    comment: "Added serialization for the physics material sleep counter threshold",
    value: 37,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AddShapeSimAndQueryCollisionEnabled",
    comment: "Added ability to remove shapes from sim and/or query separately",
    value: 38,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "RemoveShapeSimAndQueryDuplicateRepresentations",
    comment: "Remove extra representations of per shape sim and query enabled flags",
    value: 39,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "RemovedAABBTreeFullBounds",
    comment: "Removed unused full bounds from AABBTree",
    value: 40,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "AddOneWayInteraction",
    comment: "Added one-way interaction flag",
    value: 41,
    firstAppearance: "4.27.0",
  }),
];
