// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FFoliageCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Converted to use HierarchicalInstancedStaticMeshComponent
  FoliageUsingHierarchicalISMC = 1,
  /// Changed Component to not RF_Transactional
  HierarchicalISMCNonTransactional = 2,
  /// Added FoliageTypeUpdateGuid
  AddedFoliageTypeUpdateGuid = 3,
  /// Use a GUID to determine whic procedural actor spawned us
  ProceduralGuid = 4,
  /// Support for cross-level bases
  CrossLevelBase = 5,
  /// FoliageType for details customization
  FoliageTypeCustomization = 6,
  /// FoliageType for details customization continued
  FoliageTypeCustomizationScaling = 7,
  /// FoliageType procedural scale and shade settings updated
  FoliageTypeProceduralScaleAndShade = 8,
  /// Added FoliageHISMC and blueprint support
  FoliageHISMCBlueprints = 9,
  /// Added Mobility setting to UFoliageType
  AddedMobility = 10,
  /// Make sure that foliage has FoliageHISMC class
  FoliageUsingFoliageISMC = 11,
  /// Foliage Actor Support
  FoliageActorSupport = 12,
  /// Foliage Actor (No weak ptr)
  FoliageActorSupportNoWeakPtr = 13,
  /// Foliage Instances are now always saved local to Level
  FoliageRepairInstancesWithLevelTransform = 14,
  /// Supports discarding foliage types on load independently from density scaling
  FoliageDiscardOnLoad = 15,
  // endregion
}

export const FFoliageCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageUsingHierarchicalISMC",
    comment: "Converted to use HierarchicalInstancedStaticMeshComponent",
    value: 1,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "HierarchicalISMCNonTransactional",
    comment: "Changed Component to not RF_Transactional",
    value: 2,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "AddedFoliageTypeUpdateGuid",
    comment: "Added FoliageTypeUpdateGuid",
    value: 3,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ProceduralGuid",
    comment: "Use a GUID to determine whic procedural actor spawned us",
    value: 4,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "CrossLevelBase",
    comment: "Support for cross-level bases ",
    value: 5,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageTypeCustomization",
    comment: "FoliageType for details customization",
    value: 6,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageTypeCustomizationScaling",
    comment: "FoliageType for details customization continued",
    value: 7,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageTypeProceduralScaleAndShade",
    comment: "FoliageType procedural scale and shade settings updated",
    value: 8,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageHISMCBlueprints",
    comment: "Added FoliageHISMC and blueprint support",
    value: 9,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "AddedMobility",
    comment: "Added Mobility setting to UFoliageType",
    value: 10,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageUsingFoliageISMC",
    comment: "Make sure that foliage has FoliageHISMC class",
    value: 11,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageActorSupport",
    comment: "Foliage Actor Support",
    value: 12,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageActorSupportNoWeakPtr",
    comment: "Foliage Actor (No weak ptr)",
    value: 13,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageRepairInstancesWithLevelTransform",
    comment: "Foliage Instances are now always saved local to Level",
    value: 14,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "FoliageDiscardOnLoad",
    comment:
      "Supports discarding foliage types on load independently from density scaling",
    value: 15,
    firstAppearance: "4.27.0",
  }),
];
