// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FFortniteMainInterchangePipelineObjectVersion {
  // region Introduced with UE 5.6.0
  InitialVersion = 0,
  /// Interchange Move generic animation pipeline property bAddCurveMetadataToSkeleton to the generic shared skeletalmesh and animation pipeline
  InterchangeAddCurveMetadataToSkeletonPropertyMove = 1,
  // endregion
}

export const FFortniteMainInterchangePipelineObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "InitialVersion",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "InterchangeAddCurveMetadataToSkeletonPropertyMove",
    comment:
      "Interchange Move generic animation pipeline property bAddCurveMetadataToSkeleton to the generic shared skeletalmesh and animation pipeline",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FFortniteMainInterchangePipelineObjectVersionGuid =
  new CustomVersionGuid<FFortniteMainInterchangePipelineObjectVersion>({
    friendlyName: "FN-Main-InterchangePipeline",
    guid: FGuid.fromComponents(0xb69d2e47, 0xe2a84003, 0xbf7718a4, 0x92c4d899),
    details: FFortniteMainInterchangePipelineObjectVersionDetails,
  });
