// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FFortniteMainBranchObjectVersion {
  // region Introduced with UE 4.20.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// World composition tile offset changed from 2d to 3d
  WorldCompositionTile3DOffset = 1,
  /// Minor material serialization optimization
  MaterialInstanceSerializeOptimization_ShaderFName = 2,
  /// Refactored cull distances to account for HLOD, explicit override and globals in priority
  CullDistanceRefactor_RemovedDefaultDistance = 3,
  CullDistanceRefactor_NeverCullHLODsByDefault = 4,
  CullDistanceRefactor_NeverCullALODActorsByDefault = 5,
  /// Support to remove morphtarget generated by bRemapMorphtarget
  SaveGeneratedMorphTargetByEngine = 6,
  /// Convert reduction setting options
  ConvertReductionSettingOptions = 7,
  /// Serialize the type of blending used for landscape layer weight static params
  StaticParameterTerrainLayerWeightBlendType = 8,
  /// Fix up None Named animation curve names,
  FixUpNoneNameAnimationCurves = 9,
  /// Ensure ActiveBoneIndices to have parents even not skinned for old assets
  EnsureActiveBoneIndicesToContainParents = 10,
  /// Serialize the instanced static mesh render data, to avoid building it at runtime
  SerializeInstancedStaticMeshRenderData = 11,
  /// Cache material quality node usage
  CachedMaterialQualityNodeUsage = 12,
  // endregion

  // region Introduced with UE 4.21.0
  /// Font outlines no longer apply to drop shadows for new objects but we maintain the opposite way for backwards compat
  FontOutlineDropShadowFixup = 13,
  /// New skeletal mesh import workflow (Geometry only or animation only re-import )
  NewSkeletalMeshImporterWorkflow = 14,
  /// Migrate data from previous data structure to new one to support materials per LOD on the Landscape
  NewLandscapeMaterialPerLOD = 15,
  /// New Pose Asset data type
  RemoveUnnecessaryTracksFromPose = 16,
  /// Migrate Foliage TLazyObjectPtr to TSoftObjectPtr
  FoliageLazyObjPtrToSoftObjPtr = 17,
  // endregion

  // region Introduced with UE 4.22.0
  /// This code tied to this version was reverted and redone at a later date
  REVERTED_StoreTimelineNamesInTemplate = 18,
  /// Added BakePoseOverride for LOD setting
  AddBakePoseOverrideForSkeletalMeshReductionSetting = 19,
  /// TimelineTemplates store their derived names instead of dynamically generating
  StoreTimelineNamesInTemplate = 20,
  /// Avoid duplicating widget animations to save space.
  WidgetStopDuplicatingAnimations = 21,
  /// Allow reducing of the base LOD, we need to store some imported model data so we can reduce again from the same data.
  AllowSkeletalMeshToReduceTheBaseLOD = 22,
  /// Curve Table size reduction
  ShrinkCurveTableSize = 23,
  /// Widgets upgraded with WidgetStopDuplicatingAnimations, may not correctly default-to-self for the widget parameter.
  WidgetAnimationDefaultToSelfFail = 24,
  /// HUDWidgets now require an element tag
  FortHUDElementNowRequiresTag = 25,
  // endregion

  // region Introduced with UE 4.23.0
  /// Animation saved as bulk data when cooked
  FortMappedCookedAnimation = 26,
  /// Support Virtual Bone in Retarget Manager
  SupportVirtualBoneInRetargeting = 27,
  // endregion

  // region Introduced with UE 4.24.0
  /// Fixup bad defaults in water metadata
  FixUpWaterMetadata = 28,
  /// Move the location of water metadata
  MoveWaterMetadataToActor = 29,
  /// Replaced lake collision component
  ReplaceLakeCollision = 30,
  /// Anim layer node names are now conformed by Guid
  AnimLayerGuidConformation = 31,
  // endregion

  // region Introduced with UE 4.26.0
  /// Ocean collision component has become dynamic
  MakeOceanCollisionTransient = 32,
  /// FFieldPath will serialize the owner struct reference and only a short path to its property
  FFieldPathOwnerSerialization = 33,
  /// Simplified WaterBody post process material handling
  FixUpUnderwaterPostProcessMaterial = 34,
  /// A single water exclusion volume can now exclude N water bodies
  SupportMultipleWaterBodiesPerExclusionVolume = 35,
  /// Serialize rigvm operators one by one instead of the full byte code array to ensure determinism
  RigVMByteCodeDeterminism = 36,
  /// Serialize the physical materials generated by the render material
  LandscapePhysicalMaterialRenderData = 37,
  /// RuntimeVirtualTextureVolume fix transforms
  FixupRuntimeVirtualTextureVolume = 38,
  /// Retrieve water body collision components that were lost in cooked builds
  FixUpRiverCollisionComponents = 39,
  /// Fix duplicate spline mesh components on rivers
  FixDuplicateRiverSplineMeshCollisionComponents = 40,
  /// Indicates level has stable actor guids
  ContainsStableActorGUIDs = 41,
  /// Levelset Serialization support for BodySetup.
  LevelsetSerializationSupportForBodySetup = 42,
  /// Moving Chaos solver properties to allow them to exist in the project physics settings
  ChaosSolverPropertiesMoved = 43,
  // endregion

  // region Introduced with UE 4.27.0
  /// Moving some UFortGameFeatureData properties and behaviors into the UGameFeatureAction pattern
  GameFeatureData_MovedComponentListAndCheats = 44,
  /// Add centrifugal forces for cloth
  ChaosClothAddfictitiousforces = 45,
  /// (Merged from //UE4/Main)
  ChaosConvexVariableStructureDataAndVerticesArray = 46,
  /// Remove the WaterVelocityHeightTexture dependency on MPC_Landscape and LandscapeWaterIndo
  RemoveLandscapeWaterInfo = 47,
  // endregion

  // region Introduced with UE 5.0.0
  /// Added the weighted value property type to store the cloths weight maps' low/high ranges
  ChaosClothAddWeightedValue = 48,
  /// Added the Long Range Attachment stiffness weight map
  ChaosClothAddTetherStiffnessWeightMap = 49,
  /// Fix corrupted LOD transition maps
  ChaosClothFixLODTransitionMaps = 50,
  /// Enable a few more weight maps to better art direct the cloth simulation
  ChaosClothAddTetherScaleAndDragLiftWeightMaps = 51,
  /// Enable material (edge, bending, and area stiffness) weight maps
  ChaosClothAddMaterialWeightMaps = 52,
  /// Added bShowCurve for movie scene float channel serialization
  SerializeFloatChannelShowCurve = 53,
  /// Minimize slack waste by using a single array for grass data
  LandscapeGrassSingleArray = 54,
  /// Add loop counters to sequencer's compiled sub-sequence data
  AddedSubSequenceEntryWarpCounter = 55,
  /// Water plugin is now component-based rather than actor based
  WaterBodyComponentRefactor = 56,
  /// Cooked BPGC storing editor-only asset tags
  BPGCCookedEditorTags = 57,
  /// Terrain layer weights are no longer considered material parameters
  TerrainLayerWeightsAreNotParameters = 58,
  /// true for nodes predating this change.
  GravityOverrideDefinedInWorldSpace = 59,
  // endregion

  // region Introduced with UE 5.1.0
  /// Anim Dynamics Node Physics parameters for each body in a chain are now stored in an array and can be edited.
  AnimDynamicsEditableChainParameters = 60,
  /// Decoupled the generation of the water texture from the Water Brush and the landscape
  WaterZonesRefactor = 61,
  /// Add faster damping calculations to the cloth simulation and rename previous Damping parameter to LocalDamping.
  ChaosClothFasterDamping = 62,
  /// Migrated function handlers to the CDO/archetype data
  MigratedFunctionHandlersToDefaults = 63,
  /// Storing inertia tensor as vec3 instead of matrix.
  ChaosInertiaConvertedToVec3 = 64,
  /// Migrated event definitions to the CDO/archetype data
  MigratedEventDefinitionToDefaults = 65,
  /// Serialize LevelInstanceActorGuid on new ILevelInstanceInterface implementation
  LevelInstanceActorGuidSerialize = 66,
  /// Single-frame/key AnimDataModel patch-up
  SingleFrameAndKeyAnimModel = 67,
  /// Remapped bEvaluateWorldPositionOffset to bEvaluateWorldPositionOffsetInRayTracing
  RemappedEvaluateWorldPositionOffsetInRayTracing = 68,
  /// Water body collision settings are now those of the base UPrimitiveComponent, rather than duplicated in UWaterBodyComponent
  WaterBodyComponentCollisionSettingsRefactor = 69,
  /// if a widget exposes its named slot to everyone (even if it has content) which by default they wont any longer.
  WidgetInheritedNamedSlots = 70,
  /// Added water HLOD material
  WaterHLODSupportAdded = 71,
  /// Moved parameters affecting Skeleton pose rendering from the PoseWatch class to the PoseWatchPoseElement class.
  PoseWatchMigrateSkeletonDrawParametersToPoseElement = 72,
  /// Reset default value for Water exclusion volumes to make them more intuitive and support the "it just works" philosophy.
  WaterExclusionVolumeExcludeAllDefault = 73,
  /// Added water non-tessellated LOD
  WaterNontessellatedLODSupportAdded = 74,
  /// Added FHierarchicalSimplification::SimplificationMethod
  HierarchicalSimplificationMethodEnumAdded = 75,
  /// Changed how world partition streaming cells are named
  WorldPartitionStreamingCellsNamingShortened = 76,
  /// Serialize ContentBundleGuid in WorldPartitionActorDesc
  WorldPartitionActorDescSerializeContentBundleGuid = 77,
  /// Serialize IsActorRuntimeOnly in WorldPartitionActorDesc
  WorldPartitionActorDescSerializeActorIsRuntimeOnly = 78,
  /// Add Nanite Material Override option to materials and material instances.
  NaniteMaterialOverride = 79,
  /// Serialize HLOD stats in HLODActorDesc
  WorldPartitionHLODActorDescSerializeStats = 80,
  // endregion

  // region Introduced with UE 5.2.0
  /// WorldPartitionStreamingSourceComponent property deprecation
  WorldPartitionStreamingSourceComponentTargetDeprecation = 81,
  /// Fixed localization gathering for external actor packages
  FixedLocalizationGatherForExternalActorPackage = 82,
  /// Change HLODActors to RuntimeCells mapping to use a GUID instead of the cell name
  WorldPartitionHLODActorUseSourceCellGuid = 83,
  // endregion

  // region Introduced with UE 5.3.0
  /// Add an attribute to geometry collection to track internal faces, rather than relying on material ID numbering
  ChaosGeometryCollectionInternalFacesAttribute = 84,
  /// Dynamic cast nodes use an enumerated pure node state to include a value for the default setting
  DynamicCastNodesUsePureStateEnum = 85,
  /// Add FWorldPartitionActorFilter to FLevelInstanceActorDesc/FDataLayerInstanceDesc
  WorldPartitionActorFilter = 86,
  /// Change the non-spatialized radius to blend to a pure 2D spatialized sound vs omnidirectional
  AudioAttenuationNonSpatializedRadiusBlend = 87,
  /// Serialize actor class descriptors
  WorldPartitionActorClassDescSerialize = 88,
  /// FActorContainerID is now an FGuid instead of a uint64
  WorldPartitionFActorContainerIDu64ToGuid = 89,
  /// FDataLayerInstanceDesc support for private data layers
  WorldPartitionPrivateDataLayers = 90,
  /// Reduce size and improve behaviour of Chaos::FImplicitObjectUnion
  ChaosImplicitObjectUnionBVHRefactor = 91,
  /// FLevelInstanceActorDesc DeltaSerialize Filter
  LevelInstanceActorDescDeltaSerializeFilter = 92,
  /// Fix the Nanite landscape mesh non-deterministic DDC keys
  FixNaniteLandscapeMeshDDCKey = 93,
  /// Change how connection graphs are stored on Geometry Collections to an edge-array representation
  ChaosGeometryCollectionConnectionEdgeGroup = 94,
  /// Moved the water info mesh data and static water body meshes into new static mesh components for water bodies.
  WaterBodyStaticMeshComponents = 95,
  /// Serialize invalid bounds in world partition actor descriptors
  WorldPartitionActorDescSerializeInvalidBounds = 96,
  /// Upgrade Navigation Links to use 64 bits for the ID
  NavigationLinkID32To64 = 97,
  /// Serialize editor only references in world partition actor descriptors
  WorldPartitionActorDescSerializeEditorOnlyReferences = 98,
  /// Add support for soft object paths in actor descriptors
  WorldPartitionActorDescSerializeSoftObjectPathSupport = 99,
  /// Don't serialize class descriptor GUIDs
  WorldPartitionClasDescGuidTransient = 100,
  /// Serialize ActorDesc bIsMainWorldOnly
  WorldPartitionActorDescIsMainWorldOnly = 101,
  /// FWorldPartitionActorFilter go back to FString serialize of AssetPaths to avoid FArchiveReplaceOrClearExternalReferences clearing CDO references on BP Compile
  WorldPartitionActorFilterStringAssetPath = 102,
  /// Add FPackedLevelActorDesc for APackedLevelActor and support for APackedLevelActor Filters
  PackedLevelActorDesc = 103,
  /// Add customizable values for several UWorldPartitionRuntimeSpatialHash cvars
  WorldPartitionRuntimeSpatialHashCVarOverrides = 104,
  /// WorldPartition HLOD now contains a source actors object
  WorldPartitionHLODSourceActorsRefactor = 105,
  WaterBodyStaticMeshRename = 106,
  /// Geometry Collection now by-default converts vertex colors to sRGB when creating render data
  GeometryCollectionConvertVertexColorToSRGB = 107,
  /// Water bodies before this version need to update their water zone on load since they won't have been serialized yet.
  WaterOwningZonePointerFixup = 108,
  /// Set flags on water static meshes to duplicate transient to avoid underlying static mesh duplication issue
  WaterBodyStaticMeshDuplicateTransient = 109,
  /// Update paths to use the SkeletalClass
  MVVMConvertPropertyPathToSkeletalClass = 110,
  /// Fixup all flags/outering on static meshes on water bodies by rebuilding them completely
  WaterBodyStaticMeshFixup = 111,
  // endregion

  // region Introduced with UE 5.4.0
  /// Binding extensions for anim graph nodes
  AnimGraphNodeBindingExtensions = 112,
  /// Function data stores a map from work to debug operands
  RigVMSaveDebugMapInGraphFunctionData = 113,
  /// Fix missing binding extensions for some anim graph nodes
  FixMissingAnimGraphNodeBindingExtensions = 114,
  /// EditableWhenInherited: Skip custom serialization on non Archetypes
  ISMComponentEditableWhenInheritedSkipSerialization = 115,
  /// GrassTypes are now per-component, rather than per-landscape proxy :
  LandscapeSupportPerComponentGrassTypes = 116,
  /// World partition actor data layers activation logic operator support defaults for old maps
  WorldPartitionDataLayersLogicOperatorAdded = 117,
  /// Started sorting Possessables, Spawnables, and MovieSceneBindings for better search performance.
  MovieSceneSortedBindings = 118,
  /// Remove the UAnimCurveCompressionCodec::InstanceGuid which causes cook determinism issues
  RemoveAnimCurveCompressionCodecInstanceGuid = 119,
  /// Serialize the source HLOD Layer for HLOD actor descriptors.
  WorldPartitionHLODActorDescSerializeSourceHLODLayer = 120,
  /// Serialize custom editor bounds for HLOD actor descriptors.
  WorldPartitionHLODActorDescSerializeEditorBounds = 121,
  /// Changed default Local Exposure Contrast from 1.0 to 0.8 (reverted)
  LocalExposureDefaultChangeFrom1_Reverted = 122,
  /// Added support of external packaging of Data Layer Instances
  AddDataLayerInstanceExternalPackage = 123,
  /// Update paths to keep a flag if they are the widget BP
  MVVMPropertyPathSelf = 124,
  /// Enabled ObjectPtr property serialization for Dataflow nodes
  AddDataflowObjectSerialization = 125,
  /// Add anim notify rate scaling, defaults to on for new content, off for old content
  AnimNotifyAddRateScale = 126,
  /// Fix tangents for non-uniform build scales, and add a flag to optionally match the previous (incorrect) tangents
  FixedTangentTransformForNonuniformBuildScale = 127,
  /// AnimNode Layers will now start in a Shared Group, instead of being each one on a different group at runtime
  AnimNodeRootDefaultGroupChange = 128,
  /// Move AnimNext graphs to sub-entries of assets
  AnimNextMoveGraphsToEntries = 129,
  /// Removed debug information containing compressed data author, time etc. from animation DDC data as it introduces indeterminism
  AnimationSequenceCompressedDataRemoveDebugData = 130,
  /// Changes to Orthographic Camera default settings
  OrthographicCameraDefaultSettings = 131,
  /// Added settings to Landscape HLODs
  LandscapeAddedHLODSettings = 132,
  /// Skeletal Mesh uses Mesh Description to store mesh bulk data.
  MeshDescriptionForSkeletalMesh = 133,
  /// Skeletal Mesh optionally cooks half edge data per lod
  SkeletalHalfEdgeData = 134,
  // endregion

  // region Introduced with UE 5.5.0
  /// Combine graph contexts for AnimNext graphs
  AnimNextCombineGraphContexts = 135,
  /// Combine parameter blocks and graphs
  AnimNextCombineParameterBlocksAndGraphs = 136,
  /// Move workspaces to a seperate plugin
  AnimNextMoveWorkspaces = 137,
  /// Level Instance Property overrides
  LevelInstancePropertyOverrides = 138,
  /// Added FVolumetricLightMapGridDesc in MapBuildData
  VolumetricLightMapGridDescSupport = 139,
  /// Introduce new structure for customizing the landscape edit layer behavior
  IntroduceLandscapeEditLayerClass = 140,
  /// Change workspaces to store asset references as external objects
  AnimNextWorkspaceEntryConversion = 141,
  /// Add support for anytype in dataflow
  DataflowAnyTypeSupport = 142,
  /// Adding a new flag in RBAN Solver Setting to be able to use manifolds
  PhysicsAssetUseManifoldFlags = 143,
  /// Added support for to record sim and query data of Shape Instance data in CVD
  SimAndQueryDataSupportInChaosVisualDebugger = 144,
  /// Add the imported asset dependencies to the Cloth Asset USD Import node
  ChaosClothAssetUSDImportNodeAddAssetDependencies = 145,
  /// Changed HitLighting to HitLightingForReflections, and HitLighting now means hit lighting for entire Lumen
  LumenRayLightingModeOverrideEnum = 146,
  /// PCGPartitionActorDesc
  PCGPartitionActorDesc = 147,
  /// Target layers are now defined in the Landscape actor and not continuously synced from the assigned material.
  LandscapeTargetLayersInLandscapeActor = 148,
  /// Fix to get full name of templated type ( Tarray > TArray<Float> for example )
  DataflowTemplatedTypeFix = 149,
  /// Changes for LevelInstance support in StaticLighting
  LevelInstanceStaticLightingSupport = 150,
  /// PCGGridDescriptor
  PCGGridDescriptor = 151,
  /// AnimNext graphs now have public/private state
  AnimNextGraphAccessSpecifiers = 152,
  /// Added a more stable pixel depth offset mode.
  MaterialPixelDepthOffsetMode = 153,
  /// Added hideable pins to dataflow
  DataflowHideablePins = 154,
  /// Added multiple section import to the cloth asset skeletal mesh import node
  ClothAssetSkeletalMeshMultiSectionImport = 155,
  /// Serialize EditorBounds in WorldPartitionActorDesc
  WorldPartitionActorDescSerializeEditorBounds = 156,
  /// Fixup for the data that has been damaged by LandscapeTargetLayersInLandscapeActor (loss of landscape layer info object assignments)
  FixupLandscapeTargetLayersInLandscapeActor = 157,
  /// Allow custom import of morph target
  MorphTargetCustomImport = 158,
  /// Fix chaos cloth buckling stiffness parameter bug
  ChaosClothAllowZeroBucklingStiffness = 159,
  /// LevelSequenceUpgradeDynamicBindings was removed but was intended for this position. Putting this here to make sure versioning of subsequent assets remains the same
  LevelSequenceUpgradeDynamicBindings_NoOp = 160,
  /// AddToFrontend GFA now defaults to unload plugin on exit frontend
  GameFeatureDataActionAddToFrontendDefaultToUnload = 161,
  /// Upgraded movie scene 'dynamic bindings' to use the new Custom Bindings system
  LevelSequenceUpgradeDynamicBindings = 162,
  /// Changed the precision for the stored rotation on kinematic targets to match the precision used in particles
  ChaosStoreKinematicTargetRotationAsSinglePrecision = 163,
  /// PCG changes around the ApplyOnActor node, where we collapsed the TargetActor to the input pin.
  PCGApplyOnActorNodeMoveTargetActorEdgeToInput = 164,
  /// PlayingStateTracker type to improve replication reliability
  TimelinePlayingStateTrackerDeprecation = 165,
  /// Enable SkipOnlyEditorOnly style cooking of UStaticMeshComponent::MeshPaintTexture
  MeshPaintTextureUsesEditorOnly = 166,
  /// Fixup and synchronize some landscape properties that have moved to the property sharing/overriding system :
  LandscapeBodyInstanceAsSharedProperty = 167,
  /// Multiple changes to AnimNext modules, variables etc.
  AnimNextModuleRefactor = 168,
  /// Subsurface profile now has a guid to be able to select one of many in a Substrate material.
  SubsurfaceProfileGuid = 169,
  /// Added support for to record the new solver iteration settings in CVD
  SolverIterationsDataSupportInChaosVisualDebugger = 170,
  // endregion

  // region Introduced with UE 5.6.0
  /// Updated FColorMaterialInput to use FLinearColor instead of FColor
  MaterialInputUsesLinearColor = 171,
  /// Updated editor only AFunctionalTest running logic to run tests editor world if the actors don't support PIE
  FunctionalTestCanRunInEditorWorld = 172,
  /// Added support for display name in the Visual Logger
  VisualLoggerSupportDisplayName = 173,
  /// Added support for the GyroscopicTorque flag in CVD
  GyroscopicTorquesSupportInChaosVisualDebugger = 174,
  /// Added managed array property serialization
  AddManagedArrayCollectionPropertySerialization = 175,
  /// Landscape texture patches in Texture Asset source mode now use proper resolution when calculating transform
  LandscapeTexturePatchUsesTextureAssetResolution = 176,
  /// Added support for relative transform in WorldPartitionActorDesc
  WorldPartitionActorDescSerializeRelativeTransform = 177,
  /// Make sure scene graph entities are not public by default
  SceneGraphEntitiesPrivateByDefault = 178,
  /// Added debug color for physical materials
  DebugColorForPhysicalMaterials = 179,
  /// Added PreprocessedFontGeometry to FFontFaceData
  AddedPreprocessedFontGeometry = 180,
  /// Added Dynamic Mesh Sculpt Layer serialization
  DynamicMeshSerializeSculptLayers = 181,
  /// Fix reachable garbage object warnings from some legacy ASpatialHashRuntimeGridInfo actors
  SpatialHashRuntimeGridInfoSpriteFixup = 182,
  /// Removed UAnimSequence::bUseRawDataOnly flag alongside compression refactor
  AnimSequenceRawDataOnlyFlagRemoval = 183,
  /// HLOD relevancy of Level Instances was previously ignored, now taken into account. Reset to the default behavior.
  ResetLevelInstanceHLODRelevancy = 184,
  /// Updated default scene capture post-processing settings to reflect the underlying implementation overrides
  SceneCaptureDefaultSettings = 185,
  /// Add Cloth Asset Base class serialization
  AddClothAssetBase = 186,
  /// Add inline constant default values to the PCG graph nodes.
  PCGInlineConstantDefaultValues = 187,
  /// Add MaterialSubstrateSubsurfaceType type to UMaterialExpressionSubstrateSlabBSDF for replacing bUseSSSDifffusion
  AddMaterialSubstrateSubsurfaceType = 188,
  /// Added option to visualize runtime virtual textures' streamed mips only in PIE
  AddedRuntimeVirtualTextureUseStreamingMipsInEditorMode = 189,
  /// Media plate holdout composite components have been replaced by a checkbox
  MediaPlateHoldoutComponentRemoval = 190,
  /// Changed PCG landscape cache default from "serialize at cook" to "never serialize"
  PCGLandscapeCacheDefaultSerializationChanged = 191,
  /// FSoftObjectPath::SubPathString changed to FUtf8String
  SoftObjectPathUtf8SubPaths = 192,
  /// FSoftObjectPath::SubPathString could be saved with trailing NULs and need truncating
  SoftObjectPathTrailingNULsMaintained = 193,
  /// Water body components no longer need to maintain their own PhysicalMaterial property since they are primitive components. After this version, leverage that one instead.
  WaterBodyPhysicalMaterialPropertyRemoval = 194,
  /// PCG fixed attribute set -> point conversion passing through empty point data as-is and violating output pin type.
  PCGAttributeSetToPointAlwaysConverts = 195,
  /// Add per material slot overlay material data
  MeshMaterialSlotOverlayMaterialAdded = 196,
  /// Convert Sustrate glint density properly
  ConvertGlintDensity = 197,
  /// Introduced skinweight validation to avoid render crashes and disappearing simulation meshes
  ClothAssetSkinweightsValidation = 198,
  /// Switching verse from right handed to left handed
  VerseRightToLeftHandedness = 199,
  /// Added additional data required to record and represent particle data from the game thread (Kinematic targets, and SQ rejection reasons)
  AdditionalGameThreadDataSupportInChaosVisualDebugger = 200,
  /// Upgrade UMG widget blueprints using legacy animation API
  UpgradeWidgetBlueprintLegacySequencePlayer = 201,
  /// Changed clockwise detection algorithm for PCGSplineDirection node with the correct one, but add a version to not break previous nodes.
  PCGSplineDirectionClockwiseFix = 202,
  /// Rect Lights set in EV units had the wrong intensity (older files need a flag set to keep the old look)
  RectLightFixedEVUnitConversion = 203,
  /// Add particle bounds to data exported to CVD
  ParticleInflatedBoundsInChaosVisualDebugger = 204,
  /// Migrate properties from FLandscapeLayer to ULandscapeEditLayer
  MigrateLandscapeEditLayerProperties = 205,
  /// Added more context data to CVD's traced shapes so we can play it back at the solver stage level (not just game thread frames)
  ThreadContextDataInChaosVisualDebuggerDebugDrawData = 206,
  /// Changed default grid mode in surface sampler to a version that's more intuitive and less error-prone
  PCGChangedSurfaceSamplerDefaultGridCreationMode = 207,
  // endregion
}

export const FFortniteMainBranchObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "WorldCompositionTile3DOffset",
    comment: "World composition tile offset changed from 2d to 3d",
    value: 1,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "MaterialInstanceSerializeOptimization_ShaderFName",
    comment: "Minor material serialization optimization",
    value: 2,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "CullDistanceRefactor_RemovedDefaultDistance",
    comment: "Refactored cull distances to account for HLOD, explicit override and globals in priority",
    value: 3,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "CullDistanceRefactor_NeverCullHLODsByDefault",
    value: 4,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "CullDistanceRefactor_NeverCullALODActorsByDefault",
    value: 5,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "SaveGeneratedMorphTargetByEngine",
    comment: "Support to remove morphtarget generated by bRemapMorphtarget",
    value: 6,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "ConvertReductionSettingOptions",
    comment: "Convert reduction setting options",
    value: 7,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "StaticParameterTerrainLayerWeightBlendType",
    comment: "Serialize the type of blending used for landscape layer weight static params",
    value: 8,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "FixUpNoneNameAnimationCurves",
    comment: "Fix up None Named animation curve names,",
    value: 9,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "EnsureActiveBoneIndicesToContainParents",
    comment: "Ensure ActiveBoneIndices to have parents even not skinned for old assets",
    value: 10,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "SerializeInstancedStaticMeshRenderData",
    comment: "Serialize the instanced static mesh render data, to avoid building it at runtime",
    value: 11,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "CachedMaterialQualityNodeUsage",
    comment: "Cache material quality node usage",
    value: 12,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "FontOutlineDropShadowFixup",
    comment:
      "Font outlines no longer apply to drop shadows for new objects but we maintain the opposite way for backwards compat",
    value: 13,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "NewSkeletalMeshImporterWorkflow",
    comment: "New skeletal mesh import workflow (Geometry only or animation only re-import )",
    value: 14,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "NewLandscapeMaterialPerLOD",
    comment: "Migrate data from previous data structure to new one to support materials per LOD on the Landscape",
    value: 15,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "RemoveUnnecessaryTracksFromPose",
    comment: "New Pose Asset data type",
    value: 16,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "FoliageLazyObjPtrToSoftObjPtr",
    comment: "Migrate Foliage TLazyObjectPtr to TSoftObjectPtr",
    value: 17,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "REVERTED_StoreTimelineNamesInTemplate",
    comment: "This code tied to this version was reverted and redone at a later date",
    value: 18,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "AddBakePoseOverrideForSkeletalMeshReductionSetting",
    comment: "Added BakePoseOverride for LOD setting",
    value: 19,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "StoreTimelineNamesInTemplate",
    comment: "TimelineTemplates store their derived names instead of dynamically generating",
    value: 20,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "WidgetStopDuplicatingAnimations",
    comment: "Avoid duplicating widget animations to save space.",
    value: 21,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "AllowSkeletalMeshToReduceTheBaseLOD",
    comment:
      "Allow reducing of the base LOD, we need to store some imported model data so we can reduce again from the same data.",
    value: 22,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "ShrinkCurveTableSize",
    comment: "Curve Table size reduction",
    value: 23,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "WidgetAnimationDefaultToSelfFail",
    comment:
      "Widgets upgraded with WidgetStopDuplicatingAnimations, may not correctly default-to-self for the widget parameter.",
    value: 24,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "FortHUDElementNowRequiresTag",
    comment: "HUDWidgets now require an element tag",
    value: 25,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "FortMappedCookedAnimation",
    comment: "Animation saved as bulk data when cooked",
    value: 26,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "SupportVirtualBoneInRetargeting",
    comment: "Support Virtual Bone in Retarget Manager",
    value: 27,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "FixUpWaterMetadata",
    comment: "Fixup bad defaults in water metadata",
    value: 28,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "MoveWaterMetadataToActor",
    comment: "Move the location of water metadata",
    value: 29,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "ReplaceLakeCollision",
    comment: "Replaced lake collision component",
    value: 30,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "AnimLayerGuidConformation",
    comment: "Anim layer node names are now conformed by Guid",
    value: 31,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "MakeOceanCollisionTransient",
    comment: "Ocean collision component has become dynamic",
    value: 32,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FFieldPathOwnerSerialization",
    comment: "FFieldPath will serialize the owner struct reference and only a short path to its property",
    value: 33,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixUpUnderwaterPostProcessMaterial",
    comment: "Simplified WaterBody post process material handling",
    value: 34,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SupportMultipleWaterBodiesPerExclusionVolume",
    comment: "A single water exclusion volume can now exclude N water bodies",
    value: 35,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "RigVMByteCodeDeterminism",
    comment: "Serialize rigvm operators one by one instead of the full byte code array to ensure determinism",
    value: 36,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "LandscapePhysicalMaterialRenderData",
    comment: "Serialize the physical materials generated by the render material",
    value: 37,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixupRuntimeVirtualTextureVolume",
    comment: "RuntimeVirtualTextureVolume fix transforms",
    value: 38,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixUpRiverCollisionComponents",
    comment: "Retrieve water body collision components that were lost in cooked builds",
    value: 39,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixDuplicateRiverSplineMeshCollisionComponents",
    comment: "Fix duplicate spline mesh components on rivers",
    value: 40,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "ContainsStableActorGUIDs",
    comment: "Indicates level has stable actor guids",
    value: 41,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "LevelsetSerializationSupportForBodySetup",
    comment: "Levelset Serialization support for BodySetup.",
    value: 42,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "ChaosSolverPropertiesMoved",
    comment: "Moving Chaos solver properties to allow them to exist in the project physics settings",
    value: 43,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "GameFeatureData_MovedComponentListAndCheats",
    comment: "Moving some UFortGameFeatureData properties and behaviors into the UGameFeatureAction pattern",
    value: 44,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ChaosClothAddfictitiousforces",
    comment: "Add centrifugal forces for cloth",
    value: 45,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ChaosConvexVariableStructureDataAndVerticesArray",
    comment: "(Merged from //UE4/Main)",
    value: 46,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemoveLandscapeWaterInfo",
    comment: "Remove the WaterVelocityHeightTexture dependency on MPC_Landscape and LandscapeWaterIndo",
    value: 47,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ChaosClothAddWeightedValue",
    comment: "Added the weighted value property type to store the cloths weight maps' low/high ranges",
    value: 48,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "ChaosClothAddTetherStiffnessWeightMap",
    comment: "Added the Long Range Attachment stiffness weight map",
    value: 49,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "ChaosClothFixLODTransitionMaps",
    comment: "Fix corrupted LOD transition maps",
    value: 50,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "ChaosClothAddTetherScaleAndDragLiftWeightMaps",
    comment: "Enable a few more weight maps to better art direct the cloth simulation",
    value: 51,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "ChaosClothAddMaterialWeightMaps",
    comment: "Enable material (edge, bending, and area stiffness) weight maps",
    value: 52,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "SerializeFloatChannelShowCurve",
    comment: "Added bShowCurve for movie scene float channel serialization",
    value: 53,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "LandscapeGrassSingleArray",
    comment: "Minimize slack waste by using a single array for grass data",
    value: 54,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "AddedSubSequenceEntryWarpCounter",
    comment: "Add loop counters to sequencer's compiled sub-sequence data",
    value: 55,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "WaterBodyComponentRefactor",
    comment: "Water plugin is now component-based rather than actor based",
    value: 56,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "BPGCCookedEditorTags",
    comment: "Cooked BPGC storing editor-only asset tags",
    value: 57,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "TerrainLayerWeightsAreNotParameters",
    comment: "Terrain layer weights are no longer considered material parameters",
    value: 58,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "GravityOverrideDefinedInWorldSpace",
    comment: "true for nodes predating this change.",
    value: 59,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "AnimDynamicsEditableChainParameters",
    comment:
      "Anim Dynamics Node Physics parameters for each body in a chain are now stored in an array and can be edited.",
    value: 60,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WaterZonesRefactor",
    comment: "Decoupled the generation of the water texture from the Water Brush and the landscape",
    value: 61,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ChaosClothFasterDamping",
    comment:
      "Add faster damping calculations to the cloth simulation and rename previous Damping parameter to LocalDamping.",
    value: 62,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "MigratedFunctionHandlersToDefaults",
    comment: "Migrated function handlers to the CDO/archetype data",
    value: 63,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ChaosInertiaConvertedToVec3",
    comment: "Storing inertia tensor as vec3 instead of matrix.",
    value: 64,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "MigratedEventDefinitionToDefaults",
    comment: "Migrated event definitions to the CDO/archetype data",
    value: 65,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "LevelInstanceActorGuidSerialize",
    comment: "Serialize LevelInstanceActorGuid on new ILevelInstanceInterface implementation",
    value: 66,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "SingleFrameAndKeyAnimModel",
    comment: "Single-frame/key AnimDataModel patch-up",
    value: 67,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "RemappedEvaluateWorldPositionOffsetInRayTracing",
    comment: "Remapped bEvaluateWorldPositionOffset to bEvaluateWorldPositionOffsetInRayTracing",
    value: 68,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WaterBodyComponentCollisionSettingsRefactor",
    comment:
      "Water body collision settings are now those of the base UPrimitiveComponent, rather than duplicated in UWaterBodyComponent",
    value: 69,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WidgetInheritedNamedSlots",
    comment:
      "if a widget exposes its named slot to everyone (even if it has content) which by default they wont any longer.",
    value: 70,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WaterHLODSupportAdded",
    comment: "Added water HLOD material",
    value: 71,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "PoseWatchMigrateSkeletonDrawParametersToPoseElement",
    comment:
      "Moved parameters affecting Skeleton pose rendering from the PoseWatch class to the PoseWatchPoseElement class.",
    value: 72,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WaterExclusionVolumeExcludeAllDefault",
    comment:
      'Reset default value for Water exclusion volumes to make them more intuitive and support the "it just works" philosophy.',
    value: 73,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WaterNontessellatedLODSupportAdded",
    comment: "Added water non-tessellated LOD",
    value: 74,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "HierarchicalSimplificationMethodEnumAdded",
    comment: "Added FHierarchicalSimplification::SimplificationMethod",
    value: 75,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WorldPartitionStreamingCellsNamingShortened",
    comment: "Changed how world partition streaming cells are named",
    value: 76,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeContentBundleGuid",
    comment: "Serialize ContentBundleGuid in WorldPartitionActorDesc",
    value: 77,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeActorIsRuntimeOnly",
    comment: "Serialize IsActorRuntimeOnly in WorldPartitionActorDesc",
    value: 78,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "NaniteMaterialOverride",
    comment: "Add Nanite Material Override option to materials and material instances.",
    value: 79,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WorldPartitionHLODActorDescSerializeStats",
    comment: "Serialize HLOD stats in HLODActorDesc",
    value: 80,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "WorldPartitionStreamingSourceComponentTargetDeprecation",
    comment: "WorldPartitionStreamingSourceComponent property deprecation",
    value: 81,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "FixedLocalizationGatherForExternalActorPackage",
    comment: "Fixed localization gathering for external actor packages",
    value: 82,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "WorldPartitionHLODActorUseSourceCellGuid",
    comment: "Change HLODActors to RuntimeCells mapping to use a GUID instead of the cell name",
    value: 83,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "ChaosGeometryCollectionInternalFacesAttribute",
    comment:
      "Add an attribute to geometry collection to track internal faces, rather than relying on material ID numbering",
    value: 84,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "DynamicCastNodesUsePureStateEnum",
    comment: "Dynamic cast nodes use an enumerated pure node state to include a value for the default setting",
    value: 85,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorFilter",
    comment: "Add FWorldPartitionActorFilter to FLevelInstanceActorDesc/FDataLayerInstanceDesc",
    value: 86,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "AudioAttenuationNonSpatializedRadiusBlend",
    comment: "Change the non-spatialized radius to blend to a pure 2D spatialized sound vs omnidirectional",
    value: 87,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorClassDescSerialize",
    comment: "Serialize actor class descriptors",
    value: 88,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionFActorContainerIDu64ToGuid",
    comment: "FActorContainerID is now an FGuid instead of a uint64",
    value: 89,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionPrivateDataLayers",
    comment: "FDataLayerInstanceDesc support for private data layers",
    value: 90,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "ChaosImplicitObjectUnionBVHRefactor",
    comment: "Reduce size and improve behaviour of Chaos::FImplicitObjectUnion",
    value: 91,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "LevelInstanceActorDescDeltaSerializeFilter",
    comment: "FLevelInstanceActorDesc DeltaSerialize Filter",
    value: 92,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "FixNaniteLandscapeMeshDDCKey",
    comment: "Fix the Nanite landscape mesh non-deterministic DDC keys",
    value: 93,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "ChaosGeometryCollectionConnectionEdgeGroup",
    comment: "Change how connection graphs are stored on Geometry Collections to an edge-array representation",
    value: 94,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WaterBodyStaticMeshComponents",
    comment:
      "Moved the water info mesh data and static water body meshes into new static mesh components for water bodies.",
    value: 95,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeInvalidBounds",
    comment: "Serialize invalid bounds in world partition actor descriptors",
    value: 96,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "NavigationLinkID32To64",
    comment: "Upgrade Navigation Links to use 64 bits for the ID",
    value: 97,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeEditorOnlyReferences",
    comment: "Serialize editor only references in world partition actor descriptors",
    value: 98,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeSoftObjectPathSupport",
    comment: "Add support for soft object paths in actor descriptors",
    value: 99,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionClasDescGuidTransient",
    comment: "Don't serialize class descriptor GUIDs",
    value: 100,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescIsMainWorldOnly",
    comment: "Serialize ActorDesc bIsMainWorldOnly",
    value: 101,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorFilterStringAssetPath",
    comment:
      "FWorldPartitionActorFilter go back to FString serialize of AssetPaths to avoid FArchiveReplaceOrClearExternalReferences clearing CDO references on BP Compile",
    value: 102,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "PackedLevelActorDesc",
    comment: "Add FPackedLevelActorDesc for APackedLevelActor and support for APackedLevelActor Filters",
    value: 103,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionRuntimeSpatialHashCVarOverrides",
    comment: "Add customizable values for several UWorldPartitionRuntimeSpatialHash cvars",
    value: 104,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WorldPartitionHLODSourceActorsRefactor",
    comment: "WorldPartition HLOD now contains a source actors object",
    value: 105,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WaterBodyStaticMeshRename",
    value: 106,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "GeometryCollectionConvertVertexColorToSRGB",
    comment: "Geometry Collection now by-default converts vertex colors to sRGB when creating render data",
    value: 107,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WaterOwningZonePointerFixup",
    comment:
      "Water bodies before this version need to update their water zone on load since they won't have been serialized yet.",
    value: 108,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WaterBodyStaticMeshDuplicateTransient",
    comment:
      "Set flags on water static meshes to duplicate transient to avoid underlying static mesh duplication issue",
    value: 109,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "MVVMConvertPropertyPathToSkeletalClass",
    comment: "Update paths to use the SkeletalClass",
    value: 110,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "WaterBodyStaticMeshFixup",
    comment: "Fixup all flags/outering on static meshes on water bodies by rebuilding them completely",
    value: 111,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "AnimGraphNodeBindingExtensions",
    comment: "Binding extensions for anim graph nodes",
    value: 112,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "RigVMSaveDebugMapInGraphFunctionData",
    comment: "Function data stores a map from work to debug operands",
    value: 113,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "FixMissingAnimGraphNodeBindingExtensions",
    comment: "Fix missing binding extensions for some anim graph nodes",
    value: 114,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "ISMComponentEditableWhenInheritedSkipSerialization",
    comment: "EditableWhenInherited: Skip custom serialization on non Archetypes",
    value: 115,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "LandscapeSupportPerComponentGrassTypes",
    comment: "GrassTypes are now per-component, rather than per-landscape proxy :",
    value: 116,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "WorldPartitionDataLayersLogicOperatorAdded",
    comment: "World partition actor data layers activation logic operator support defaults for old maps",
    value: 117,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "MovieSceneSortedBindings",
    comment: "Started sorting Possessables, Spawnables, and MovieSceneBindings for better search performance.",
    value: 118,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "RemoveAnimCurveCompressionCodecInstanceGuid",
    comment: "Remove the UAnimCurveCompressionCodec::InstanceGuid which causes cook determinism issues",
    value: 119,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "WorldPartitionHLODActorDescSerializeSourceHLODLayer",
    comment: "Serialize the source HLOD Layer for HLOD actor descriptors.",
    value: 120,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "WorldPartitionHLODActorDescSerializeEditorBounds",
    comment: "Serialize custom editor bounds for HLOD actor descriptors.",
    value: 121,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "LocalExposureDefaultChangeFrom1_Reverted",
    comment: "Changed default Local Exposure Contrast from 1.0 to 0.8 (reverted)",
    value: 122,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddDataLayerInstanceExternalPackage",
    comment: "Added support of external packaging of Data Layer Instances",
    value: 123,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "MVVMPropertyPathSelf",
    comment: "Update paths to keep a flag if they are the widget BP",
    value: 124,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddDataflowObjectSerialization",
    comment: "Enabled ObjectPtr property serialization for Dataflow nodes",
    value: 125,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AnimNotifyAddRateScale",
    comment: "Add anim notify rate scaling, defaults to on for new content, off for old content",
    value: 126,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "FixedTangentTransformForNonuniformBuildScale",
    comment:
      "Fix tangents for non-uniform build scales, and add a flag to optionally match the previous (incorrect) tangents",
    value: 127,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AnimNodeRootDefaultGroupChange",
    comment:
      "AnimNode Layers will now start in a Shared Group, instead of being each one on a different group at runtime",
    value: 128,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AnimNextMoveGraphsToEntries",
    comment: "Move AnimNext graphs to sub-entries of assets",
    value: 129,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AnimationSequenceCompressedDataRemoveDebugData",
    comment:
      "Removed debug information containing compressed data author, time etc. from animation DDC data as it introduces indeterminism",
    value: 130,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "OrthographicCameraDefaultSettings",
    comment: "Changes to Orthographic Camera default settings",
    value: 131,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "LandscapeAddedHLODSettings",
    comment: "Added settings to Landscape HLODs",
    value: 132,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "MeshDescriptionForSkeletalMesh",
    comment: "Skeletal Mesh uses Mesh Description to store mesh bulk data.",
    value: 133,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "SkeletalHalfEdgeData",
    comment: "Skeletal Mesh optionally cooks half edge data per lod",
    value: 134,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AnimNextCombineGraphContexts",
    comment: "Combine graph contexts for AnimNext graphs",
    value: 135,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AnimNextCombineParameterBlocksAndGraphs",
    comment: "Combine parameter blocks and graphs",
    value: 136,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AnimNextMoveWorkspaces",
    comment: "Move workspaces to a seperate plugin",
    value: 137,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LevelInstancePropertyOverrides",
    comment: "Level Instance Property overrides",
    value: 138,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "VolumetricLightMapGridDescSupport",
    comment: "Added FVolumetricLightMapGridDesc in MapBuildData",
    value: 139,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "IntroduceLandscapeEditLayerClass",
    comment: "Introduce new structure for customizing the landscape edit layer behavior",
    value: 140,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AnimNextWorkspaceEntryConversion",
    comment: "Change workspaces to store asset references as external objects",
    value: 141,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DataflowAnyTypeSupport",
    comment: "Add support for anytype in dataflow",
    value: 142,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PhysicsAssetUseManifoldFlags",
    comment: "Adding a new flag in RBAN Solver Setting to be able to use manifolds",
    value: 143,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SimAndQueryDataSupportInChaosVisualDebugger",
    comment: "Added support for to record sim and query data of Shape Instance data in CVD",
    value: 144,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ChaosClothAssetUSDImportNodeAddAssetDependencies",
    comment: "Add the imported asset dependencies to the Cloth Asset USD Import node",
    value: 145,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LumenRayLightingModeOverrideEnum",
    comment:
      "Changed HitLighting to HitLightingForReflections, and HitLighting now means hit lighting for entire Lumen",
    value: 146,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PCGPartitionActorDesc",
    comment: "PCGPartitionActorDesc",
    value: 147,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LandscapeTargetLayersInLandscapeActor",
    comment:
      "Target layers are now defined in the Landscape actor and not continuously synced from the assigned material.",
    value: 148,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DataflowTemplatedTypeFix",
    comment: "Fix to get full name of templated type ( Tarray > TArray<Float> for example )",
    value: 149,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LevelInstanceStaticLightingSupport",
    comment: "Changes for LevelInstance support in StaticLighting",
    value: 150,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PCGGridDescriptor",
    comment: "PCGGridDescriptor",
    value: 151,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AnimNextGraphAccessSpecifiers",
    comment: "AnimNext graphs now have public/private state",
    value: 152,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MaterialPixelDepthOffsetMode",
    comment: "Added a more stable pixel depth offset mode.",
    value: 153,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "DataflowHideablePins",
    comment: "Added hideable pins to dataflow",
    value: 154,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ClothAssetSkeletalMeshMultiSectionImport",
    comment: "Added multiple section import to the cloth asset skeletal mesh import node",
    value: 155,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeEditorBounds",
    comment: "Serialize EditorBounds in WorldPartitionActorDesc",
    value: 156,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FixupLandscapeTargetLayersInLandscapeActor",
    comment:
      "Fixup for the data that has been damaged by LandscapeTargetLayersInLandscapeActor (loss of landscape layer info object assignments)",
    value: 157,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MorphTargetCustomImport",
    comment: "Allow custom import of morph target",
    value: 158,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ChaosClothAllowZeroBucklingStiffness",
    comment: "Fix chaos cloth buckling stiffness parameter bug",
    value: 159,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LevelSequenceUpgradeDynamicBindings_NoOp",
    comment:
      "LevelSequenceUpgradeDynamicBindings was removed but was intended for this position. Putting this here to make sure versioning of subsequent assets remains the same",
    value: 160,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "GameFeatureDataActionAddToFrontendDefaultToUnload",
    comment: "AddToFrontend GFA now defaults to unload plugin on exit frontend",
    value: 161,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LevelSequenceUpgradeDynamicBindings",
    comment: "Upgraded movie scene 'dynamic bindings' to use the new Custom Bindings system",
    value: 162,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ChaosStoreKinematicTargetRotationAsSinglePrecision",
    comment:
      "Changed the precision for the stored rotation on kinematic targets to match the precision used in particles",
    value: 163,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "PCGApplyOnActorNodeMoveTargetActorEdgeToInput",
    comment: "PCG changes around the ApplyOnActor node, where we collapsed the TargetActor to the input pin.",
    value: 164,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "TimelinePlayingStateTrackerDeprecation",
    comment: "PlayingStateTracker type to improve replication reliability",
    value: 165,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MeshPaintTextureUsesEditorOnly",
    comment: "Enable SkipOnlyEditorOnly style cooking of UStaticMeshComponent::MeshPaintTexture",
    value: 166,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LandscapeBodyInstanceAsSharedProperty",
    comment:
      "Fixup and synchronize some landscape properties that have moved to the property sharing/overriding system :",
    value: 167,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AnimNextModuleRefactor",
    comment: "Multiple changes to AnimNext modules, variables etc.",
    value: 168,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SubsurfaceProfileGuid",
    comment: "Subsurface profile now has a guid to be able to select one of many in a Substrate material.",
    value: 169,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "SolverIterationsDataSupportInChaosVisualDebugger",
    comment: "Added support for to record the new solver iteration settings in CVD",
    value: 170,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "MaterialInputUsesLinearColor",
    comment: "Updated FColorMaterialInput to use FLinearColor instead of FColor",
    value: 171,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "FunctionalTestCanRunInEditorWorld",
    comment:
      "Updated editor only AFunctionalTest running logic to run tests editor world if the actors don't support PIE",
    value: 172,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "VisualLoggerSupportDisplayName",
    comment: "Added support for display name in the Visual Logger",
    value: 173,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "GyroscopicTorquesSupportInChaosVisualDebugger",
    comment: "Added support for the GyroscopicTorque flag in CVD",
    value: 174,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddManagedArrayCollectionPropertySerialization",
    comment: "Added managed array property serialization",
    value: 175,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "LandscapeTexturePatchUsesTextureAssetResolution",
    comment:
      "Landscape texture patches in Texture Asset source mode now use proper resolution when calculating transform",
    value: 176,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "WorldPartitionActorDescSerializeRelativeTransform",
    comment: "Added support for relative transform in WorldPartitionActorDesc",
    value: 177,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "SceneGraphEntitiesPrivateByDefault",
    comment: "Make sure scene graph entities are not public by default",
    value: 178,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "DebugColorForPhysicalMaterials",
    comment: "Added debug color for physical materials",
    value: 179,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddedPreprocessedFontGeometry",
    comment: "Added PreprocessedFontGeometry to FFontFaceData",
    value: 180,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "DynamicMeshSerializeSculptLayers",
    comment: "Added Dynamic Mesh Sculpt Layer serialization",
    value: 181,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "SpatialHashRuntimeGridInfoSpriteFixup",
    comment: "Fix reachable garbage object warnings from some legacy ASpatialHashRuntimeGridInfo actors",
    value: 182,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AnimSequenceRawDataOnlyFlagRemoval",
    comment: "Removed UAnimSequence::bUseRawDataOnly flag alongside compression refactor",
    value: 183,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ResetLevelInstanceHLODRelevancy",
    comment:
      "HLOD relevancy of Level Instances was previously ignored, now taken into account. Reset to the default behavior.",
    value: 184,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "SceneCaptureDefaultSettings",
    comment:
      "Updated default scene capture post-processing settings to reflect the underlying implementation overrides",
    value: 185,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddClothAssetBase",
    comment: "Add Cloth Asset Base class serialization",
    value: 186,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PCGInlineConstantDefaultValues",
    comment: "Add inline constant default values to the PCG graph nodes.",
    value: 187,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddMaterialSubstrateSubsurfaceType",
    comment:
      "Add MaterialSubstrateSubsurfaceType type to UMaterialExpressionSubstrateSlabBSDF for replacing bUseSSSDifffusion",
    value: 188,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddedRuntimeVirtualTextureUseStreamingMipsInEditorMode",
    comment: "Added option to visualize runtime virtual textures' streamed mips only in PIE",
    value: 189,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "MediaPlateHoldoutComponentRemoval",
    comment: "Media plate holdout composite components have been replaced by a checkbox",
    value: 190,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PCGLandscapeCacheDefaultSerializationChanged",
    comment: 'Changed PCG landscape cache default from "serialize at cook" to "never serialize"',
    value: 191,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "SoftObjectPathUtf8SubPaths",
    comment: "FSoftObjectPath::SubPathString changed to FUtf8String",
    value: 192,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "SoftObjectPathTrailingNULsMaintained",
    comment: "FSoftObjectPath::SubPathString could be saved with trailing NULs and need truncating",
    value: 193,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "WaterBodyPhysicalMaterialPropertyRemoval",
    comment:
      "Water body components no longer need to maintain their own PhysicalMaterial property since they are primitive components. After this version, leverage that one instead.",
    value: 194,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PCGAttributeSetToPointAlwaysConverts",
    comment:
      "PCG fixed attribute set -> point conversion passing through empty point data as-is and violating output pin type.",
    value: 195,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "MeshMaterialSlotOverlayMaterialAdded",
    comment: "Add per material slot overlay material data",
    value: 196,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ConvertGlintDensity",
    comment: "Convert Sustrate glint density properly",
    value: 197,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ClothAssetSkinweightsValidation",
    comment: "Introduced skinweight validation to avoid render crashes and disappearing simulation meshes",
    value: 198,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "VerseRightToLeftHandedness",
    comment: "Switching verse from right handed to left handed",
    value: 199,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AdditionalGameThreadDataSupportInChaosVisualDebugger",
    comment:
      "Added additional data required to record and represent particle data from the game thread (Kinematic targets, and SQ rejection reasons)",
    value: 200,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UpgradeWidgetBlueprintLegacySequencePlayer",
    comment: "Upgrade UMG widget blueprints using legacy animation API",
    value: 201,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PCGSplineDirectionClockwiseFix",
    comment:
      "Changed clockwise detection algorithm for PCGSplineDirection node with the correct one, but add a version to not break previous nodes.",
    value: 202,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "RectLightFixedEVUnitConversion",
    comment: "Rect Lights set in EV units had the wrong intensity (older files need a flag set to keep the old look)",
    value: 203,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ParticleInflatedBoundsInChaosVisualDebugger",
    comment: "Add particle bounds to data exported to CVD",
    value: 204,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "MigrateLandscapeEditLayerProperties",
    comment: "Migrate properties from FLandscapeLayer to ULandscapeEditLayer",
    value: 205,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ThreadContextDataInChaosVisualDebuggerDebugDrawData",
    comment:
      "Added more context data to CVD's traced shapes so we can play it back at the solver stage level (not just game thread frames)",
    value: 206,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "PCGChangedSurfaceSamplerDefaultGridCreationMode",
    comment: "Changed default grid mode in surface sampler to a version that's more intuitive and less error-prone",
    value: 207,
    firstAppearance: "5.6.0",
  }),
];

export const FFortniteMainBranchObjectVersionGuid = new CustomVersionGuid<FFortniteMainBranchObjectVersion>({
  name: "FFortniteMainBranchObjectVersion",
  guid: FGuid.fromComponents(0x601d1886, 0xac644f84, 0xaa16d3de, 0x0deac7d6),
  details: FFortniteMainBranchObjectVersionDetails,
});
