// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FFusionPatchCustomVersion {
  // region Introduced with UE 5.4.0
  BeforeCustomVersionWasAdded = 0,
  KeyzonesUseMappedParameters = 1,
  PitchShifterNameRedirects = 2,
  PanImportingFromDTAFixed = 3,
  DeprecatedPresets = 4,
  DeprecatedUnusedEffectsSettings = 5,
  DeprecateTypedSettingsArray = 6,
  // endregion
}

export const FFusionPatchCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "KeyzonesUseMappedParameters",
    value: 1,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "PitchShifterNameRedirects",
    value: 2,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "PanImportingFromDTAFixed",
    value: 3,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "DeprecatedPresets",
    value: 4,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "DeprecatedUnusedEffectsSettings",
    value: 5,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "DeprecateTypedSettingsArray",
    value: 6,
    firstAppearance: "5.4.0",
  }),
];

export const FFusionPatchCustomVersionGuid = new CustomVersionGuid<FFusionPatchCustomVersion>({
  friendlyName: "FusionPatchVer",
  guid: __INVALID_GUID__,
  details: FFusionPatchCustomVersionDetails,
});
