// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FGameNetworkCustomVersion {
  // region Introduced with UE 5.2.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FGameNetworkCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.2.0",
  }),
];

export const FGameNetworkCustomVersionGuid = new CustomVersionGuid<FGameNetworkCustomVersion>({
  friendlyName: "GameNetworkVersion",
  guid: __INVALID_GUID__,
  details: FGameNetworkCustomVersionDetails,
});
