// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FIKRigObjectVersion {
  // region Introduced with UE 5.0.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion

  // region Introduced with UE 5.1.0
  /// Retarget pose quaternions changed from pre to post multiplied
  RetargetPoseQuatPostMultiplied = 1,
  /// Chain settings moved to struct to be used in profiles
  ChainSettingsConvertedToStruct = 2,
  // endregion

  // region Introduced with UE 5.6.0
  /// Pin Bone "Maintain Offset" converted from bool to enum
  PinBoneTypeAndOffsetsUpgraded = 3,
  /// we switched "Use Attach Parent" from a bool to an enum on retarget pose from mesh node
  UseAttachedParentDeprecated = 4,
  /// modularized retargeting internals (converted phases to ops)
  ModularRetargeterOps = 5,
  /// ops control their own chain mapping (no more global chain map on retarget asset)
  OpsOwnChainMapping = 6,
  // endregion
}

export const FIKRigObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "RetargetPoseQuatPostMultiplied",
    comment: "Retarget pose quaternions changed from pre to post multiplied",
    value: 1,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ChainSettingsConvertedToStruct",
    comment: "Chain settings moved to struct to be used in profiles",
    value: 2,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "PinBoneTypeAndOffsetsUpgraded",
    comment: 'Pin Bone "Maintain Offset" converted from bool to enum',
    value: 3,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "UseAttachedParentDeprecated",
    comment: 'we switched "Use Attach Parent" from a bool to an enum on retarget pose from mesh node',
    value: 4,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ModularRetargeterOps",
    comment: "modularized retargeting internals (converted phases to ops)",
    value: 5,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "OpsOwnChainMapping",
    comment: "ops control their own chain mapping (no more global chain map on retarget asset)",
    value: 6,
    firstAppearance: "5.6.0",
  }),
];

export const FIKRigObjectVersionGuid = new CustomVersionGuid<FIKRigObjectVersion>({
  friendlyName: "Dev-IKRig",
  guid: FGuid.fromComponents(0xf6dfbb78, 0xbb50a0e4, 0x4018b84d, 0x60cbaf23),
  details: FIKRigObjectVersionDetails,
});
