// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FInstancedActorsCustomVersion {
  // region Introduced with UE 5.4.0
  /// Before any version changes were made in the plugin
  InitialVersion = 0,
  // endregion
}

export const FInstancedActorsCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "InitialVersion",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.4.0",
  }),
];

export const FInstancedActorsCustomVersionGuid = new CustomVersionGuid<FInstancedActorsCustomVersion>({
  friendlyName: "InstancedActors",
  guid: FGuid.fromComponents(0xa6ebc74a, 0x3bad46b8, 0xaa30d6b2, 0x7d58ea25),
  details: FInstancedActorsCustomVersionDetails,
});
