// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FInterchangeCustomVersion {
  // region Introduced with UE 5.3.0
  /// Roughly corresponds to 5.2
  BeforeCustomVersionWasAdded = 0,
  SerializedInterchangeObjectStoring = 1,
  // endregion
}

export const FInterchangeCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 5.2",
    value: 0,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "SerializedInterchangeObjectStoring",
    value: 1,
    firstAppearance: "5.3.0",
  }),
];

export const FInterchangeCustomVersionGuid = new CustomVersionGuid<FInterchangeCustomVersion>({
  friendlyName: "InterchangeAssetImportDataVer",
  guid: FGuid.fromString("{92738C43-2988-4D9C-9A3D-9BBE6EFF9FC0}"),
  details: FInterchangeCustomVersionDetails,
});
