// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FLandscapeCustomVersion {
  // region Introduced with UE 4.9.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Changed to TMap properties instead of manual serialization and fixed landscape spline control point cross-level mesh components not being serialized
  NewSplineCrossLevelMeshSerialization = 1,
  // endregion

  // region Introduced with UE 4.11.2
  /// Support material world-position-offset in the heightmap used for grass placement
  GrassMaterialWPO = 2,
  // endregion

  // region Introduced with UE 4.12.0
  /// Support material world-position-offset in landscape simple collision
  CollisionMaterialWPO = 3,
  /// Support material world-position-offset in landscape lighting mesh
  LightmassMaterialWPO = 4,
  /// Fix for landscape grass not updating when using a material instance as the landscape material and changing parameters
  GrassMaterialInstanceFix = 5,
  // endregion

  // region Introduced with UE 4.16.0
  /// Fix for spline Foreign data that used TMap<TLazyObjectPtr, ...> to now use TArray<...> to prevent key creation every time we do a search thus putting the package dirty
  SplineForeignDataLazyObjectPtrFix = 6,
  // endregion

  // region Introduced with UE 4.19.0
  /// Migration of deprecated property from old landscape rendering to new landscape Rendering
  MigrateOldPropertiesToNewRenderingProperties = 7,
  // endregion

  // region Introduced with UE 4.20.0
  /// Migration of old EnabledCollision for spline elements to the full body instance exposed
  AddingBodyInstanceToSplinesElements = 8,
  // endregion

  // region Introduced with UE 4.24.0
  /// Spline Layer Falloff
  AddSplineLayerFalloff = 9,
  /// Spline Layer Width
  AddSplineLayerWidth = 10,
  /// New LOD distribution and tessellation calculations are introduced, needs parameter conversion
  NewLandscapeContinuousLOD = 11,
  // endregion
}

export const FLandscapeCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.9.0",
  }),
  new VersionDetails({
    name: "NewSplineCrossLevelMeshSerialization",
    comment:
      "Changed to TMap properties instead of manual serialization and fixed landscape spline control point cross-level mesh components not being serialized",
    value: 1,
    firstAppearance: "4.9.0",
  }),
  new VersionDetails({
    name: "GrassMaterialWPO",
    comment:
      "Support material world-position-offset in the heightmap used for grass placement",
    value: 2,
    firstAppearance: "4.11.2",
  }),
  new VersionDetails({
    name: "CollisionMaterialWPO",
    comment:
      "Support material world-position-offset in landscape simple collision",
    value: 3,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "LightmassMaterialWPO",
    comment:
      "Support material world-position-offset in landscape lighting mesh",
    value: 4,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "GrassMaterialInstanceFix",
    comment:
      "Fix for landscape grass not updating when using a material instance as the landscape material and changing parameters",
    value: 5,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "SplineForeignDataLazyObjectPtrFix",
    comment:
      "Fix for spline Foreign data that used TMap<TLazyObjectPtr, ...> to now use TArray<...> to prevent key creation every time we do a search thus putting the package dirty",
    value: 6,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "MigrateOldPropertiesToNewRenderingProperties",
    comment:
      "Migration of deprecated property from old landscape rendering to new landscape Rendering ",
    value: 7,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "AddingBodyInstanceToSplinesElements",
    comment:
      "Migration of old EnabledCollision for spline elements to the full body instance exposed",
    value: 8,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "AddSplineLayerFalloff",
    comment: "Spline Layer Falloff",
    value: 9,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "AddSplineLayerWidth",
    comment: "Spline Layer Width",
    value: 10,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "NewLandscapeContinuousLOD",
    comment:
      "New LOD distribution and tessellation calculations are introduced, needs parameter conversion",
    value: 11,
    firstAppearance: "4.24.0",
  }),
];
