// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FLensFileObjectVersion {
  // region Introduced with UE 5.5.0
  BeforeCustomVersionWasAdded = 0,
  EditableFocusCurves = 1,
  // endregion
}

export const FLensFileObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "EditableFocusCurves",
    value: 1,
    firstAppearance: "5.5.0",
  }),
];

export const FLensFileObjectVersionGuid = new CustomVersionGuid<FLensFileObjectVersion>({
  friendlyName: "LensFileVersion",
  guid: FGuid.fromComponents(0x8652a554, 0x966a466c, 0x9fd71c6d, 0xd61b1adb),
  details: FLensFileObjectVersionDetails,
});
