// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FLiveLinkCustomVersion {
  // region Introduced with UE 4.23.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  NewLiveLinkRoleSystem = 1,
  // endregion
}

export const FLiveLinkCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "NewLiveLinkRoleSystem",
    value: 1,
    firstAppearance: "4.23.0",
  }),
];
