// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FLocalFileReplayCustomVersion {
  // region Introduced with UE 5.2.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  FixedSizeFriendlyName = 1,
  CompressionSupport = 2,
  RecordingTimestamp = 3,
  StreamChunkTimes = 4,
  FriendlyNameCharEncoding = 5,
  EncryptionSupport = 6,
  CustomVersions = 7,
  // endregion
}

export const FLocalFileReplayCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "FixedSizeFriendlyName",
    value: 1,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "CompressionSupport",
    value: 2,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "RecordingTimestamp",
    value: 3,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "StreamChunkTimes",
    value: 4,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "FriendlyNameCharEncoding",
    value: 5,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "EncryptionSupport",
    value: 6,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "CustomVersions",
    value: 7,
    firstAppearance: "5.2.0",
  }),
];

export const FLocalFileReplayCustomVersionGuid = new CustomVersionGuid<FLocalFileReplayCustomVersion>({
  friendlyName: "LocalFileReplay",
  guid: __INVALID_GUID__,
  details: FLocalFileReplayCustomVersionDetails,
});
