// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FMetaHumanCoreCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Added audio processing type to frame data
  AddAudioProcessingTypeToFrameData = 1,
  // endregion
}

export const FMetaHumanCoreCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "AddAudioProcessingTypeToFrameData",
    comment: "Added audio processing type to frame data",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FMetaHumanCoreCustomVersionGuid = new CustomVersionGuid<FMetaHumanCoreCustomVersion>({
  friendlyName: "MetaHumanCoreVer",
  guid: FGuid.fromComponents(0x9a529652, 0xb6f785f7, 0x4b868fb5, 0x744f83e3),
  details: FMetaHumanCoreCustomVersionDetails,
});
