// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FMetaHumanIdentityCustomVersion {
  // region Introduced with UE 5.6.0
  /// MetaHuman Identity was updated to use EditorBulkData
  EditorBulkDataUpdate = 0,
  // endregion
}

export const FMetaHumanIdentityCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "EditorBulkDataUpdate",
    comment: "MetaHuman Identity was updated to use EditorBulkData",
    value: 0,
    firstAppearance: "5.6.0",
  }),
];

export const FMetaHumanIdentityCustomVersionGuid = new CustomVersionGuid<FMetaHumanIdentityCustomVersion>({
  friendlyName: "MetaHumanIdentityCustomVersion",
  guid: FGuid.fromComponents(0x3ac07c3c, 0x19ff4731, 0x98c5432b, 0x43b241b5),
  details: FMetaHumanIdentityCustomVersionDetails,
});
