// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FMetaHumanCharacterCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes
  CharcterBase = 0,
  /// High res body textures serialized to character
  BodyTexturesSerialized = 1,
  // endregion
}

export const FMetaHumanCharacterCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "CharcterBase",
    comment: "Before any version changes",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "BodyTexturesSerialized",
    comment: "High res body textures serialized to character",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FMetaHumanCharacterCustomVersionGuid = new CustomVersionGuid<FMetaHumanCharacterCustomVersion>({
  friendlyName: "MetaHumanCharacter",
  guid: FGuid.fromComponents(0xc5db848, 0x21757ce, 0xc42843e, 0xca16973),
  details: FMetaHumanCharacterCustomVersionDetails,
});
