// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FMobileObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion

  // region Introduced with UE 4.19.0
  /// Removed LightmapUVBias, ShadowmapUVBias from per-instance data
  InstancedStaticMeshLightmapSerialization = 1,
  /// Added stationary point/spot light direct contribution to volumetric lightmaps.
  LQVolumetricLightmapLayers = 2,
  // endregion

  // region Introduced with UE 4.26.0
  /// Store Reflection Capture in compressed format for mobile
  StoreReflectionCaptureCompressedMobile = 3,
  // endregion
}

export const FMobileObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "InstancedStaticMeshLightmapSerialization",
    comment: "Removed LightmapUVBias, ShadowmapUVBias from per-instance data",
    value: 1,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "LQVolumetricLightmapLayers",
    comment:
      "Added stationary point/spot light direct contribution to volumetric lightmaps. ",
    value: 2,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "StoreReflectionCaptureCompressedMobile",
    comment: "Store Reflection Capture in compressed format for mobile",
    value: 3,
    firstAppearance: "4.26.0",
  }),
];
