// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FMovieRenderPipelineCoreObjectVersion {
  // region Introduced with UE 5.6.0
  PreVersioning = 0,
  OnlyMatchComponentsAdded = 1,
  // endregion
}

export const FMovieRenderPipelineCoreObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "OnlyMatchComponentsAdded",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FMovieRenderPipelineCoreObjectVersionGuid = new CustomVersionGuid<FMovieRenderPipelineCoreObjectVersion>({
  friendlyName: "MovieRenderPipelineCoreObjectVersion",
  guid: FGuid.fromComponents(0x81a1b2b3, 0xaf127711, 0xe211b0b2, 0x1d235409),
  details: FMovieRenderPipelineCoreObjectVersionDetails,
});
