// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FMovieSceneEvaluationCustomVersion {
  // region Introduced with UE 4.15.0
  Initial = 0,
  // endregion

  // region Introduced with UE 4.17.0
  /// Changed EvalOptions.bEvaluateNearestSection to be false by default
  ChangeEvaluateNearestSectionDefault = 1,
  /// Added support for blending
  AddBlendingSupport = 2,
  // endregion

  // region Introduced with UE 4.26.0
  /// Added ECS evaluation
  EntityManager = 3,
  /// Removed GUID references to blueprint graphs and replaced with direct weak ptrs
  DeprecateEventGUIDs = 4,
  // endregion
}

export const FMovieSceneEvaluationCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "Initial",
    value: 0,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "ChangeEvaluateNearestSectionDefault",
    comment: "Changed EvalOptions.bEvaluateNearestSection to be false by default",
    value: 1,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "AddBlendingSupport",
    comment: "Added support for blending",
    value: 2,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "EntityManager",
    comment: "Added ECS evaluation",
    value: 3,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "DeprecateEventGUIDs",
    comment: "Removed GUID references to blueprint graphs and replaced with direct weak ptrs",
    value: 4,
    firstAppearance: "4.26.0",
  }),
];
