// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FNaniteResearchStreamObjectVersion {
  // region Introduced with UE 5.5.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Various global shader values converted to LWC types
  LWCTypesInShaders = 1,
  // endregion
}

export const FNaniteResearchStreamObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "LWCTypesInShaders",
    comment: "Various global shader values converted to LWC types",
    value: 1,
    firstAppearance: "5.5.0",
  }),
];

export const FNaniteResearchStreamObjectVersionGuid = new CustomVersionGuid<FNaniteResearchStreamObjectVersion>({
  friendlyName: "Dev-NaniteResearch",
  guid: FGuid.fromComponents(0x30d58be3, 0x95ea4282, 0xa6e3b159, 0xd8ebb06a),
  details: FNaniteResearchStreamObjectVersionDetails,
});
