// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FNearestNeighborModelCustomVersion {
  // region Introduced with UE 5.4.0
  BeforeCustomVersionWasAdded = 0,
  AddTrainedBasis = 1,
  // endregion

  // region Introduced with UE 5.5.0
  DeprecateNumEpochs = 2,
  // endregion
}

export const FNearestNeighborModelCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddTrainedBasis",
    value: 1,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "DeprecateNumEpochs",
    value: 2,
    firstAppearance: "5.5.0",
  }),
];
