// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FNearestNeighborModelCustomVersion {
  // region Introduced with UE 5.4.0
  BeforeCustomVersionWasAdded = 0,
  AddTrainedBasis = 1,
  // endregion

  // region Introduced with UE 5.5.0
  DeprecateNumEpochs = 2,
  // endregion
}

export const FNearestNeighborModelCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddTrainedBasis",
    value: 1,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "DeprecateNumEpochs",
    value: 2,
    firstAppearance: "5.5.0",
  }),
];

export const FNearestNeighborModelCustomVersionGuid = new CustomVersionGuid<FNearestNeighborModelCustomVersion>({
  friendlyName: "NearestNeighborModelVer",
  guid: FGuid.fromComponents(0xba926256, 0x6c7947c4, 0x96d1e4f4, 0xce985342),
  details: FNearestNeighborModelCustomVersionDetails,
});
