// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FNetworkingObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FNetworkingObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
];

export const FNetworkingObjectVersionGuid = new CustomVersionGuid<FNetworkingObjectVersion>({
  friendlyName: "Dev-Networking",
  guid: FGuid.fromComponents(0xa4e4105c, 0x59a149b5, 0xa7c540c4, 0x547edfee),
  details: FNetworkingObjectVersionDetails,
});
