// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FNiagaraObjectVersion {
  // region Introduced with UE 4.21.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  SkeletalMeshVertexSampling = 1,
  // endregion
}

export const FNiagaraObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "SkeletalMeshVertexSampling",
    value: 1,
    firstAppearance: "4.21.0",
  }),
];

export const FNiagaraObjectVersionGuid = new CustomVersionGuid<FNiagaraObjectVersion>({
  friendlyName: "Dev-Niagara",
  guid: FGuid.fromComponents(0xf2aed0ac, 0x9afe416f, 0x8664aa7f, 0xfa26d6fc),
  details: FNiagaraObjectVersionDetails,
});
