// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FOnlineObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FOnlineObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
];

export const FOnlineObjectVersionGuid = new CustomVersionGuid<FOnlineObjectVersion>({
  friendlyName: "Dev-Online",
  guid: FGuid.fromComponents(0x39c831c9, 0x5ae647dc, 0x9a449c17, 0x3e1c8e7c),
  details: FOnlineObjectVersionDetails,
});
