// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FOverlappingVerticesCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Converted to use HierarchicalInstancedStaticMeshComponent
  DetectOVerlappingVertices = 1,
  // endregion
}

export const FOverlappingVerticesCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "DetectOVerlappingVertices",
    comment: "Converted to use HierarchicalInstancedStaticMeshComponent",
    value: 1,
    firstAppearance: "4.27.0",
  }),
];

export const FOverlappingVerticesCustomVersionGuid = new CustomVersionGuid<FOverlappingVerticesCustomVersion>({
  friendlyName: "OverlappingVerticeDetectionVer",
  guid: FGuid.fromComponents(0x612fbe52, 0xda53400b, 0x910d4f91, 0x9fb1857c),
  details: FOverlappingVerticesCustomVersionDetails,
});
