// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FOverlappingVerticesCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Converted to use HierarchicalInstancedStaticMeshComponent
  DetectOVerlappingVertices = 1,
  // endregion
}

export const FOverlappingVerticesCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "DetectOVerlappingVertices",
    comment: "Converted to use HierarchicalInstancedStaticMeshComponent",
    value: 1,
    firstAppearance: "4.27.0",
  }),
];
