// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FPaperCustomVersion {
  // region Introduced with UE 4.5.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Fixed negative volume in UPaperSprite 3D aggregate geometry (caused collision issues)
  FixedNegativeVolume = 1,
  /// Removed FBodyInstance2D and moved 2D physics support into Engine (requires regenerating 2D agg geom)
  RemovedBodyInstance2D = 2,
  /// Moved tile map data out of the component into UPaperTileMap
  MovedTileMapDataToSeparateClass = 3,
  /// Marked sprite UBodySetup to use simple as complex, allowing 3D raycasts to succeed
  MarkSpriteBodySetupToUseSimpleAsComplex = 4,
  /// Added PixelsPerUnrealUnit to move away from a 1:1 relationship between pixels and uu
  AddPixelsPerUnrealUnit = 5,
  /// Fixed typo in convex hull generation code for 3D custom collision
  FixTypoIn3DConvexHullCollisionGeneration = 6,
  /// Fixed undo issues in several asset types due to missing RF_Transactional flag
  AddTransactionalToClasses = 7,
  /// Converted UPaperSpriteComponent to be derived from UMeshComponent
  ConvertPaperSpriteComponentToBeMeshComponent = 8,
  /// Added the option to snap pivots to a pixel grid
  AddPivotSnapToPixelGrid = 9,
  /// Converted UPaperFlipbookComponent to be derived from UMeshComponent
  ConvertPaperFlipbookComponentToBeMeshComponent = 10,
  /// Add default BodyInstance setup in the sprite asset
  AddDefaultCollisionProfileInSpriteAsset = 11,
  // endregion

  // region Introduced with UE 4.7.0
  /// Add source texture size
  AddSourceTextureSize = 12,
  // endregion

  // region Introduced with UE 4.7.4
  /// Fix incorrect collision geometry generation when sprites were rotated in the source texture
  FixIncorrectCollisionOnSourceRotatedSprites = 13,
  // endregion

  // region Introduced with UE 4.8.0
  /// Refactor sprite render/collision polygon storage to allow more flexible geometry shapes
  RefactorPolygonStorageToSupportShapes = 14,
  /// Change Tile Set margin and padding to allow non-uniform values (also converts TileWidth/TileHeight into TileSize and makes members private)
  AllowNonUniformPaddingInTileSets = 15,
  /// Fixed the tangent generation for sprites, tile maps, etc... being incorrect for the front face
  FixTangentGenerationForFrontFace = 16,
  // endregion

  // region Introduced with UE 4.9.0
  /// rather than sprites appearing far brighter than they should (note: they are still sent down as a FColor so they have limited precision)
  FixVertexColorSpace = 17,
  // endregion
}

export const FPaperCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "FixedNegativeVolume",
    comment: "Fixed negative volume in UPaperSprite 3D aggregate geometry (caused collision issues)",
    value: 1,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "RemovedBodyInstance2D",
    comment: "Removed FBodyInstance2D and moved 2D physics support into Engine (requires regenerating 2D agg geom)",
    value: 2,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "MovedTileMapDataToSeparateClass",
    comment: "Moved tile map data out of the component into UPaperTileMap",
    value: 3,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "MarkSpriteBodySetupToUseSimpleAsComplex",
    comment: "Marked sprite UBodySetup to use simple as complex, allowing 3D raycasts to succeed",
    value: 4,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "AddPixelsPerUnrealUnit",
    comment: "Added PixelsPerUnrealUnit to move away from a 1:1 relationship between pixels and uu",
    value: 5,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "FixTypoIn3DConvexHullCollisionGeneration",
    comment: "Fixed typo in convex hull generation code for 3D custom collision",
    value: 6,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "AddTransactionalToClasses",
    comment: "Fixed undo issues in several asset types due to missing RF_Transactional flag",
    value: 7,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "ConvertPaperSpriteComponentToBeMeshComponent",
    comment: "Converted UPaperSpriteComponent to be derived from UMeshComponent",
    value: 8,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "AddPivotSnapToPixelGrid",
    comment: "Added the option to snap pivots to a pixel grid",
    value: 9,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "ConvertPaperFlipbookComponentToBeMeshComponent",
    comment: "Converted UPaperFlipbookComponent to be derived from UMeshComponent",
    value: 10,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "AddDefaultCollisionProfileInSpriteAsset",
    comment: "Add default BodyInstance setup in the sprite asset",
    value: 11,
    firstAppearance: "4.5.0",
  }),
  new VersionDetails({
    name: "AddSourceTextureSize",
    comment: "Add source texture size",
    value: 12,
    firstAppearance: "4.7.0",
  }),
  new VersionDetails({
    name: "FixIncorrectCollisionOnSourceRotatedSprites",
    comment: "Fix incorrect collision geometry generation when sprites were rotated in the source texture",
    value: 13,
    firstAppearance: "4.7.4",
  }),
  new VersionDetails({
    name: "RefactorPolygonStorageToSupportShapes",
    comment: "Refactor sprite render/collision polygon storage to allow more flexible geometry shapes",
    value: 14,
    firstAppearance: "4.8.0",
  }),
  new VersionDetails({
    name: "AllowNonUniformPaddingInTileSets",
    comment:
      "Change Tile Set margin and padding to allow non-uniform values (also converts TileWidth/TileHeight into TileSize and makes members private)",
    value: 15,
    firstAppearance: "4.8.0",
  }),
  new VersionDetails({
    name: "FixTangentGenerationForFrontFace",
    comment: "Fixed the tangent generation for sprites, tile maps, etc... being incorrect for the front face",
    value: 16,
    firstAppearance: "4.8.0",
  }),
  new VersionDetails({
    name: "FixVertexColorSpace",
    comment:
      "rather than sprites appearing far brighter than they should (note: they are still sent down as a FColor so they have limited precision)",
    value: 17,
    firstAppearance: "4.9.0",
  }),
];
