// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FParticleSystemCustomVersion {
  // region Introduced with UE 4.20.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  SkipCookingEmittersBasedOnDetailMode = 1,
  /// skip emitter cooking if their detail mode doesn't match predefined
  FixLegacySpawningBugs = 2,
  // endregion

  // region Introduced with UE 5.3.0
  /// fixing some spawning bugs but must keep old behavior around for existing systems.
  AddEpicDetailMode = 3,
  // endregion
}

export const FParticleSystemCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "SkipCookingEmittersBasedOnDetailMode",
    value: 1,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "FixLegacySpawningBugs",
    comment:
      "skip emitter cooking if their detail mode doesn't match predefined",
    value: 2,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "AddEpicDetailMode",
    comment:
      "fixing some spawning bugs but must keep old behavior around for existing systems.",
    value: 3,
    firstAppearance: "5.3.0",
  }),
];
