// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FPoseDriverCustomVersion {
  // region Introduced with UE 4.16.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Add RBFData
  AddRBFData = 1,
  /// Add multi-bone input support
  MultiBoneInput = 2,
  // endregion
}

export const FPoseDriverCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "AddRBFData",
    comment: "Add RBFData",
    value: 1,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "MultiBoneInput",
    comment: "Add multi-bone input support",
    value: 2,
    firstAppearance: "4.16.0",
  }),
];
