// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FProceduralFoliageCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// We serialize the type clean change map to ensure validity
  SerializeTypeMap = 1,
  // endregion
}

export const FProceduralFoliageCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "SerializeTypeMap",
    comment: "We serialize the type clean change map to ensure validity",
    value: 1,
    firstAppearance: "4.27.0",
  }),
];
