// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FRecomputeTangentCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// We serialize the RecomputeTangent Option
  RuntimeRecomputeTangent = 1,
  /// Choose which Vertex Color channel to use as mask to blend tangents
  RecomputeTangentVertexColorMask = 2,
  // endregion
}

export const FRecomputeTangentCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RuntimeRecomputeTangent",
    comment: "We serialize the RecomputeTangent Option",
    value: 1,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RecomputeTangentVertexColorMask",
    comment: "Choose which Vertex Color channel to use as mask to blend tangents",
    value: 2,
    firstAppearance: "4.27.0",
  }),
];

export const FRecomputeTangentCustomVersionGuid = new CustomVersionGuid<FRecomputeTangentCustomVersion>({
  friendlyName: "RecomputeTangentCustomVer",
  guid: FGuid.fromComponents(0x5579f886, 0x933a4c1f, 0x83ba087b, 0x6361b92f),
  details: FRecomputeTangentCustomVersionDetails,
});
