// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FReflectionCaptureObjectVersion {
  // region Introduced with UE 4.19.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Allows uncompressed reflection captures for cooked builds
  MoveReflectionCaptureDataToMapBuildData = 1,
  // endregion
}

export const FReflectionCaptureObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "MoveReflectionCaptureDataToMapBuildData",
    comment: "Allows uncompressed reflection captures for cooked builds",
    value: 1,
    firstAppearance: "4.19.0",
  }),
];

export const FReflectionCaptureObjectVersionGuid = new CustomVersionGuid<FReflectionCaptureObjectVersion>({
  friendlyName: "Dev-ReflectionCapture",
  guid: FGuid.fromComponents(0x6b266cec, 0x1ec74b8f, 0xa30be4d9, 0x0942fc07),
  details: FReflectionCaptureObjectVersionDetails,
});
