// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FRegionAffiliationAssetCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FRegionAffiliationAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.6.0",
  }),
];

export const FRegionAffiliationAssetCustomVersionGuid = new CustomVersionGuid<FRegionAffiliationAssetCustomVersion>({
  friendlyName: "RegionAffiliationAssetVer",
  guid: FGuid.fromComponents(0xfa0c4d22, 0x6d36415e, 0x937f159f, 0xb7814f35),
  details: FRegionAffiliationAssetCustomVersionDetails,
});
