// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FRegionAffiliationAssetCustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FRegionAffiliationAssetCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.6.0",
  }),
];
