// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FRemoteControlObjectVersion {
  // region Introduced with UE 4.27.0
  /// Roughly corresponds to 4.26
  BeforeCustomVersionWasAdded = 0,
  /// Properties can now be directly exposed on components
  RemovedComponentChain = 1,
  /// RCProperties and RCFunctions now inherit from FRemoteControlEntity
  ConvertRCFieldsToRCEntities = 2,
  /// Converted FRemoteControlTarget to URemoteControlBinding, put RCFields in the expose registry.
  ConvertTargetsToBindings = 3,
  /// ExposedEntities can now be rebound.
  AddedRebindingFunctionality = 4,
  /// Added property/function flags to RemoteControlField
  AddedFieldFlags = 5,
  // endregion

  // region Introduced with UE 5.5.0
  /// Instead of the global 'Protocol Generates Transactions' setting, each preset can now specify its modify operation flags
  AddedPerPresetModifyOperationFlags = 6,
  /// Change FRCEntityWrapper::ExposedEntities' Set to an Array to retain ordering across sessions
  ChangedExposedEntitiesSetToAnOrderedTArray = 7,
  // endregion
}

export const FRemoteControlObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 4.26",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemovedComponentChain",
    comment: "Properties can now be directly exposed on components",
    value: 1,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ConvertRCFieldsToRCEntities",
    comment: "RCProperties and RCFunctions now inherit from FRemoteControlEntity",
    value: 2,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "ConvertTargetsToBindings",
    comment: "Converted FRemoteControlTarget to URemoteControlBinding, put RCFields in the expose registry.",
    value: 3,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "AddedRebindingFunctionality",
    comment: "ExposedEntities can now be rebound.",
    value: 4,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "AddedFieldFlags",
    comment: "Added property/function flags to RemoteControlField",
    value: 5,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "AddedPerPresetModifyOperationFlags",
    comment:
      "Instead of the global 'Protocol Generates Transactions' setting, each preset can now specify its modify operation flags",
    value: 6,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "ChangedExposedEntitiesSetToAnOrderedTArray",
    comment: "Change FRCEntityWrapper::ExposedEntities' Set to an Array to retain ordering across sessions",
    value: 7,
    firstAppearance: "5.5.0",
  }),
];

export const FRemoteControlObjectVersionGuid = new CustomVersionGuid<FRemoteControlObjectVersion>({
  friendlyName: "RemoteControlObjectVer",
  guid: FGuid.fromComponents(0x83e2c5c2, 0x364d11eb, 0x90a93cdf, 0xfb2ca371),
  details: FRemoteControlObjectVersionDetails,
});
