// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FRemoteControlProtocolDMXObjectVersion {
  // region Introduced with UE 5.0.0
  /// Roughly corresponds to 4.27
  BeforeCustomVersionWasAdded = 0,
  /// Move Remote Control Protocol DMX Entity Properties to the Extra Setting struct so they can be customized
  MoveRemoteControlProtocolDMXEntityPropertiesToExtraSettingStruct = 1,
  // endregion
}

export const FRemoteControlProtocolDMXObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Roughly corresponds to 4.27",
    value: 0,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "MoveRemoteControlProtocolDMXEntityPropertiesToExtraSettingStruct",
    comment: "Move Remote Control Protocol DMX Entity Properties to the Extra Setting struct so they can be customized",
    value: 1,
    firstAppearance: "5.0.0",
  }),
];

export const FRemoteControlProtocolDMXObjectVersionGuid = new CustomVersionGuid<FRemoteControlProtocolDMXObjectVersion>(
  {
    friendlyName: "RemoteControlProtocolDMXObjectVersion",
    guid: FGuid.fromComponents(0x077636e9, 0x44119fd9, 0x26477f9d, 0x0a7e9f6e),
    details: FRemoteControlProtocolDMXObjectVersionDetails,
  },
);
