// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FRenderingObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added support for 3 band SH in the ILC
  IndirectLightingCache3BandSupport = 1,
  /// Allows specifying resolution for reflection capture probes
  CustomReflectionCaptureResolutionSupport = 2,
  // endregion

  // region Introduced with UE 4.13.0
  RemovedTextureStreamingLevelData = 3,
  /// translucency is now a property which matters for materials with the decal domain
  IntroducedMeshDecals = 4,
  // endregion

  // region Introduced with UE 4.14.0
  /// Reflection captures are no longer prenormalized
  ReflectionCapturesStoreAverageBrightness = 5,
  ChangedPlanarReflectionFadeDefaults = 6,
  RemovedRenderTargetSize = 7,
  /// Particle Cutout (SubUVAnimation) data is now stored in the ParticleRequired Module
  MovedParticleCutoutsToRequiredModule = 8,
  MapBuildDataSeparatePackage = 9,
  /// StaticMesh and SkeletalMesh texcoord size data.
  TextureStreamingMeshUVChannelData = 10,
  /// Added type handling to material normalize and length (sqrt) nodes
  TypeHandlingForMaterialSqrtNodes = 11,
  FixedBSPLightmaps = 12,
  // endregion

  // region Introduced with UE 4.16.0
  DistanceFieldSelfShadowBias = 13,
  FixedLegacyMaterialAttributeNodeTypes = 14,
  ShaderResourceCodeSharing = 15,
  // endregion

  // region Introduced with UE 4.17.0
  MotionBlurAndTAASupportInSceneCapture2d = 16,
  AddedTextureRenderTargetFormats = 17,
  /// Triggers a rebuild of the mesh UV density while also adding an update in the postedit
  FixedMeshUVDensity = 18,
  AddedbUseShowOnlyList = 19,
  // endregion

  // region Introduced with UE 4.18.0
  VolumetricLightmaps = 20,
  // endregion

  // region Introduced with UE 4.19.0
  MaterialAttributeLayerParameters = 21,
  StoreReflectionCaptureBrightnessForCooking = 22,
  /// FModelVertexBuffer does serialize a regular TArray instead of a TResourceArray
  ModelVertexBufferSerialization = 23,
  ReplaceLightAsIfStatic = 24,
  /// Added per FShaderType permutation id.
  ShaderPermutationId = 25,
  // endregion

  // region Introduced with UE 4.20.0
  /// Changed normal precision in imported data
  IncreaseNormalPrecision = 26,
  // endregion

  // region Introduced with UE 4.21.0
  VirtualTexturedLightmaps = 27,
  // endregion

  // region Introduced with UE 4.22.0
  GeometryCacheFastDecoder = 28,
  // endregion

  // region Introduced with UE 4.23.0
  LightmapHasShadowmapData = 29,
  /// Removed old gaussian and bokeh DOF methods from deferred shading renderer.
  DiaphragmDOFOnlyForDeferredShadingRenderer = 30,
  /// Lightmaps replace ULightMapVirtualTexture (non-UTexture derived class) with ULightMapVirtualTexture2D (derived from UTexture)
  VirtualTexturedLightmapsV2 = 31,
  // endregion

  // region Introduced with UE 4.24.0
  SkyAtmosphereStaticLightingVersioning = 32,
  /// UTextureRenderTarget2D now explicitly allows users to create sRGB or non-sRGB type targets
  ExplicitSRGBSetting = 33,
  VolumetricLightmapStreaming = 34,
  /// ShaderModel4 support removed from engine
  RemovedSM4 = 35,
  /// Deterministic ShaderMapID serialization
  MaterialShaderMapIdSerialization = 36,
  // endregion

  // region Introduced with UE 4.25.0
  /// Add force opaque flag for static mesh
  StaticMeshSectionForceOpaqueField = 37,
  /// Add force opaque flag for static mesh
  AutoExposureChanges = 38,
  /// Removed emulated instancing from instanced static meshes
  RemovedEmulatedInstancing = 39,
  /// Added per instance custom data (for Instanced Static Meshes)
  PerInstanceCustomData = 40,
  /// Added material attributes to shader graph to support anisotropic materials
  AnisotropicMaterial = 41,
  /// Add if anything has changed in the exposure, override the bias to avoid the new default propagating
  AutoExposureForceOverrideBiasFlag = 42,
  /// Override for a special case for objects that were serialized and deserialized between versions AutoExposureChanges and AutoExposureForceOverrideBiasFlag
  AutoExposureDefaultFix = 43,
  // endregion

  // region Introduced with UE 4.26.0
  /// Remap Volume Extinction material input to RGB
  VolumeExtinctionBecomesRGB = 44,
  // endregion

  // region Introduced with UE 4.27.0
  /// Add a new virtual texture to support virtual texture light map on mobile
  VirtualTexturedLightmapsV3 = 45,
  // endregion

  // region Introduced with UE 5.3.0
  /// Added fallback target modes including auto to Nanite builder
  NaniteFallbackTarget = 46,
  /// Added support to force Nanite material usage if Nanite mesh builders are also forced.
  NaniteForceMaterialUsage = 47,
  // endregion

  // region Introduced with UE 5.4.0
  /// Custom material expression includes are now serialized & used for DDC key generation
  AddedMaterialExpressionIncludesHash = 48,
  // endregion
}

export const FRenderingObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "IndirectLightingCache3BandSupport",
    comment: "Added support for 3 band SH in the ILC",
    value: 1,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "CustomReflectionCaptureResolutionSupport",
    comment: "Allows specifying resolution for reflection capture probes",
    value: 2,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "RemovedTextureStreamingLevelData",
    value: 3,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "IntroducedMeshDecals",
    comment: "translucency is now a property which matters for materials with the decal domain",
    value: 4,
    firstAppearance: "4.13.0",
  }),
  new VersionDetails({
    name: "ReflectionCapturesStoreAverageBrightness",
    comment: "Reflection captures are no longer prenormalized",
    value: 5,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "ChangedPlanarReflectionFadeDefaults",
    value: 6,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "RemovedRenderTargetSize",
    value: 7,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "MovedParticleCutoutsToRequiredModule",
    comment: "Particle Cutout (SubUVAnimation) data is now stored in the ParticleRequired Module",
    value: 8,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "MapBuildDataSeparatePackage",
    value: 9,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "TextureStreamingMeshUVChannelData",
    comment: "StaticMesh and SkeletalMesh texcoord size data.",
    value: 10,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "TypeHandlingForMaterialSqrtNodes",
    comment: "Added type handling to material normalize and length (sqrt) nodes",
    value: 11,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "FixedBSPLightmaps",
    value: 12,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "DistanceFieldSelfShadowBias",
    value: 13,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "FixedLegacyMaterialAttributeNodeTypes",
    value: 14,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "ShaderResourceCodeSharing",
    value: 15,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "MotionBlurAndTAASupportInSceneCapture2d",
    value: 16,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "AddedTextureRenderTargetFormats",
    value: 17,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "FixedMeshUVDensity",
    comment: "Triggers a rebuild of the mesh UV density while also adding an update in the postedit",
    value: 18,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "AddedbUseShowOnlyList",
    value: 19,
    firstAppearance: "4.17.0",
  }),
  new VersionDetails({
    name: "VolumetricLightmaps",
    value: 20,
    firstAppearance: "4.18.0",
  }),
  new VersionDetails({
    name: "MaterialAttributeLayerParameters",
    value: 21,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "StoreReflectionCaptureBrightnessForCooking",
    value: 22,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "ModelVertexBufferSerialization",
    comment: "FModelVertexBuffer does serialize a regular TArray instead of a TResourceArray",
    value: 23,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "ReplaceLightAsIfStatic",
    value: 24,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "ShaderPermutationId",
    comment: "Added per FShaderType permutation id.",
    value: 25,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "IncreaseNormalPrecision",
    comment: "Changed normal precision in imported data",
    value: 26,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "VirtualTexturedLightmaps",
    value: 27,
    firstAppearance: "4.21.0",
  }),
  new VersionDetails({
    name: "GeometryCacheFastDecoder",
    value: 28,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "LightmapHasShadowmapData",
    value: 29,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "DiaphragmDOFOnlyForDeferredShadingRenderer",
    comment: "Removed old gaussian and bokeh DOF methods from deferred shading renderer.",
    value: 30,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "VirtualTexturedLightmapsV2",
    comment:
      "Lightmaps replace ULightMapVirtualTexture (non-UTexture derived class) with ULightMapVirtualTexture2D (derived from UTexture)",
    value: 31,
    firstAppearance: "4.23.0",
  }),
  new VersionDetails({
    name: "SkyAtmosphereStaticLightingVersioning",
    value: 32,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "ExplicitSRGBSetting",
    comment: "UTextureRenderTarget2D now explicitly allows users to create sRGB or non-sRGB type targets",
    value: 33,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "VolumetricLightmapStreaming",
    value: 34,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "RemovedSM4",
    comment: "ShaderModel4 support removed from engine",
    value: 35,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "MaterialShaderMapIdSerialization",
    comment: "Deterministic ShaderMapID serialization",
    value: 36,
    firstAppearance: "4.24.0",
  }),
  new VersionDetails({
    name: "StaticMeshSectionForceOpaqueField",
    comment: "Add force opaque flag for static mesh",
    value: 37,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AutoExposureChanges",
    comment: "Add force opaque flag for static mesh",
    value: 38,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "RemovedEmulatedInstancing",
    comment: "Removed emulated instancing from instanced static meshes",
    value: 39,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "PerInstanceCustomData",
    comment: "Added per instance custom data (for Instanced Static Meshes)",
    value: 40,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AnisotropicMaterial",
    comment: "Added material attributes to shader graph to support anisotropic materials ",
    value: 41,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AutoExposureForceOverrideBiasFlag",
    comment: "Add if anything has changed in the exposure, override the bias to avoid the new default propagating",
    value: 42,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "AutoExposureDefaultFix",
    comment:
      "Override for a special case for objects that were serialized and deserialized between versions AutoExposureChanges and AutoExposureForceOverrideBiasFlag",
    value: 43,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "VolumeExtinctionBecomesRGB",
    comment: "Remap Volume Extinction material input to RGB",
    value: 44,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "VirtualTexturedLightmapsV3",
    comment: "Add a new virtual texture to support virtual texture light map on mobile",
    value: 45,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "NaniteFallbackTarget",
    comment: "Added fallback target modes including auto to Nanite builder",
    value: 46,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "NaniteForceMaterialUsage",
    comment: "Added support to force Nanite material usage if Nanite mesh builders are also forced.",
    value: 47,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "AddedMaterialExpressionIncludesHash",
    comment: "Custom material expression includes are now serialized & used for DDC key generation",
    value: 48,
    firstAppearance: "5.4.0",
  }),
];
