// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FRigVMObjectVersion {
  // region Introduced with UE 5.3.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// ControlRig & RigVMHost compute and checks VM Hash
  AddedVMHashChecks = 1,
  /// Predicates added to execute operations
  PredicatesAddedToExecuteOps = 2,
  // endregion

  // region Introduced with UE 5.4.0
  /// Storing paths to user defined structs map
  VMStoringUserDefinedStructMap = 3,
  /// Storing paths to user defined enums map
  VMStoringUserDefinedEnumMap = 4,
  /// Storing paths to user defined enums map
  HostStoringUserDefinedData = 5,
  /// VM Memory Storage Struct serialized
  VMMemoryStorageStructSerialized = 6,
  /// VM Memory Storage Defaults generated at VM
  VMMemoryStorageDefaultsGeneratedAtVM = 7,
  /// VM Bytecode Stores the Public Context Path
  VMBytecodeStorePublicContextPath = 8,
  /// Removing unused tooltip property from frunction header
  VMRemoveTooltipFromFunctionHeader = 9,
  // endregion

  // region Introduced with UE 5.5.0
  /// Removing library node FSoftObjectPath from FRigVMGraphFunctionIdentifier
  RemoveLibraryNodeReferenceFromFunctionIdentifier = 10,
  /// Adding variant struct to function identifier
  AddVariantToFunctionIdentifier = 11,
  /// Adding variant to every RigVM asset
  AddVariantToRigVMAssets = 12,
  /// Storing user interface layout within function header
  FunctionHeaderStoresLayout = 13,
  /// Storing user interface relevant pin index in category
  FunctionHeaderLayoutStoresPinIndexInCategory = 14,
  /// Storing user interface relevant category expansion
  FunctionHeaderLayoutStoresCategoryExpansion = 15,
  // endregion

  // region Introduced with UE 5.6.0
  /// Storing function graph collapse node content as part of the header
  RigVMSaveSerializedGraphInGraphFunctionDataAsByteArray = 16,
  /// VM Bytecode Stores the Public Context Path as a FTopLevelAssetPath
  VMBytecodeStorePublicContextPathAsTopLevelAssetPath = 17,
  /// from RigVMCopyOp
  ByteCodeCleanup = 18,
  // endregion
}

export const FRigVMObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "AddedVMHashChecks",
    comment: "ControlRig & RigVMHost compute and checks VM Hash",
    value: 1,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "PredicatesAddedToExecuteOps",
    comment: "Predicates added to execute operations",
    value: 2,
    firstAppearance: "5.3.0",
  }),
  new VersionDetails({
    name: "VMStoringUserDefinedStructMap",
    comment: "Storing paths to user defined structs map",
    value: 3,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "VMStoringUserDefinedEnumMap",
    comment: "Storing paths to user defined enums map",
    value: 4,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "HostStoringUserDefinedData",
    comment: "Storing paths to user defined enums map",
    value: 5,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "VMMemoryStorageStructSerialized",
    comment: "VM Memory Storage Struct serialized",
    value: 6,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "VMMemoryStorageDefaultsGeneratedAtVM",
    comment: "VM Memory Storage Defaults generated at VM",
    value: 7,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "VMBytecodeStorePublicContextPath",
    comment: "VM Bytecode Stores the Public Context Path",
    value: 8,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "VMRemoveTooltipFromFunctionHeader",
    comment: "Removing unused tooltip property from frunction header",
    value: 9,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "RemoveLibraryNodeReferenceFromFunctionIdentifier",
    comment: "Removing library node FSoftObjectPath from FRigVMGraphFunctionIdentifier",
    value: 10,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddVariantToFunctionIdentifier",
    comment: "Adding variant struct to function identifier",
    value: 11,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "AddVariantToRigVMAssets",
    comment: "Adding variant to every RigVM asset",
    value: 12,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FunctionHeaderStoresLayout",
    comment: "Storing user interface layout within function header",
    value: 13,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FunctionHeaderLayoutStoresPinIndexInCategory",
    comment: "Storing user interface relevant pin index in category",
    value: 14,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "FunctionHeaderLayoutStoresCategoryExpansion",
    comment: "Storing user interface relevant category expansion",
    value: 15,
    firstAppearance: "5.5.0",
  }),
  new VersionDetails({
    name: "RigVMSaveSerializedGraphInGraphFunctionDataAsByteArray",
    comment: "Storing function graph collapse node content as part of the header",
    value: 16,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "VMBytecodeStorePublicContextPathAsTopLevelAssetPath",
    comment: "VM Bytecode Stores the Public Context Path as a FTopLevelAssetPath ",
    value: 17,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "ByteCodeCleanup",
    comment: "from RigVMCopyOp",
    value: 18,
    firstAppearance: "5.6.0",
  }),
];

export const FRigVMObjectVersionGuid = new CustomVersionGuid<FRigVMObjectVersion>({
  friendlyName: "Dev-RigVM",
  guid: FGuid.fromComponents(0xdc49959b, 0x53c04de7, 0x9156ea88, 0x5e7c5d39),
  details: FRigVMObjectVersionDetails,
});
