// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FSequencerObjectVersion {
  // region Introduced with UE 4.12.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion

  // region Introduced with UE 4.14.0
  /// Per-platform overrides player overrides for media sources changed name and type.
  RenameMediaSourcePlatformPlayers = 1,
  // endregion

  // region Introduced with UE 4.15.0
  /// Enable root motion isn't the right flag to use, but force root lock
  ConvertEnableRootMotionToForceRootLock = 2,
  /// Convert multiple rows to tracks
  ConvertMultipleRowsToTracks = 3,
  // endregion

  // region Introduced with UE 4.16.0
  /// When finished now defaults to restore state
  WhenFinishedDefaultsToRestoreState = 4,
  // endregion

  // region Introduced with UE 4.19.0
  /// EvaluationTree added
  EvaluationTree = 5,
  /// When finished now defaults to project default
  WhenFinishedDefaultsToProjectDefault = 6,
  // endregion

  // region Introduced with UE 4.20.0
  /// When finished now defaults to project default
  FloatToIntConversion = 7,
  /// Purged old spawnable blueprint classes from level sequence assets
  PurgeSpawnableBlueprints = 8,
  /// Finish UMG evaluation on end
  FinishUMGEvaluation = 9,
  // endregion

  // region Introduced with UE 4.22.0
  /// Manual serialization of float channel
  SerializeFloatChannel = 10,
  /// Change the linear keys so they act the old way and interpolate always.
  ModifyLinearKeysForOldInterp = 11,
  // endregion

  // region Introduced with UE 4.25.0
  /// Full Manual serialization of float channel
  SerializeFloatChannelCompletely = 12,
  // endregion

  // region Introduced with UE 4.27.0
  /// Set ContinuouslyRespawn to false by default, added FMovieSceneSpawnable::bNetAddressableName
  SpawnableImprovements = 13,
  // endregion
}

export const FSequencerObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.12.0",
  }),
  new VersionDetails({
    name: "RenameMediaSourcePlatformPlayers",
    comment:
      "Per-platform overrides player overrides for media sources changed name and type.",
    value: 1,
    firstAppearance: "4.14.0",
  }),
  new VersionDetails({
    name: "ConvertEnableRootMotionToForceRootLock",
    comment:
      "Enable root motion isn't the right flag to use, but force root lock",
    value: 2,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "ConvertMultipleRowsToTracks",
    comment: "Convert multiple rows to tracks",
    value: 3,
    firstAppearance: "4.15.0",
  }),
  new VersionDetails({
    name: "WhenFinishedDefaultsToRestoreState",
    comment: "When finished now defaults to restore state",
    value: 4,
    firstAppearance: "4.16.0",
  }),
  new VersionDetails({
    name: "EvaluationTree",
    comment: "EvaluationTree added",
    value: 5,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "WhenFinishedDefaultsToProjectDefault",
    comment: "When finished now defaults to project default",
    value: 6,
    firstAppearance: "4.19.0",
  }),
  new VersionDetails({
    name: "FloatToIntConversion",
    comment: "When finished now defaults to project default",
    value: 7,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "PurgeSpawnableBlueprints",
    comment:
      "Purged old spawnable blueprint classes from level sequence assets",
    value: 8,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "FinishUMGEvaluation",
    comment: "Finish UMG evaluation on end",
    value: 9,
    firstAppearance: "4.20.0",
  }),
  new VersionDetails({
    name: "SerializeFloatChannel",
    comment: "Manual serialization of float channel",
    value: 10,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "ModifyLinearKeysForOldInterp",
    comment:
      "Change the linear keys so they act the old way and interpolate always.",
    value: 11,
    firstAppearance: "4.22.0",
  }),
  new VersionDetails({
    name: "SerializeFloatChannelCompletely",
    comment: "Full Manual serialization of float channel",
    value: 12,
    firstAppearance: "4.25.0",
  }),
  new VersionDetails({
    name: "SpawnableImprovements",
    comment:
      "Set ContinuouslyRespawn to false by default, added FMovieSceneSpawnable::bNetAddressableName",
    value: 13,
    firstAppearance: "4.27.0",
  }),
];
