// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FShapeComponentCustomVersion {
  // region Introduced with UE 5.1.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Reworked AreaClass Implementation
  AreaClassRework = 1,
  // endregion
}

export const FShapeComponentCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "AreaClassRework",
    comment: "Reworked AreaClass Implementation",
    value: 1,
    firstAppearance: "5.1.0",
  }),
];

export const FShapeComponentCustomVersionGuid = new CustomVersionGuid<FShapeComponentCustomVersion>({
  friendlyName: "ShapeComponentVer",
  guid: FGuid.fromComponents(0xb6e31b1c, 0xd29f11ec, 0x857e9f85, 0x6f9970e2),
  details: FShapeComponentCustomVersionDetails,
});
