// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FSkeletalMeshCustomVersion {
  // region Introduced with UE 4.27.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Remove Chunks array in FStaticLODModel and combine with Sections array
  CombineSectionWithChunk = 1,
  /// Remove FRigidSkinVertex and combine with FSoftSkinVertex array
  CombineSoftAndRigidVerts = 2,
  /// Need to recalc max bone influences
  RecalcMaxBoneInfluences = 3,
  /// Add NumVertices that can be accessed when stripping editor data
  SaveNumVertices = 4,
  /// Regenerated clothing section shadow flags from source sections
  RegenerateClothingShadowFlags = 5,
  /// Share color buffer structure with StaticMesh
  UseSharedColorBufferFormat = 6,
  /// Use separate buffer for skin weights
  UseSeparateSkinWeightBuffer = 7,
  /// Added new clothing systems
  NewClothingSystemAdded = 8,
  /// Cached inv mass data for clothing assets
  CachedClothInverseMasses = 9,
  /// Compact cloth vertex buffer, without dummy entries
  CompactClothVertexBuffer = 10,
  /// Remove SourceData
  RemoveSourceData = 11,
  /// Split data into Model and RenderData
  SplitModelAndRenderData = 12,
  /// Remove triangle sorting support
  RemoveTriangleSorting = 13,
  /// Remove the duplicated clothing sections that were a legacy holdover from when we didn't use our own render data
  RemoveDuplicatedClothingSections = 14,
  /// Remove 'Disabled' flag from SkelMesh asset sections
  DeprecateSectionDisabledFlag = 15,
  /// Add Section ignore by reduce
  SectionIgnoreByReduceAdded = 16,
  /// Adding skin weight profile support
  SkinWeightProfiles = 17,
  /// Remove uninitialized/deprecated enable cloth LOD flag
  RemoveEnableClothLOD = 18,
  // endregion
}

export const FSkeletalMeshCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "CombineSectionWithChunk",
    comment: "Remove Chunks array in FStaticLODModel and combine with Sections array",
    value: 1,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "CombineSoftAndRigidVerts",
    comment: "Remove FRigidSkinVertex and combine with FSoftSkinVertex array",
    value: 2,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RecalcMaxBoneInfluences",
    comment: "Need to recalc max bone influences",
    value: 3,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "SaveNumVertices",
    comment: "Add NumVertices that can be accessed when stripping editor data",
    value: 4,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RegenerateClothingShadowFlags",
    comment: "Regenerated clothing section shadow flags from source sections",
    value: 5,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "UseSharedColorBufferFormat",
    comment: "Share color buffer structure with StaticMesh",
    value: 6,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "UseSeparateSkinWeightBuffer",
    comment: "Use separate buffer for skin weights",
    value: 7,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "NewClothingSystemAdded",
    comment: "Added new clothing systems",
    value: 8,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "CachedClothInverseMasses",
    comment: "Cached inv mass data for clothing assets",
    value: 9,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "CompactClothVertexBuffer",
    comment: "Compact cloth vertex buffer, without dummy entries",
    value: 10,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemoveSourceData",
    comment: "Remove SourceData",
    value: 11,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "SplitModelAndRenderData",
    comment: "Split data into Model and RenderData",
    value: 12,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemoveTriangleSorting",
    comment: "Remove triangle sorting support",
    value: 13,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemoveDuplicatedClothingSections",
    comment:
      "Remove the duplicated clothing sections that were a legacy holdover from when we didn't use our own render data",
    value: 14,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "DeprecateSectionDisabledFlag",
    comment: "Remove 'Disabled' flag from SkelMesh asset sections",
    value: 15,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "SectionIgnoreByReduceAdded",
    comment: "Add Section ignore by reduce",
    value: 16,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "SkinWeightProfiles",
    comment: "Adding skin weight profile support",
    value: 17,
    firstAppearance: "4.27.0",
  }),
  new VersionDetails({
    name: "RemoveEnableClothLOD",
    comment: "Remove uninitialized/deprecated enable cloth LOD flag",
    value: 18,
    firstAppearance: "4.27.0",
  }),
];
