// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FSnapshotCustomVersion {
  // region Introduced with UE 5.1.0
  BeforeCustomVersionWasAdded = 0,
  SubobjectSupport = 1,
  ActorHash = 2,
  ClassArchetypeRefactor = 3,
  OoddleCompression = 4,
  CustomSubobjectSoftObjectPathRefactor = 5,
  SkipSubobjectReferencesWhenSerializingArchetypesRefactor = 6,
  NonEditableComponentsAreCaptured = 7,
  // endregion

  // region Introduced with UE 5.2.0
  FixActorHashSerialize = 8,
  FoliageTypesUnreadable = 9,
  // endregion
}

export const FSnapshotCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "SubobjectSupport",
    value: 1,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ActorHash",
    value: 2,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "ClassArchetypeRefactor",
    value: 3,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "OoddleCompression",
    value: 4,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "CustomSubobjectSoftObjectPathRefactor",
    value: 5,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "SkipSubobjectReferencesWhenSerializingArchetypesRefactor",
    value: 6,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "NonEditableComponentsAreCaptured",
    value: 7,
    firstAppearance: "5.1.0",
  }),
  new VersionDetails({
    name: "FixActorHashSerialize",
    value: 8,
    firstAppearance: "5.2.0",
  }),
  new VersionDetails({
    name: "FoliageTypesUnreadable",
    value: 9,
    firstAppearance: "5.2.0",
  }),
];

export const FSnapshotCustomVersionGuid = new CustomVersionGuid<FSnapshotCustomVersion>({
  friendlyName: "LevelSnapshotVersion",
  guid: FGuid.fromComponents(0x3ef5fdbd, 0x21aaaf1f, 0xbcd6f38f, 0xb3a32521),
  details: FSnapshotCustomVersionDetails,
});
