// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FStateTreeInstanceStorageCustomVersion {
  // region Introduced with UE 5.4.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Added custom serialization
  AddedCustomSerialization = 1,
  // endregion
}

export const FStateTreeInstanceStorageCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "AddedCustomSerialization",
    comment: "Added custom serialization",
    value: 1,
    firstAppearance: "5.4.0",
  }),
];

export const FStateTreeInstanceStorageCustomVersionGuid = new CustomVersionGuid<FStateTreeInstanceStorageCustomVersion>(
  {
    friendlyName: "StateTreeInstanceStorage",
    guid: FGuid.fromComponents(0x60c4f0de, 0x8b264c34, 0xaa937201, 0x5dff09cc),
    details: FStateTreeInstanceStorageCustomVersionDetails,
  },
);
