// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FSVGActorVersion {
  // region Introduced with UE 5.4.0
  PreVersioning = 0,
  ShapeComponents = 1,
  // endregion
}

export const FSVGActorVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "ShapeComponents",
    value: 1,
    firstAppearance: "5.4.0",
  }),
];

export const FSVGActorVersionGuid = new CustomVersionGuid<FSVGActorVersion>({
  friendlyName: "SVGActorVersion",
  guid: FGuid.fromComponents(0x73ed0078, 0x781147bc, 0x8082b640, 0x9aa13df0),
  details: FSVGActorVersionDetails,
});
