// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FTempCustomVersion {
  // region Introduced with UE 4.22.0
  /// Initial version
  FirstVersion = 0,
  // endregion
}

export const FTempCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "FirstVersion",
    comment: "Initial version",
    value: 0,
    firstAppearance: "4.22.0",
  }),
];

export const FTempCustomVersionGuid = new CustomVersionGuid<FTempCustomVersion>({
  friendlyName: "LiveLinkCustomVersion",
  guid: FGuid.fromComponents(0xcb8ab0cd, 0xe78c4bde, 0xa8621393, 0x14e9ef62),
  details: FTempCustomVersionDetails,
});
