// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FTempCustomVersion {
  // region Introduced with UE 4.22.0
  /// Initial version
  FirstVersion = 0,
  // endregion
}

export const FTempCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "FirstVersion",
    comment: "Initial version",
    value: 0,
    firstAppearance: "4.22.0",
  }),
];
