// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FText3DComponentVersion {
  // region Introduced with UE 5.6.0
  PreVersioning = 0,
  Extensions = 1,
  // endregion
}

export const FText3DComponentVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "PreVersioning",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "Extensions",
    value: 1,
    firstAppearance: "5.6.0",
  }),
];

export const FText3DComponentVersionGuid = new CustomVersionGuid<FText3DComponentVersion>({
  friendlyName: "Text3DComponentVersion",
  guid: __INVALID_GUID__,
  details: FText3DComponentVersionDetails,
});
