// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FTG_CustomVersion {
  // region Introduced with UE 5.6.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Added TexturePath to FTG_Texture
  TGTextureAddedTexturePath = 1,
  /// Added BaseOutputSettings to TG_Expression
  TGExpressionAddedBaseOutputSettings = 2,
  /// Added bSRGB to FTG_TextureDescriptor
  TGTextureDescAdded_bSRGB = 3,
  // endregion
}

export const FTG_CustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "TGTextureAddedTexturePath",
    comment: "Added TexturePath to FTG_Texture",
    value: 1,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "TGExpressionAddedBaseOutputSettings",
    comment: "Added BaseOutputSettings to TG_Expression",
    value: 2,
    firstAppearance: "5.6.0",
  }),
  new VersionDetails({
    name: "TGTextureDescAdded_bSRGB",
    comment: "Added bSRGB to FTG_TextureDescriptor",
    value: 3,
    firstAppearance: "5.6.0",
  }),
];

export const FTG_CustomVersionGuid = new CustomVersionGuid<FTG_CustomVersion>({
  friendlyName: "TG_BaseVer",
  guid: FGuid.fromComponents(0x84f72f2e, 0x4181c255, 0x26721cb5, 0x37dfb222),
  details: FTG_CustomVersionDetails,
});
