// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FUE5LWCRenderingStreamObjectVersion {
  // region Introduced with UE 5.0.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Various global shader values converted to LWC types
  LWCTypesInShaders = 1,
  // endregion
}

export const FUE5LWCRenderingStreamObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "LWCTypesInShaders",
    comment: "Various global shader values converted to LWC types",
    value: 1,
    firstAppearance: "5.0.0",
  }),
];
