// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails } from "../registry";

export enum FUE5CookerObjectVersion {
  // region Introduced with UE 5.0.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  // endregion
}

export const FUE5CookerObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "5.0.0",
  }),
];
