// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FVCamCoreCustomVersion {
  // region Introduced with UE 5.4.0
  BeforeCustomVersionWasAdded = 0,
  MoveTargetViewportFromComponentToOutput = 1,
  // endregion
}

export const FVCamCoreCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    value: 0,
    firstAppearance: "5.4.0",
  }),
  new VersionDetails({
    name: "MoveTargetViewportFromComponentToOutput",
    value: 1,
    firstAppearance: "5.4.0",
  }),
];

export const FVCamCoreCustomVersionGuid = new CustomVersionGuid<FVCamCoreCustomVersion>({
  friendlyName: "VCamCoreCustomVersion",
  guid: FGuid.fromComponents(0x31234dbd, 0x21caf31f, 0xaaa7a38f, 0xb4a32531),
  details: FVCamCoreCustomVersionDetails,
});
