// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FVirtualProductionObjectVersion {
  // region Introduced with UE 4.26.0
  /// Before any version changes were made
  BeforeCustomVersionWasAdded = 0,
  /// Aja LTC pin support
  SupportAjaLTCPin = 1,
  // endregion
}

export const FVirtualProductionObjectVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made",
    value: 0,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "SupportAjaLTCPin",
    comment: "Aja LTC pin support ",
    value: 1,
    firstAppearance: "4.26.0",
  }),
];

export const FVirtualProductionObjectVersionGuid = new CustomVersionGuid<FVirtualProductionObjectVersion>({
  friendlyName: "Dev-VirtualProduction",
  guid: FGuid.fromComponents(0x64f58936, 0xfd1b42ba, 0xba967289, 0xd5d0fa4e),
  details: FVirtualProductionObjectVersionDetails,
});
