// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FWaterCustomVersion {
  // region Introduced with UE 4.26.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Refactor of AWaterBody into sub-classes, waves refactor, etc.
  WaterBodyRefactor = 1,
  /// Transfer of TerrainCarvingSettings from landmass to water
  MoveTerrainCarvingSettingsToWater = 2,
  /// WaterBrushManager now can specify its own brush materials instead of using those from the default water editor settings :
  MoveBrushMaterialsToWaterBrushManager = 3,
  /// Deprecate pontoons data on UBuoyancyComponent
  UpdateBuoyancyComponentPontoonsData = 4,
  /// Move JumpFlood materials into AWaterBrushManager
  MoveJumpFloodMaterialsToWaterBrushManager = 5,
  /// Fixup Gerstner waves that were not recomputed at the right moment
  FixupUnserializedGerstnerWaves = 6,
  /// Move responsability of updating the Water MPC params to WaterMesh
  MoveWaterMPCParamsToWaterMesh = 7,
  // endregion

  // region Introduced with UE 5.6.0
  /// Moved where the default water info material is assigned to prevent blocking async load thread
  DefaultWaterInfoMaterialAssignmentMoved = 8,
  // endregion
}

export const FWaterCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "WaterBodyRefactor",
    comment: "Refactor of AWaterBody into sub-classes, waves refactor, etc.",
    value: 1,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "MoveTerrainCarvingSettingsToWater",
    comment: "Transfer of TerrainCarvingSettings from landmass to water",
    value: 2,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "MoveBrushMaterialsToWaterBrushManager",
    comment:
      "WaterBrushManager now can specify its own brush materials instead of using those from the default water editor settings : ",
    value: 3,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "UpdateBuoyancyComponentPontoonsData",
    comment: "Deprecate pontoons data on UBuoyancyComponent",
    value: 4,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "MoveJumpFloodMaterialsToWaterBrushManager",
    comment: "Move JumpFlood materials into AWaterBrushManager",
    value: 5,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "FixupUnserializedGerstnerWaves",
    comment: "Fixup Gerstner waves that were not recomputed at the right moment",
    value: 6,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "MoveWaterMPCParamsToWaterMesh",
    comment: "Move responsability of updating the Water MPC params to WaterMesh",
    value: 7,
    firstAppearance: "4.26.0",
  }),
  new VersionDetails({
    name: "DefaultWaterInfoMaterialAssignmentMoved",
    comment: "Moved where the default water info material is assigned to prevent blocking async load thread",
    value: 8,
    firstAppearance: "5.6.0",
  }),
];

export const FWaterCustomVersionGuid = new CustomVersionGuid<FWaterCustomVersion>({
  friendlyName: "Water",
  guid: FGuid.fromComponents(0x40d2fba7, 0x4b484ce5, 0xb0385a75, 0x884e499e),
  details: FWaterCustomVersionDetails,
});
