// This file is generated by `extract_custom_versions.py`.
// Do not edit manually.
// noinspection JSUnusedGlobalSymbols
//

import { VersionDetails, CustomVersionGuid } from "../CustomVersionGuid";
import { FGuid } from "../../modules/CoreUObject/structs/Guid";

export enum FZoneShapeCustomVersion {
  // region Introduced with UE 5.0.0
  /// Before any version changes were made in the plugin
  BeforeCustomVersionWasAdded = 0,
  /// Added roll to points.
  AddedRoll = 1,
  // endregion
}

export const FZoneShapeCustomVersionDetails: VersionDetails[] = [
  new VersionDetails({
    name: "BeforeCustomVersionWasAdded",
    comment: "Before any version changes were made in the plugin",
    value: 0,
    firstAppearance: "5.0.0",
  }),
  new VersionDetails({
    name: "AddedRoll",
    comment: "Added roll to points.",
    value: 1,
    firstAppearance: "5.0.0",
  }),
];

export const FZoneShapeCustomVersionGuid = new CustomVersionGuid<FZoneShapeCustomVersion>({
  friendlyName: "ZoneShapeComponent",
  guid: FGuid.fromComponents(0xa6fc0560, 0x45b83348, 0xd0e5e18a, 0x3129cd45),
  details: FZoneShapeCustomVersionDetails,
});
